### ISSUE TITLE
Difficulty with setting up Unix

### ISSUE THREAD

**Issue by xzzz3** [nus-cs2030/2122-s1#10]
# Summary
Ubuntu password problem

## Description 
Hello, referring to the setting up unix wiki page, I was able to run the WSL Ubuntu. When I first launched it, it asked for a password but when I tried to enter a new password it did not show anything, and after that it said that the passwords did not match so I proceeded to enter "N" for No when it asked whether I still want to update my password. However, now I am trying to run the sudo apt udpate code and it requires me to enter the password, which I did not set in the first place. I have tried googling to find the default password for new users as well as ways to reset the password, but to no avail. 

## Screenshots (if any): 
![image](https://user-images.githubusercontent.com/88388128/128692384-376715e2-ea60-4630-9726-e4b03dd9164b.png)

**Comment by Irminrics** [comment]
Hi xzzz3,

Have you tried entering in your computer user log in password? Not to worry if you do not see any text appearing when you are typing your password as it is intended as a secret.

**Comment by xzzz3** [comment]
Hello, I just tried to do that but it doesn't work unfortunately :( Also, as I have tried a few times with other potential passwords, it now says that I have 3 incorrect password attempts... I'm not sure whether anything will happen if I continue trying.

**Comment by lkldev** [comment]
Hi xzzz3,
you can login as root by opening a command prompt and type `wsl -u root`, which will allow you to login to wsl as root user. After that you can proceed to change your user account password by typing `passwd xzzz`.

**Comment by xzzz3** [comment]
It worked! Thank you!
