### ISSUE TITLE
Issues Installing wget with Homebrew (MacOS) 

### ISSUE THREAD

**Issue by ReubenChay** [nus-cs2030/2122-s1#11]
Hi! I am having issues with installing wget using Homebrew on macOS. This is what is returned when i try to install wget.

<img width="509" alt="Screenshot 2021-08-09 at 9 51 44 PM" src="https://user-images.githubusercontent.com/77574488/128717277-5c957b15-bcc6-4663-8929-f143669536fd.png">

**Comment by Irminrics** [comment]
Hi ReubenChay, 

It seems like your brew is not installed properly. Could you try do a brew doctor and see what it gives? I recommend you to reinstall brew and try again to see how it works.

Install Homebrew
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"

**Comment by ReubenChay** [comment]
Hi! Thanks for the help. I tried reinstalling brew and i still got the same messages. I could install jdk-11 using some of the other brew commands though, just not the installation of wget
