### ISSUE TITLE
Textbook

### ISSUE THREAD

**Issue by Hongyi6328** [nus-cs2030/2122-s1#12]
Hi all,

What textbook do we need for the module? I cannot find any information about it on Luminus.

**Comment by hwkchia** [comment]
There is no textbook that is suitable for our module.  In fact, the reason for having this repository is to allow students to freely create their own resources in the spirit of peer-learning.  This module is evolving, so it's never taught exactly the same as before.

Anyway, I've also included a weblink in LumiNUS that points to some past semester resource on CS2030S taught by my colleagues.  You may use that as reference, although I will not follow the topics exactly.

**Comment by Hongyi6328** [comment]
Thank you prof!
