### ISSUE TITLE
Checkstyle setup step 2

### ISSUE THREAD

**Issue by ssyap98** [nus-cs2030/2122-s1#14]
Hi, I downloaded the checkstyle jar file and the cs2030 xml file but how do I go about with step 2? How do I check if the 2 files are in the same directory as my java files?

<img width="936" alt="image" src="https://user-images.githubusercontent.com/77193965/128832280-d939bfe0-3cdf-4f52-b5bc-1d33308b198e.png">

**Comment by Irminrics** [comment]
Hi ssyap98,

I think what the instruction meant is to have your future java files saved in the same directory as two of the files that you have just downloaded. You can try create a new empty java file now in the directory that you downloaded the 2 files and perform a checkstyle to see if it is working as intended.

**Comment by ssyap98** [comment]
Thank you! My checkstyle is working as intended!
