### ISSUE TITLE
Storing max/min values in Lab 7

### ISSUE THREAD

**Issue by jaegarpoonyy** [nus-cs2030/2122-s1#146]
# Summary

Unsure how to go through the stream once and only once.

## Description:

Would like to ask for the approach of going through the stream only once and deriving the min, max and average just by going through the stream. I couldn't think of a way to work around deriving the min/max as there are no if/else conditions..

**Comment by jaegarpoonyy** [comment]
Thanks for all the replies! Will relook the question again :)

**Comment by SimJM** [comment]
You can convert the stream into a list, store it, and convert it back to a stream and use it as many times as you want. However, I don't think a good programming design would resort to such methods.

**Comment by chenghong99** [comment]
I believe you are referring to question 4 in particular. I think the objective of the lab is for you to return a one liner pipeline and not convert it to an array, but from the previous threads some people have successfully submitted a solution that converts the original stream into an array and generate multiple streams from there. if you want to you can opt for the easy way out which is to convert into an array and do multiple implementation to it. You do not need if else to find the max and min. you can refer to the java api for methods that can help you find it.

**Comment by jaegarpoonyy** [comment]
Hi! I managed to solve the issue by using the collections method, then producing streams if I need to. 

For those interested, I faced an issue when an empty stream was the input of the function of normalizedMean(), which I overcame by creating more streams with the list and using .max().orElse(0) [or min().orElse()]. 

Thanks for all the help! Will be closing this issue
