### ISSUE TITLE
Fail to install the Java Development kit

### ISSUE THREAD

**Issue by DankaiAndrew** [nus-cs2030/2122-s1#15]
# Summary
After I downloaded java package following the command below,
![image](https://user-images.githubusercontent.com/88640629/128865059-82968c21-3838-4213-b6cf-3bb1c8991168.png)
   
I failed to install the java development kit with the command below and Error appeared 
![image](https://user-images.githubusercontent.com/88640629/128865202-95fa470a-9978-418f-aca8-d9b273bb6421.png)

The error interface:  
![image](https://user-images.githubusercontent.com/88640629/128864667-45dc1e1a-49fe-422a-ae66-c79355b477c7.png)

**Comment by hwkchia** [comment]
Seems like you might not have downloaded openjdk correctly.  May I suggest you remove it:

```rm openlogic*deb```

and issue the `wget` command again?

**Comment by DankaiAndrew** [comment]
I redownloaded the openjdk and problem solved.
Thank you :).
