### ISSUE TITLE
Lab 8 Level 5 method f(int)

### ISSUE THREAD

**Issue by yuyanjulia** [nus-cs2030/2122-s1#150]
## Description:

The f method for int provided in the question seems to use recursion. But when I tried to use it and change the return type to Logger, the Logger does not have the log with it, so it was just `Logger[1]`. 
I have changed my approach to iteration, which worked even without lazy evaluation. But I still want to now how to keep track of log while using recursion! Thank you.

## Screenshots
<img width="550" alt="Screenshot 2021-10-30 at 11 20 41 AM" src="https://user-images.githubusercontent.com/77619767/139518553-6f8d5fe7-a898-4e44-8536-b22956ae6357.png">

**Comment by Eclipse-Dominator** [comment]
I'm actually not sure how to implement it recursively. Mainly because of this what I would consider ridiculous test case:
![image](https://user-images.githubusercontent.com/4567895/139521006-370676e7-443a-4939-80d5-066e8707ad72.png)
Why cant they have an arrow when the mapped value and the initial value is different.
Not having the arrow breaks the whole point of logging a variable in the first place imo.

**Comment by yuyanjulia** [comment]
> I'm actually not sure how to implement it recursively. Mainly because of this ridiculous test case: ![image](https://user-images.githubusercontent.com/4567895/139521006-370676e7-443a-4939-80d5-066e8707ad72.png) Why cant they have an arrow when the mapped value and the initial value is different. Not having the arrow breaks the whole point of logging a variable in the first place IMO.
> 
> The reason your recursive implementation of logger returns just Logger[1] is mainly cos of the listed test case above imo.
> 
> In the end my function is also implemented iteratively.

Looking through the test cases again, I am thinking if we are supposed to implement something like this so that we keep the log lol
<img width="831" alt="Screenshot 2021-10-30 at 1 25 10 PM" src="https://user-images.githubusercontent.com/77619767/139521438-e5d0adcd-2411-4b3e-958e-53011fbcb419.png">

**Comment by Eclipse-Dominator** [comment]
The 2 cases are different one. The 2nd one that keep the log is just the logged data from the returned Logger in flatmap. The 2nd case I'd say is just merging the original history with the new history in Logger returned in flatmap.

Notice how they have the flatMap first mapped to an Identity function before mapping to other different values.

**Comment by cadencjk** [comment]
I  managed to use the recursion using a helper function, declared outside the f() function. Think this may be useful. 
```ruby
Logger<Integer> helper(Logger<Integer> logger) {
    if (logger.get() == 1) {
         //Return something
    }
    return helper(logger.test(predicate, trueLogger, falseLogger));
}
```
I don't think it is possible to use f() function for recursion because it only takes in an Integer and will lose any logger history.

**Comment by chocofats** [comment]
> I managed to use recursion using a helper function, declared outside the f() function. Think this may be useful.
> 
> ```ruby
> Logger<Integer> helper(Logger<Integer> logger) {
>     if (logger.get() == 1) {
>          //Return something
>     }
>     return helper(logger.test(predicate, trueLogger, falseLogger));
> }
> ```
> 
> I don't think it is possible to use f() function for recursion because it only takes in an Integer and will lose any logger history.

It's actually possible to recurs using f() without losing any logger history! Since we are only concerned with logging changes when map() is called, we can use logger.map() within f(). 

So something like:
```
Logger<Integer> f(int n) {
    Logger<Integer> logger = Logger.<Integer>of(n);
    if (n == 1) {
        return logger;
    }
    Logger<Integer> newLogger = logger.test(<predicate>, logger.map(...), logger.map(...)
    return newLogger.flatMap(...);
}
```

**Comment by JavierTham** [comment]
> Looking through the test cases again, I am thinking if we are supposed to implement something like this so that we keep the log lol
> <img alt="Screenshot 2021-10-30 at 1 25 10 PM" width="831" src="https://user-images.githubusercontent.com/77619767/139521438-e5d0adcd-2411-4b3e-958e-53011fbcb419.png">

Yep from here we can see that even if you have a Logger.of(x) somewhere deep inside the flatMap or map, it wouldn't affect the logs. That goes to show that you can use it (somewhat freely) in your recursion, so we don't actually need a helper function.

![image](https://user-images.githubusercontent.com/79401055/139862208-21acd417-6ae0-435f-820c-ba6723c9a36b.png)

From the normal code, we can see that we have **3** if/else if/else conditions, so if we want to make use of our `test()` method, there must be at least 1 **nested** `test()` in another one. It goes like this 
`test( if n == 1,
        return a Logger of n, 
        else test( if x is even,
                      n / 2  then return f(new n),
                      n * 3 + 1 then return f(new n)))`

*hint: as stated above, you can use `Logger.of()` without worry. You need to use map and flatMap because anything done in those 2 methods are the things that will be logged :D atb*

**Comment by yuqitanyq** [comment]
> > I managed to use recursion using a helper function, declared outside the f() function. Think this may be useful.
> > ```ruby
> > Logger<Integer> helper(Logger<Integer> logger) {
> >     if (logger.get() == 1) {
> >          //Return something
> >     }
> >     return helper(logger.test(predicate, trueLogger, falseLogger));
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I don't think it is possible to use f() function for recursion because it only takes in an Integer and will lose any logger history.
> 
> It's actually possible to recurs using f() without losing any logger history! Since we are only concerned with logging changes when map() is called, we can use logger.map() within f().
> 
> So something like:
> 
> ```
> Logger<Integer> f(int n) {
>     Logger<Integer> logger = Logger.<Integer>of(n);
>     if (n == 1) {
>         return logger;
>     }
>     Logger<Integer> newLogger = logger.test(<predicate>, logger.map(...), logger.map(...)
>     return newLogger.flatMap(...);
> }
> ```

Hi, can i just check, what is the function that you will put inside the flat map though?

**Comment by chocofats** [comment]
> > > I managed to use recursion using a helper function, declared outside the f() function. Think this may be useful.
> > > ```ruby
> > > Logger<Integer> helper(Logger<Integer> logger) {
> > >     if (logger.get() == 1) {
> > >          //Return something
> > >     }
> > >     return helper(logger.test(predicate, trueLogger, falseLogger));
> > > }
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > I don't think it is possible to use f() function for recursion because it only takes in an Integer and will lose any logger history.
> > 
> > 
> > It's actually possible to recurs using f() without losing any logger history! Since we are only concerned with logging changes when map() is called, we can use logger.map() within f().
> > So something like:
> > ```
> > Logger<Integer> f(int n) {
> >     Logger<Integer> logger = Logger.<Integer>of(n);
> >     if (n == 1) {
> >         return logger;
> >     }
> >     Logger<Integer> newLogger = logger.test(<predicate>, logger.map(...), logger.map(...)
> >     return newLogger.flatMap(...);
> > }
> > ```
> 
> Hi, can i just check, what is the function that you will put inside the flat map though?

```
return newLogger.flatMap(x -> f(x));
```

**Comment by yuqitanyq** [comment]
> > > > I managed to use recursion using a helper function, declared outside the f() function. Think this may be useful.
> > > > ```ruby
> > > > Logger<Integer> helper(Logger<Integer> logger) {
> > > >     if (logger.get() == 1) {
> > > >          //Return something
> > > >     }
> > > >     return helper(logger.test(predicate, trueLogger, falseLogger));
> > > > }
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > I don't think it is possible to use f() function for recursion because it only takes in an Integer and will lose any logger history.
> > > 
> > > 
> > > It's actually possible to recurs using f() without losing any logger history! Since we are only concerned with logging changes when map() is called, we can use logger.map() within f().
> > > So something like:
> > > ```
> > > Logger<Integer> f(int n) {
> > >     Logger<Integer> logger = Logger.<Integer>of(n);
> > >     if (n == 1) {
> > >         return logger;
> > >     }
> > >     Logger<Integer> newLogger = logger.test(<predicate>, logger.map(...), logger.map(...)
> > >     return newLogger.flatMap(...);
> > > }
> > > ```
> > 
> > 
> > Hi, can i just check, what is the function that you will put inside the flat map though?
> 
> ```
> return newLogger.flatMap(x -> f(x));
> ```

hmmm I'm not sure if I'm doing this right

    Logger<Integer> f(int n) {
        Logger<Integer> logger = Logger.<Integer>of(n);
        if (n == 1) {
            return logger;
        }
        Logger<Integer> newLogger = logger.test(x -> x % 2 == 0, logger.map(x -> x/2), logger.map(x -> (x * 3) + 1));
        return newLogger(x -> f(x));
    }
    
    but somehow this is not working for me though... is there something i did wrong?

**Comment by chocofats** [comment]
> > > > > I managed to use recursion using a helper function, declared outside the f() function. Think this may be useful.
> > > > > ```ruby
> > > > > Logger<Integer> helper(Logger<Integer> logger) {
> > > > >     if (logger.get() == 1) {
> > > > >          //Return something
> > > > >     }
> > > > >     return helper(logger.test(predicate, trueLogger, falseLogger));
> > > > > }
> > > > > ```
> > > > > 
> > > > > 
> > > > >     
> > > > >       
> > > > >     
> > > > > 
> > > > >       
> > > > >     
> > > > > 
> > > > >     
> > > > >   
> > > > > I don't think it is possible to use f() function for recursion because it only takes in an Integer and will lose any logger history.
> > > > 
> > > > 
> > > > It's actually possible to recurs using f() without losing any logger history! Since we are only concerned with logging changes when map() is called, we can use logger.map() within f().
> > > > So something like:
> > > > ```
> > > > Logger<Integer> f(int n) {
> > > >     Logger<Integer> logger = Logger.<Integer>of(n);
> > > >     if (n == 1) {
> > > >         return logger;
> > > >     }
> > > >     Logger<Integer> newLogger = logger.test(<predicate>, logger.map(...), logger.map(...)
> > > >     return newLogger.flatMap(...);
> > > > }
> > > > ```
> > > 
> > > 
> > > Hi, can i just check, what is the function that you will put inside the flat map though?
> > 
> > 
> > ```
> > return newLogger.flatMap(x -> f(x));
> > ```
> 
> hmmm I'm not sure if I'm doing this right but somehow this is not working for me though... is there something i did wrong? it keeps saying runtime exception and the recursion doesn't stop though?
> 
> ```
> Logger<Integer> f(int n) {
>     Logger<Integer> logger = Logger.<Integer>of(n);
>     if (n == 1) {
>         return logger;
>     }
>     Logger<Integer> newLogger = logger.test(x -> x % 2 == 0, logger.map(x -> x/2), logger.map(x -> (x * 3) + 1));
>     return newLogger.flatMap(x -> f(x));
> }
> ```

It looks about right. I'm not sure why you encountered a runtime exception though. 
1 small change, ``` logger.map(x -> (x * 3) + 1) ``` should be refactored as ``` logger.map(x -> 3 * x).map(x -> x + 1) ```

**Comment by yuqitanyq** [comment]
> > > > > > I managed to use recursion using a helper function, declared outside the f() function. Think this may be useful.
> > > > > > ```ruby
> > > > > > Logger<Integer> helper(Logger<Integer> logger) {
> > > > > >     if (logger.get() == 1) {
> > > > > >          //Return something
> > > > > >     }
> > > > > >     return helper(logger.test(predicate, trueLogger, falseLogger));
> > > > > > }
> > > > > > ```
> > > > > > 
> > > > > > 
> > > > > >     
> > > > > >       
> > > > > >     
> > > > > > 
> > > > > >       
> > > > > >     
> > > > > > 
> > > > > >     
> > > > > >   
> > > > > > I don't think it is possible to use f() function for recursion because it only takes in an Integer and will lose any logger history.
> > > > > 
> > > > > 
> > > > > It's actually possible to recurs using f() without losing any logger history! Since we are only concerned with logging changes when map() is called, we can use logger.map() within f().
> > > > > So something like:
> > > > > ```
> > > > > Logger<Integer> f(int n) {
> > > > >     Logger<Integer> logger = Logger.<Integer>of(n);
> > > > >     if (n == 1) {
> > > > >         return logger;
> > > > >     }
> > > > >     Logger<Integer> newLogger = logger.test(<predicate>, logger.map(...), logger.map(...)
> > > > >     return newLogger.flatMap(...);
> > > > > }
> > > > > ```
> > > > 
> > > > 
> > > > Hi, can i just check, what is the function that you will put inside the flat map though?
> > > 
> > > 
> > > ```
> > > return newLogger.flatMap(x -> f(x));
> > > ```
> > 
> > 
> > hmmm I'm not sure if I'm doing this right but somehow this is not working for me though... is there something i did wrong? it keeps saying runtime exception and the recursion doesn't stop though?
> > ```
> > Logger<Integer> f(int n) {
> >     Logger<Integer> logger = Logger.<Integer>of(n);
> >     if (n == 1) {
> >         return logger;
> >     }
> >     Logger<Integer> newLogger = logger.test(x -> x % 2 == 0, logger.map(x -> x/2), logger.map(x -> (x * 3) + 1));
> >     return newLogger.flatMap(x -> f(x));
> > }
> > ```
> 
> It looks about right. I'm not sure why you encountered a runtime exception though. 1 small change, `logger.map(x -> (x * 3) + 1)` should be refactored as `logger.map(x -> 3 * x).map(x -> x + 1)`

Somehow, everything works, except that I'm missing a last print from 2 -> 1... 
Any idea why is this so?
![image](https://user-images.githubusercontent.com/83687861/140687670-3a2eaa0f-703c-45cc-8e9c-40bbceb780f0.png)
