### ISSUE TITLE
Questions regarding the test cases for flatMap given in the question and a bit of rambling..

### ISSUE THREAD

**Issue by Eclipse-Dominator** [nus-cs2030/2122-s1#151]
## background
I already completed the lab. But I have some questions regarding the way the lab required us to implement Logger.

## flatMap method
While the general idea of flatMap is pretty simple. My complaint is with this interaction:
(test case in lvl 3)
> `five.flatMap(x -> Logger.of(x + 1))` returns `Logger[6]` with no history.

I understand the case when if the returned logger's initial data is the same as the original logger's data but not this.
Why shouldn't the above case add a log for `5 -> 6`? The whole point of Logger class is to keep track of changes for a variable. So when a variable changes, why shouldn't it keep track of the change? 
Not having this interaction also makes it very difficult to keep track of variables in recursively defined functions that have a return type of Logger<T>. 

This also brings up my other question regarding the interactions listed in level 3.

What should happen if a variable already have a log but it is flatmapped to another logger with a different initial value.
ie.
`var five = Logger.of(5).map(x -> x+1).map(x -> x * 2); // lazily eval to Logger[12] with history`
`five.flatMap(x -> Logger.of(x+1).map(x -> x+2);`

What should the program return?

**Comment by Irminrics** [comment]
When I was doing level 3, I was also wondering why did the output not log the changes from 5 -> 6 as well and found it pretty odd. May I ask what was your workaround to not print this change in this log?

**Comment by Eclipse-Dominator** [comment]
I dont think the 2nd interaction in my post is included in the test case.
I just keep track of the initial value of the variable returned in the logger returned in flatMap and compare it to the final value of the variable in Logger. If they are the same, I will keep the merge the logged histories of the 2 Logger lazily, If they are different, I'll just discard the original Logger's history.
