### ISSUE TITLE
Not sure how to package in Discrete Event project

### ISSUE THREAD

**Issue by SolarPanda1** [nus-cs2030/2122-s1#156]
```
All classes related to the simulation are to be packaged in cs2030.simulator, with Simulator as the only public facing class. 
```
Does anyone know to complete this Discrete Event packaging requirement? I am unsure about how to package the Simulator. My current setup is
```
package cs2030.simulator;
public class Simulator
...
package cs2030.simulator;
class Event 

import cs2030.simulator.Simulator;
class Main
```
and my <code>MainN</code> has no packaging. I don't think I can submit folders on codeCrunch, so I put all of them together when submitting . It results in a runtime error on my machine
```
Simulator s = new Simulator(arrivalTimes);
Exception in thread "main" java.lang.NoClassDefFoundError: cs2030/simulator/Simulator
        at Main.main(Main.java:16)
```
and codecrunch says
```
Incorrect packaging
Grading terminated.
```
Thanks
Edited: Typo, removed "s" from package cs2030s.simulator;
Edited: Type, add "s" to c2030.simulator;

**Comment by TanPingZhi** [comment]
for each file write the following line on the top
in MainN.java: import cs2030.simulator.Simulator
other files: package cs2030.simulator

**Comment by TanPingZhi** [comment]
also it seems like you added "s"

**Comment by SolarPanda1** [comment]
Yup I did that, accidentally wrote s on my post. 
Still didnt work for me but thanks

**Comment by jerylseow** [comment]
When you say you put all of them together, did you mean all the classes within the same file? You can submit multiple files on CodeCrunch, just shift-click on them in the file selection window. Splitting them should pass the packaging requirement. Apologies if I misunderstood the question!

**Comment by SolarPanda1** [comment]
Oh I mean that I submit multiple files without putting any in a directory. I tried doing

> for each file write the following line on the top
> in MainN.java: import cs2030.simulator.Simulator
> other files: package cs2030.simulator

But it still gave the runtime error
```
Exception in thread "main" java.lang.NoClassDefFoundError: cs2030/simulator/Simulator
        at Main.main(Main.java:14)
Caused by: java.lang.ClassNotFoundException: cs2030.simulator.Simulator
```

**Comment by cliftonfelix** [comment]
> Oh I mean that I submit multiple files without putting any in a directory. I tried doing
> 
> > for each file write the following line on the top
> > in MainN.java: import cs2030.simulator.Simulator
> > other files: package cs2030.simulator
> 
> But it still gave the runtime error
> 
> ```
> Exception in thread "main" java.lang.NoClassDefFoundError: cs2030/simulator/Simulator
>         at Main.main(Main.java:14)
> Caused by: java.lang.ClassNotFoundException: cs2030.simulator.Simulator
> ```
> 
> Strangely, it worked when I put Simulator and other classes in cs2030\simulator\ and the output is correct. Not sure where the error is.

@SolarPanda1 When you wanna run your code on your local computer, I think you need to create a directory cs2030/simulator/ then put all the classes, except MainN, inside there.

**Comment by SolarPanda1** [comment]
After days of pain, the real problem is that LF should be used instead of CRLF. And Main.java should not be submitted. Finally got it to work. Hopefully this will help anybody who encounters the same problem in the future.
