### ISSUE TITLE
Why use reference types?

### ISSUE THREAD

**Issue by wjingen** [nus-cs2030/2122-s1#157]
# Description

Hi all, was watching lecture 5 again and I understand that we need to pass in reference types into ArrayLists, and not primitive types. So when constructing ArrayList, I need to specify the type as "Integer", rather than "int".

My question is; what is the motivation of using reference types? Why use reference types over primitives., or have reference types at all? Thanks.

## Topic:

Specific Topics this question is related to (If Any)

## Screenshots

Screenshots (if any)

**Comment by Irminrics** [comment]
Is there a typo in your example because both looks the same to me? o_o

**Comment by wjingen** [comment]
> Is there a typo in your example because both looks the same to me? o_o

Yes I realised. Don't know why it doesn't appear the way it does when I typed it out. Anyway, I've rephrased the question :)

**Comment by KeithPJX** [comment]
https://docs.oracle.com/javase/tutorial/java/generics/why.html

Generics enable types (classes and interfaces) to be parameters when defining classes. Therefore, a class/interface is needed. Since a primitive type isn’t one, we wrap it inside one. There are differences between primitives and classes/interfaces that make primitives unsuitable for this.

https://www.mindprod.com/jgloss/intvsinteger.html

Hope this helps. Sorry if I am mistaken.

**Comment by xaviertanwc** [comment]
I think it is because ArrayList probably has functions which can only be applied to a class/interface. For instance, the "contains" method might use the class's "equals" method to check if the element is present. This cannot be done if the type taken is a primitive type.

**Comment by thojianxiong** [comment]
I think one of the main differences between primitive and reference types is that primitive types store "actual values" while reference types store a "handle"/"reference" to an object in the heap.  

This also means a primitive type must always have a value given to it while a reference type can be null which means it hasn't been assigned a value. 

This can be seen when using assignment operator(=), 
in the case of primitive types, 
int i = 10;
int j = i;
j++ // i remains 10, j will be 11

for reference types,
List<String> list  = new ArrayList(2);
List<String> copy = list;
copy.add("THIS"); // modifies both copy and list

**Comment by wjingen** [comment]
Thank you all for your answers!
