### ISSUE TITLE
Simulator L5: where do the greedy customers wait?

### ISSUE THREAD

**Issue by TanPingZhi** [nus-cs2030/2122-s1#159]
# Summary
### The problem mentioned: 
A greedy customer always joins the queue with the fewest customers; in the case of a tie, he/she breaks the tie by choosing the first one while scanning from servers 1 to k.
## Description 
So my question is k = humanservers + selfcheckout
or
k = humanservers

Im just wondering cuz itd be odd if the greedy customer do not consider self checkout.
however the naming in the problem seems to suggests that server means humanserver

**Comment by hauchongtang** [comment]
yeah greedy customers still considers self checkout, you can refer to the last test case on codecrunch
