### ISSUE TITLE
Bad Class file - Random Generator

### ISSUE THREAD

**Issue by JustinS00** [nus-cs2030/2122-s1#161]
Hi, I am currently facing a problem when trying to compile the files for Project level 5. I got a bad class file when i tried to compile the code.

I copy and paste the RandomGenerator.class file into cs2030/simulator/ which is together with the rest of the class files.

Anyone able to advise me on how to fix this issue. Thank You!

 
![Capture](https://user-images.githubusercontent.com/88625114/139583212-02af3f10-4974-44ce-9a71-575e12d37928.JPG)
![randomGenError](https://user-images.githubusercontent.com/88625114/139583221-05b8ae21-b6d2-4d05-b77c-f17a8cad5ed3.JPG)

**Comment by RussellDash332** [comment]
You closed this issue? What happened? A self-fix?

**Comment by JustinS00** [comment]
Oh I asked my TA for help so yea its fixed. Anyone with the same issue as me can try doing javac -cp cs2030/simulator -d . *.java instead of just javac -d . *.java
