### ISSUE TITLE
Mutated ArrayList for "five"

### ISSUE THREAD

**Issue by ketamethane** [nus-cs2030/2122-s1#168]
# Summary

## Description:

In order to keep track of all the outputs to map, I decided to use ArrayList containing suppliers to the values. For example, in level 1, `five` would contain an ArrayList `list` containing `() -> 5` (with 5 being a String). After mapping five(`map(x -> x + 1)`, the `list` would contain `() -> 5` and `() -> 6`. 
I planned to loop through the list from index 1 onwards to show the mapping of the output. However, I do not quite understand how `five` 's list mutated, considering my `map` method returned a new Logger.

## Code Snippets
`<R> Logger<R> map(Function<? super T, ? extends R> mapper) {
R r = mapper.apply(this.get());
return new Logger<R>(() -> r, this.list, () -> String.format("%s", r));}`

## Screenshots

Screenshots (if any
![Capture](https://user-images.githubusercontent.com/88729540/139801111-da2cdeb0-8724-4554-81fe-bb1c7db6a1f6.PNG)
)

**Comment by RussellDash332** [comment]
I suggest to not add elements to the existing ArrayList but instead add all the contents of the ArrayList + this new log into another ArrayList. Concept of immutability, I suppose.

**Comment by ketamethane** [comment]
> I suggest to not add elements to the existing ArrayList but instead add all the contents of the ArrayList + this new log into another ArrayList. Concept of immutability, I suppose.
> 
> Update: oh you added a code snippet, I'll update my comments later

It appears I briefly forgot about that concept. I decided to append the elements of `this.list` into a new one, followed by the supplier to be added in as well. I shouldn't have mutated my `this.list` in my constructor as much as possible.

Thanks, Russell!
