### ISSUE TITLE
RandomGenerator not found

### ISSUE THREAD

**Issue by yeehaoo** [nus-cs2030/2122-s1#169]
# Summary
Hi friends, just got started on level 5 of the DES and I'm not sure how to use the provided class.

## Description 
RandomGenerator.class in cs2030.simulator package with the rest of the classes, except the main classes.
The following line is in Simulator::simulate
`RandomGenerator rg = new RandomGenerator(0, 0, 0, 0);`
It's the standard symbol not found error, occurring at both RandomGenerators.
Do I have to include an import statement or something in my Simulator class? I tried it and couldn't get that to work either (I don't think it's necessary anyway, since they're in the same package and RandomGenerator is package private?) 

Thanks in advance!

**Comment by RussellDash332** [comment]
It seems right to me but I'd like to reiterate the overall directory structure so that other viewers may know as well.
```
|
|_ cs2030
|   |_ simulator
|           |_ RandomGenerator.class
|           |_ Simulator.java
|           |_ Event.java
|           |_ ...
|_ Main.java
```

**Comment by yeehaoo** [comment]
> It seems right to me but I'd like to reiterate the overall directory structure so that other viewers may know as well.
> 
> ```
> .
> |
> |_ cs2030
> |   |_ simulator
> |           |_ RandomGenerator.class
> |           |_ Simulator.java
> |           |_ Event.java
> |           |_ ...
> |
> |_ Main.java
> ```
> 
> or perhaps (didn't try if this works)
> 
> ```
> .
> |
> |_ cs2030.simulator
> |       |_ RandomGenerator.class
> |       |_ Simulator.java
> |       |_ Event.java
> |       |_ ...
> |
> |_ Main.java
> ```

Hi Russell, thanks for your reply. Yes, this is how my project is currently set up. Is there anything else you had to do when you first downloaded the class?

**Comment by RussellDash332** [comment]
No, I simply put it inside the cs2030/simulator directory.

**Comment by bingsen0806** [comment]
I am guessing you're probably using some IDE like IntelliJ or Eclipse, and trying to click run. These IDEs will throw error because they can't find RandomGenerator.java

You have 2 options:
1. Run using command line. Don't click the run button on ur IDE. Instead go to the terminal in ur IDE, and type javac *.java, then java Main.java like you usually do.
2. Copy paste the decompiled RandomGenerator.java file (I think someone posted this on some GitHub issue forgot which issue) into ur project, so that your IDE recognizes it. Rmb not to submit the file for ur submission

**Comment by RussellDash332** [comment]
> I am guessing you're probably using some IDE like IntelliJ or Eclipse, and trying to click run. These IDEs will throw error because they can't find RandomGenerator.java
> 
> You have 2 options:
> 
> 1. Run using command line. Don't click the run button on ur IDE. Instead go to the terminal in ur IDE, and type javac *.java, then java Main like you usually do.
> 2. Copy paste the decompiled RandomGenerator.java file (I think someone posted this on some GitHub issue forgot which issue) into ur project, so that your IDE recognizes it. Rmb not to submit the file for ur submission

#127

**Comment by yeehaoo** [comment]
> I am guessing you're probably using some IDE like IntelliJ or Eclipse, and trying to click run. These IDEs will throw error because they can't find RandomGenerator.java
> 
> You have 2 options:
> 
> 1. Run using command line. Don't click the run button on ur IDE. Instead go to the terminal in ur IDE, and type javac *.java, then java Main like you usually do.
> 2. Copy paste the decompiled RandomGenerator.java file (I think someone posted this on some GitHub issue forgot which issue) into ur project, so that your IDE recognizes it. Rmb not to submit the file for ur submission

Nope, I am using vim + javac. Screenshots as attac
![Untitled](https://user-images.githubusercontent.com/23189791/139848956-10d27519-128b-432f-9511-664063182fea.png)
hed!

**Comment by yeehaoo** [comment]
> > I am guessing you're probably using some IDE like IntelliJ or Eclipse, and trying to click run. These IDEs will throw error because they can't find RandomGenerator.java
> > You have 2 options:
> > 
> > 1. Run using command line. Don't click the run button on ur IDE. Instead go to the terminal in ur IDE, and type javac *.java, then java Main like you usually do.
> > 2. Copy paste the decompiled RandomGenerator.java file (I think someone posted this on some GitHub issue forgot which issue) into ur project, so that your IDE recognizes it. Rmb not to submit the file for ur submission
> 
> #127

Ah the second one worked for me. Thanks Bing Sen and Russell!

**Comment by Devvynneo** [comment]
> cs2030/simulator directory

How do I save it in/find this file? 
Because I didn't make this directory though? Is it auto created when you package cs2030.simulator?

**Comment by yeehaoo** [comment]
Hi Devvyn, you should already have a cs2030/simulator directory for the rest of your .java classes, just save the RandomGenerator together with the rest of them. Hope this helps.
