### ISSUE TITLE
How to install the dropdown list plug-in on UNIX 

### ISSUE THREAD

**Issue by ReubenChay** [nus-cs2030/2122-s1#17]
Hi! I was watching the introductory videos and noticed that there was a plug-in installed on the terminal which had dropdown list suggestions where you can easily tab out longer command lines (for eg. just by typing "System" the entire "System.out.print()" can be auto-filled immediately). I know IDEs like intelliJ has this built-in function but how can i get this function for my mac terminal? Or is this not allowed for students in this course

**Comment by hwkchia** [comment]
You can search for the vim javacomplete plugin.  However, during the labs and assessment, this plugin will not be available... nor is it necessary.
