### ISSUE TITLE
Are the values probability of resting and probability of greedy used?

### ISSUE THREAD

**Issue by SolarPanda1** [nus-cs2030/2122-s1#174]
Just started level 5 today of the discrete event simulator. Are the values P_r and P_g used anywhere? They are not in the constructor of RandomGenerator

**Comment by RussellDash332** [comment]
It is not. You trigger the RNG to generate the next number based on P_r and P_g instead.

**Comment by SolarPanda1** [comment]
@RussellDash332 Thanks. But how do I do that?

**Comment by RussellDash332** [comment]
Use the RNG's genRandomRest() and genCustomerType() method and see if it's less than or equal to P_r and P_g or not.
Actually, according to #127, the seed of the RNG for both methods depends on the RNG's seed constructor.
