### ISSUE TITLE
Incorrect packaging Grading terminated.

### ISSUE THREAD

**Issue by joellow88** [nus-cs2030/2122-s1#176]
Anyone received a compilation error of 
"Incorrect packaging
Grading terminated."
on codecrunch for the project?

My code runs on my device but the Codecrunch tests gives me that error. How do I avoid that?

**Comment by Gibson0918** [comment]
Did you try compiling the code on your device with `javac -d . *.java` as well as ensuring that all files except Main1-5.java has `package cs2030.simulator` at the top?

**Comment by SolarPanda1** [comment]
I also had the same issue for days. Look at #156. Each file should use LF instead of CRLF. Also don't submit Main.java

**Comment by joellow88** [comment]
Thanks all! The above suggestions worked :)
