### ISSUE TITLE
"exception IOException is never thrown in body of corresponding try statement" and "error: unreported exception InterruptedException; must be caught or declared to be thrown"

### ISSUE THREAD

**Issue by JadeHZY** [nus-cs2030/2122-s1#179]
# Summary
Hi friends...I am stuck at the start of lab 9. I got these two errors when I compiled. 

_"exception IOException is never thrown in body of corresponding try statement"_ and 
_"error: unreported exception InterruptedException; must be caught or declared to be thrown"_

I guess it is because my try and catch blocks did not filter the exeptions correctly so the later parts still catch the exceptions. I am really confused here so any help is appreciated. 
Description of the question / problem here.
I guess the catch block is checking "if the URL is invalid (not the best behavior)". When I turned response into a CompletableFuture and I want to check if the url is proper I used a get() on the CompletableFuture. The following is my code.

PS. When I change the `IOException | InterruptedException e` to just `catch (Exception e)`, the first error disappear but the  unreported exception InterruptedException is still there. 

## Code Snippets
```
CompletableFuture<HttpResponse<String>> response;
response = client.sendAsync(request, BodyHandlers.ofString());
HttpResponse<String> unboxed = response.get();
```

## Screenshots
<img width="637" alt="1636036411(1)" src="https://user-images.githubusercontent.com/84062701/140332954-633a0945-bd43-44a0-9acc-f50f12dc0683.png">

**Comment by Le-PenDu** [comment]
`HttpClient::sendAsync` does not throw either IOException or InterruptedException, only `send` does. See [this](https://docs.oracle.com/en/java/javase/11/docs/api/java.net.http/java/net/http/HttpClient.html#sendAsync(java.net.http.HttpRequest,java.net.http.HttpResponse.BodyHandler)) for more info

**Comment by BrendanCheong** [comment]
I personally just replaced the catch statement with ```catch (Exception e)``` instead

**Comment by nmtuan2001** [comment]
If you want to catch the Exception, you can use `.handle()`.

For example, 
```(java)
client.sendAsync(request, BodyHandlers.ofString())
    .handle((result, exception) -> {
         .....  // return result or throw new Exception
    }
});
```

And try not to use `.get()` or `.join()`. Instead, you can try wrapping everything inside a CompletableFuture.

**Comment by JadeHZY** [comment]
Thanks for your help! I moved on deleting the error handling block :)
