### ISSUE TITLE
Level 2 Scanner Problem

### ISSUE THREAD

**Issue by JadeHZY** [nus-cs2030/2122-s1#182]
# Summary
Hi friends I am at level 2 of lab 9. The scanner is giving me a headache as it won't take in a CompletableFuture as returned by `BusAPI.getBusStopsServedBy(serviceId))`. 

I tried to use 
```
CompletableFuture<Scanner> sc = CompletableFuture.completedFuture(new Scanner(BusAPI
.getBusStopsServedBy(serviceId).join()));
```
Probably because of the join(), code crunch complains a time(?) error. 

Any suggestions on how to work around the scanner? Any help is appreciated!

## Screenshots
![image](https://user-images.githubusercontent.com/84062701/140474177-d9c0b016-342f-4291-83f2-5090f0568fbe.png)

**Comment by Le-PenDu** [comment]
A Scanner object does not take in a CompletableFuture as an argument. You need to call `thenApply` after calling `BusAPI
.getBusStopsServedBy(serviceId)`, as that will get you the string you need to pass in to your new Scanner object.

**Comment by JadeHZY** [comment]
> A Scanner object does not take in a CompletableFuture as an argument. You need to call `thenApply` after calling `BusAPI .getBusStopsServedBy(serviceId)`, as that will get you the string you need to pass in to your new Scanner object.

OMG I was so stubborn trying to use Scanner outside, probably why I often stuck at weired places. Thanks a lot for the new mindset!
