### ISSUE TITLE
Level 3 lognum test case error

### ISSUE THREAD

**Issue by thojianxiong** [nus-cs2030/2122-s1#186]
# Summary
I'm able to get the required output if I simply enter 
`Logger.<String>of("hello').flatMap(g)` 
but just can't seem to get it to work when I assign it to 
`Logger<Number> lognum = Logger.<String>of("hello').flatMap(g)`
Not very sure what seems to be causing this issue, hope someone can help with this!

## Code Snippets
The error that keeps popping up:
`jshell> Logger<Integer> lognum = Logger.<String>of("hello").flatMap(g)`
`|  Error:`
`|  incompatible types: no instance(s) of type variable(s) U exist so that Logger<? extends U> conforms to Logger<java.lang.Number>`
`|  Logger<Integer> lognum = Logger.<String>of("hello").flatMap(g);`
`|                           ^-----------------------------------^`

![image](https://user-images.githubusercontent.com/66673507/140582615-96d70187-db90-4351-b55d-32bfdb3f96c1.png)

**Comment by brandonrhan** [comment]
I think the error comes from Logger<?> cannot conform to Logger<java.lang.Integer>. I used Logger<? extends Object> for flatmap when I face similar issue. Hope it helps you.

**Comment by thojianxiong** [comment]
Oh I think I typed the wrong error in the comment, it's instead

`| Error:`
`| incompatible types: no instance(s) of type variable(s) U exist so that ``Logger<? extends U> conforms to Logger<java.lang.Number>`
`| Logger<Integer> lognum = Logger.<String>of("hello").flatMap(g);`
`| ^-----------------------------------^`
I used Logger<? extends U> instead of Logger<?> and it caused the above error. @brandonrhan I tried what you suggested but the error is now 
`| incompatible types: no instance(s) of type variable(s) U exist so that ``Logger<? extends java.lang.Object> conforms to Logger<java.lang.Number>`

**Comment by brandonrhan** [comment]
> Oh I think I typed the wrong error in the comment, it's instead
> 
> `| Error:` `` | incompatible types: no instance(s) of type variable(s) U exist so that ``Logger<? extends U> conforms to Logger<java.lang.Number> `` `| Logger<Integer> lognum = Logger.<String>of("hello").flatMap(g);` `| ^-----------------------------------^` I used Logger instead of Logger and it caused the above error. @brandonrhan I tried what you suggested but the error is now `` | incompatible types: no instance(s) of type variable(s) U exist so that ``Logger<? extends java.lang.Object> conforms to Logger<java.lang.Number> ``
Then change Logger<? extends U> to Logger<U> should works

**Comment by thojianxiong** [comment]
I managed to change my code such that flatMap returns a Logger<U> instead of a Logger<? extends U>. I think I was not able to change it to Logger without specifying the type, but anyways thanks for the help @brandonrhan !

**Comment by PokezardVGC** [comment]
DId the same as Mr JX, no idea why but works. Any reason for that @thojianxiong ?

**Comment by callmeqimin** [comment]
i will suggest you just use Logger<? extend Object>, then try to use supplier, then assign the supplier based on the value of get
Logger<? extends U> log = mapper.apply(this.sup.get());
        Supplier<U> sup = () -> log.sup.get();
