### ISSUE TITLE
Level4. What shoule I do after CompletableFuture.allOf?

### ISSUE THREAD

**Issue by brandonrhan** [nus-cs2030/2122-s1#189]
I am struck at level 4. I dont know what to do after 

CompletableFuture.allOf(list.toArray(new CompletableFuture<?>[list.size()]))

How to use this new CompletableFuture<void> to get the description?

And what do I get if I .join(), is it a list or object?

**Comment by malwaregarry** [comment]
Hi, there shouldn't be anything else to do after you .join(). The program will wait for all CompletableFuture in the list to complete before exiting.
What problems are you facing?
