### ISSUE TITLE
Can't copy and paste on Vim

### ISSUE THREAD

**Issue by Hongyi6328** [nus-cs2030/2122-s1#19]
Hi all,

I am catching up with the introductory videos on using Vim. 
https://luminus.nus.edu.sg/modules/95dd46df-bb62-49cd-aae3-d44062df4eb3/multimedia/channels/409a930d-8e34-454a-b4b8-328730533dd5/media/view/0607348f-cf5a-4e84-b4d4-6c1f5c2c81a9

I cannot copy (press Y) and paste (press P) the highlighted text in visual and normal mode. Each time I press P, only a single character where the blinking cursor locates is pasted. What shall I do?

In addition, my interface is not fancy as in the video (circled in red). There is no numbering of lines and no flows of input. 
![image](https://user-images.githubusercontent.com/58073006/129440237-bbab94c8-d8e2-4793-892d-16e950393f93.png)

How my Vim looks is:
![image](https://user-images.githubusercontent.com/58073006/129440220-be29b760-a7be-4ac2-9328-2e1a33e0d69a.png)
![image](https://user-images.githubusercontent.com/58073006/129440255-195f8da1-8065-4c2c-8d5c-517a7a857b02.png)

**Comment by RussellDash332** [comment]
Have you set up ```.vimrc```?

**Comment by Hongyi6328** [comment]
Hi Russell,
I did download .vimrc from this GitHub site.

**Comment by Justinhoejj** [comment]
@Hongyi6328 
Since a character appears on key press, its likely that you were in insert mode. Do verify that you are in normal mode by pressing  the _esc_ key and attempt to copy (y) and paste (p) again. 

You can set number flags and other features by specifying them in the .vimrc file.
![image](https://user-images.githubusercontent.com/68779715/129446782-8dcd8ff0-836b-4db5-b996-44194e78278e.png)
It should look something like this. Note line 9 adds the number flags.

**Comment by Hongyi6328** [comment]
Thank you Justin! The numbering problem is solved now. But there still leaves the problem of copying and pasting. After more tries, I found that I can copy and paste a line in Visual Line mode, and a block in Visual Block mode, but just cannot do copy and paste a piece of highlighted codes in normal mode or visual mode.
When I am writing, there is no such a flow that displays my keyboard activities as shown in the introductory videos, nor are there auto suggestions or predictions of codes.

**Comment by RussellDash332** [comment]
Some features are non-existent by default and optional, e.g. show keyboard activity, code snippet. The ones I can try to tweak are autoclosing brackets and quotations, which can be done by appending the ```.vimrc``` file with this
```viml
inoremap { {}<ESC>ha
inoremap [ []<ESC>ha
inoremap ( ()<ESC>ha
inoremap " ""<ESC>ha
inoremap ' ''<ESC>ha
inoremap /** /**<CR>/<ESC>O
inoremap /* /*<CR>/<ESC>O
```

**Comment by Enigmatrix** [comment]
The keyboard activity flow in the video was a keyboard recorder that he used for the demonstration of vim. It's external, iirc

**Comment by RussellDash332** [comment]
> Thank you Justin! The numbering problem is solved now. But there still leaves the problem of copying and pasting. After more tries, I found that I can copy and paste a line in Visual Line mode, and a block in Visual Block mode, but just cannot do copy and paste a piece of highlighted codes in normal mode or visual mode.
> When I am writing, there is no such a flow that displays my keyboard activities as shown in the introductory videos, nor are there auto suggestions or predictions of codes.

To add up, for code snippets you can refer to #17.

**Comment by Hongyi6328** [comment]
After hours of struggling finding the solution, I finally came up with a solution.
If you also cannot copy and paste in vim, enter `vim .vimrc`, and insert `set mouse=a` anywhere you like in the file.
