### ISSUE TITLE
Project level 3 event leave

### ISSUE THREAD

**Issue by ryan195** [nus-cs2030/2122-s1#194]
I realised that the test cases for level 3 does not account for what happens if a customer just leaves.
I currently have a list of double values for how long the server rests after serving a customer. If a customer just leaves, should I remove the first element of the list because the list would have one additional element otherwise, or should I not bother removing since each server rest time is not tagged to a specific customer?

**Comment by Le-PenDu** [comment]
> I realised that the test cases for level 3 does not account for what happens if a customer just leaves. I currently have a list of double values for how long the server rests after serving a customer. If a customer just leaves, should I remove the first element of the list because the list would have one additional element otherwise, or should I not bother removing since each server rest time is not tagged to a specific customer?

Each server's rest time is not linked to a specific customer. Only when the server is done serving a customer, it will then know how much time to rest

**Comment by ryan195** [comment]
Ahh that makes sense, thank you!

**Comment by BrendanCheong** [comment]
The server rests only when they need to rest and the rest times given in level 3 is shared among all the servers. For my implementation, when the serve time is == 0, the server does not rest but if > 0, the server will rest.  You will need to find a way to update all the servers on the next rest time they can take

**Comment by ryan195** [comment]
Ahh let's go!
