### ISSUE TITLE
Level 5

### ISSUE THREAD

**Issue by callmeqimin** [nus-cs2030/2122-s1#195]
# Summary
in the level 5 test case which require to use test method to print System.out.println("sub1" )and("add1"). my code will println 2 line of same result 
Description of the question / problem here.

## Description:
i used stream in constructing my map method, i try to change use for loop but it also does not work
Clarifications or details with respect to the issue you are facing

## Code Snippets
jshell> five.map(x -> x + 1).
   ...> test(x -> x == 5,
   ...> five.map(x -> { System.out.println("add 1"); return x + 1; }),
   ...> five.map(x -> { System.out.println("sub 1"); return x - 1; }))
sub 1
sub 1
$100 ==> Logger[4]
5 -> 4
Attach code snippets (if any)

## Screenshots

Screenshots (if any)
![image](https://user-images.githubusercontent.com/26117678/140645824-bdce5c92-00a9-4de9-9f51-5d98e5355922.png)
here is my map method:
![image](https://user-images.githubusercontent.com/26117678/140645881-1d76b66a-d5b3-458b-8e1a-aa2982db04be.png)

**Comment by weiquany** [comment]
Hi qimin, not sure if this would help but maybe you can try checking if you are calling `get()` twice in your `toString()` method. I had a similar issue and managed to fix it by changing my `toString()` method.

**Comment by RussellDash332** [comment]
Hi qimin, you can refer to #172 for the explanations!

**Comment by callmeqimin** [comment]
> Hi qimin, not sure if this would help but maybe you can try checking if you are calling `get()` twice in your `toString()` method. I had a similar issue and managed to fix it by changing my `toString()` method.

thank you! i already solved the problem
