### ISSUE TITLE
Mini Project Level 3

### ISSUE THREAD

**Issue by optionalemon** [nus-cs2030/2122-s1#196]
## Description 
I have followed the suggestions by @bingsen0806 on the filter implementation but it seems like I cannot deal with the null values.

My implementation to get the newHead is below, and I did similar approach for newTail, with a `Lazy<Boolean> gotHead` that tells whether the predicate is true
`Lazy<T> newHead = Lazy.<T>of(() -> (gotHead.get().map(x -> x).orElseGet(() -> false)) ? this.head.getContent() : null);`

and this is my `peek()` (which i'm not sure if this implementation is wrong as well
`System.out.println(head.get().map(x -> x.toString()).orElse(""));
 return tail.getContent();`

I get this `NoSuchElementException`
<img width="855" alt="Screenshot 2021-11-07 at 21 29 06" src="https://user-images.githubusercontent.com/86706511/140647065-57dddbbc-10de-4c72-a155-5fbbc795a580.png">

Any suggestion will be helpful!

**Comment by Eclipse-Dominator** [comment]
Hmm, something went wrong in your tail.getContent(). Is your tail a Lazy<InfiniteListImpl<T>>() or something else?

**Comment by TanPingZhi** [comment]
Here's how Id try to debug. You remove one intermediate method at a time. Until it works. If it still doesn't work, your get content is buggy

**Comment by Eclipse-Dominator** [comment]
Wait, fyi if you are on level 3, you shouldn't have a tail that returns a null.

**Comment by weiquany** [comment]
I'd suggest you go with `Lazy<T> newHead = this.head.filter(predicate)` as mentioned by **@bingsen0806**, delegating the filter to Optional and ensuring that your Lazy class utilizes caching.

**Comment by optionalemon** [comment]
> Hmm, something went wrong in your tail.getContent(). Is your tail a `Lazy<InfiniteListImpl<T>>()` or something else?

It is, and it is. My tail.getContent() is `tail.get().orElseGet(null)` and i tested it another time, seems like it gets null pointer exception for null values

**Comment by optionalemon** [comment]
> Here's how Id try to debug. You remove one intermediate method at a time. Until it works. If it still doesn't work, your get content is buggy

Alright, I tried and turns out getting more confusing, I think it's the issue with getContent

**Comment by optionalemon** [comment]
> I'd suggest you go with `Lazy<T> newHead = this.head.filter(predicate)` as mentioned by **@bingsen0806**, delegating the filter to Lazy and ensuring that your Lazy class utilizes caching.

Alright! I'll look into that!

**Comment by optionalemon** [comment]
> Wait, fyi if you are on level 3, you shouldn't have a tail that returns a null.

Really? the question said sth like having an Optional.empty(), without a null, what are the other methods to deal with it?

**Comment by Eclipse-Dominator** [comment]
Oh sry, I mislooked the statement, I thought you are doing if the head is empty tail returns null.

Honestly, I think you are thinking too much here, whether or not your head is empty, it will not terminate the infinitelist.

So regardless of whether or not your head is empty, you can just pass in `tail.map(x -> tail.filter(predicate))`. This works cos tail is also a InfiniteListImpl, you are just making a lazy recursive calls.

Regarding printing out nothing if head is empty, it is an implementation for peek() only. You can just do `System.out.println(head.get().map(x -> x.toString().orElse(""))`

> > Hmm, something went wrong in your tail.getContent(). Is your tail a `Lazy<InfiniteListImpl<T>>()` or something else?
> 
> It is, and it is. My tail.getContent() is `tail.get().orElseGet(null)` and i tested it another time, seems like it gets null pointer exception for null values. I can't figure out what should be returned if `tail.get()` happens to be `Optional.empty()` tho...

I recommend you to look at level 4 if you don't know what to return :)

**Comment by optionalemon** [comment]
Thanks everyone for your help! Ends up it's my map having issue in dealing with Optional.empty() :((
