### ISSUE TITLE
Enquires on Sorting

### ISSUE THREAD

**Issue by yueyin22** [nus-cs2030/2122-s1#197]
This may sound stupid but I don't understand how does the sort function work.

e.g. used in Lambda:
sort((Integer x, Interger y) -> return { y - x }) 

The statement is sorting because of _sort_ or because of the _code inside sort_ ?

And how does y - x return outcomes in descending order? Does it goes by +ve to -ve numbers ?

**Comment by cliftonfelix** [comment]
So, usually inside a Comparator, we have a compareTo method which takes in 2 elements (lets say a and b, in this order) and returns an int.

If the int result is negative, it means a must appear before b when we sort it.
If the int result is positive, a must appear after b.
If its 0, it doesn't matter which one comes first (for this one I'm not that sure, cmiiw)

So, in your case, if you have 2 Integer 5 and 3, 3-5 is -2 which is negative, so 5 must appear before 3 when we sort. Hence, it is sorting in descending order

**Comment by yueyin22** [comment]
> So, usually inside a Comparator, we have a compareTo method which takes in 2 elements (lets say a and b, in this order) and returns an int.
> 
> If the int result is negative, it means a must appear before b when we sort it. If the int result is positive, a must appear after b. If its 0, it doesn't matter which one comes first (for this one I'm not that sure, cmiiw)
> 
> So, in your case, if you have 2 Integer 5 and 3, 3-5 is -2 which is negative, so 5 must appear before 3 when we sort. Hence, it is sorting in descending order

Got it! But what do we do to sort in ascending order instead?

**Comment by RussellDash332** [comment]
> > So, usually inside a Comparator, we have a compareTo method which takes in 2 elements (lets say a and b, in this order) and returns an int.
> > If the int result is negative, it means a must appear before b when we sort it. If the int result is positive, a must appear after b. If its 0, it doesn't matter which one comes first (for this one I'm not that sure, cmiiw)
> > So, in your case, if you have 2 Integer 5 and 3, 3-5 is -2 which is negative, so 5 must appear before 3 when we sort. Hence, it is sorting in descending order
> 
> @cliftonfelix Got it! But what do we do to sort in ascending order instead?

Just flip from `y - x` to `x - y` 😄

**Comment by yueyin22** [comment]
Oh got it! thanks! @RussellDash332 @cliftonfelix
