### ISSUE TITLE
E510: Can't make backup file (add ! to override)

### ISSUE THREAD

**Issue by joellow88** [nus-cs2030/2122-s1#20]
Once I pasted .vimrc into my home directory, I'll always receive this error message when doing :wq in vim. I have to use :wq! in order to quit vim. No backups are created when I use :wq! 

I created the .backup file in my home directory but the error message still shows. What should I do to get rid of the error message?

**Comment by Enigmatrix** [comment]
mind showing us the output of `ls -lah ~`? Can blur out sensitive folders if u need to.

**Comment by joellow88** [comment]
![Picture3](https://user-images.githubusercontent.com/65859436/129453378-0142fbb7-bedd-437f-9029-d04a41dde454.png)

Thats the output when I run ` ls -lah ~`

**Comment by Enigmatrix** [comment]
Looks like the permissions are weird. `chmod 644 .backup` should work.

Your directory needs to be readable and writable, but now it's neither. 644 = readable + writable by you. readable by your group, readable by anyone.

**Comment by joellow88** [comment]
`chmod 644 .backup` worked! Thank you 👍
