### ISSUE TITLE
Did anyone face an error for lab 8 where the final line of 2 -> 1 is not printed?

### ISSUE THREAD

**Issue by yuqitanyq** [nus-cs2030/2122-s1#200]
# Summary

I used the lazy class given in the lecture, and managed to do everything until level 5 for the lab.
However, for the f(int) function, i can't seem to get the last part of 2 -> 1 to print out. I think it's because the recursion stops at n == 1? However, I'm not sure and have been debugging for quite long, but still can't seem to get it.

## Description:

Clarifications or details with respect to the issue you are facing

## Code Snippets

Attach code snippets (if any)

## Screenshots

![image](https://user-images.githubusercontent.com/83687861/140687388-bd390bc4-c37c-473f-a2a5-5771c2a1f0b1.png)

**Comment by yuyanjulia** [comment]
I think if you use flatMap(x -> Logger[1]), the log for this step is not updated. Need to use map somewhere in the case of n=1 too?

**Comment by rui-han-crh** [comment]
I look at the code you have in the other thread that you start, where I also got my own answer from. You're code is by far the same as mine. Can I check if you can successfully output 2 -> 1 with `Logger.of(2).map(x -> x / 2)`? There shouldn't be a need to use map in n = 1, just returning the normal Logger.of(n) will do.

**Comment by yuqitanyq** [comment]
> Can I check if you can successfully output 2 -> 1 with `Logger.of(2).map(x -> x / 2)`? (Edit: oops I mixed up the names...)

oh yeah i can output if i map... hmmm but that shouldn't be the case right?... by right just return logger will be good enough right?

**Comment by yuqitanyq** [comment]
> I think if you use flatMap(x -> Logger[1]), the log for this step is not updated. Need to use map somewhere in the case of n=1 too?

hmmm... is there a way of not needing to map it though...? Cuz i think by right don't need... 

Or is it because my flatMap has some issues...?

**Comment by rui-han-crh** [comment]
Oh, I was just checking if the map was working as intended, which it does seem so. I think I saw your reply in the other f(int) thread, where the code actually seems to be the same as mine. But the double printing is weird. If you just execute the `Logger.of(2).map(x -> x / 2)` it should just give one line of "2 -> 1" right?

I guess if your code is like what you showed, then the problem probably exists in the Logger class itself maybe? 😕

**Comment by yuqitanyq** [comment]
> Oh, I was just checking if the map was working as intended, which it does seem so. I think I saw your reply in the other f(int) thread, where the code actually seems to be the same as mine. But the double printing is weird. If you just execute the `Logger.of(2).map(x -> x / 2)` it should just give one line of "2 -> 1" right?
> 
> I guess if your code is like what you showed, then the problem probably exists in the Logger class itself maybe? 😕

Yeah... i think map works as intended...
![image](https://user-images.githubusercontent.com/83687861/140692372-facae0c6-cf9a-4918-bf84-b132e9f0768a.png)

Any idea which part of logger is causing this? Because after debugging for so long, i still can't see it...

**Comment by AHerdOfHLMilk** [comment]
Based on the fact that it is really only your logging that has issues im guessing the problem should be in your logger class, you could try the iterative version of this to check if the problem is with the logger class or with the recursive implementation of f.
