### ISSUE TITLE
Selection construct detected: if 

### ISSUE THREAD

**Issue by Devvynneo** [nus-cs2030/2122-s1#202]
Hi I got this in after test case check on codecrunch, anyone can enlighten me on whats the error? Thank you!

**Comment by francisyzy** [comment]
You cannot use If to check for things in lab 7.

Same for `Selection construct detected: conditional operator ? :`

**Comment by FYimu** [comment]
Hi this is because Lab 7 is supposed to be for you to exercise the use of streams, so I think prof banned the use of if for this lab specifically.

Under stream, there is a method `filter` very similar to if in the sense that you can filter all elements that satisfy the conditions given. For example,
```
IntStream.range(1, 10).filter(x -> x % 2 == 0).forEach(System.out::println);
```
has the same behavior as
```
for (int i = 1; i < 10; i++) {
    if (i % 2 == 0) {
        System.out.println(i);
    }
}
```
All the best!

**Comment by Devvynneo** [comment]
But I didn't use if in my main class, i used it in my helper class cos I was told there is no restriction on helper class?

**Comment by aaronthamsc98** [comment]
Yeah, I did the same thing previously and realized that the same rules of streams only is applied to helper classes too.

**Comment by PokezardVGC** [comment]
Here is a hint, recall what u learnt in cs1231. Try using logic, convert ur if-else statements to booleans and use "&&" and "||" statements to get ur desired output

**Comment by Devvynneo** [comment]
@PokezardVGC 

Im not from CS bro.... what is cs1231?

**Comment by RussellDash332** [comment]
> @PokezardVGC
> 
> Im not from CS bro.... what is cs1231?

It's a mod about discrete structures. Anyways, what @PokezardVGC is saying is that you can convert if-else statements into just a bunch of boolean statements.

**Comment by Devvynneo** [comment]
@RussellDash332 Interesting, how do I do that! can you give me an example please thank you!

**Comment by PokezardVGC** [comment]
Tkx for the backup boss @RussellDash332 
if (x > 1) :
    if(y > 1):
       return true
    else:
       return false
       
can be made into 
return (x > 1) && (y > 1)

Try working out the flow of ur if-else statements into this form and convert them to booleans

**Comment by Devvynneo** [comment]
@PokezardVGC Thank you! 
but for that method i should i do it if I want to return something other than a boolean value though?
for example
Eg, if x == 1  then i return 0 
and if x != then i return 5

**Comment by PokezardVGC** [comment]
it's not possible to return numbers, other than 0 and 1 from boolean. May I assume ur working on Lv3? If that's the case, u wouldn't need to return any integer values. Just check 2 conditions (if index == 0 and next number is the same) or (next num == curr num && curr num == prev num)

lmk if u still somehow require integer values to be returned, can work around it

**Comment by Devvynneo** [comment]
@PokezardVGC Im working on level 4, where my helper class has already helped me take out the average value, max and min 

but the issue is to execute the formula x - min / max - min, max - min might be equals to 0, so the equation cannot run, so in that case, i wanted to check if max - min == 0, then return 0, if not return the formula

**Comment by PokezardVGC** [comment]
Ah, for that use Math.max()
int num = max - min
denominator = Math.max(1, num)
That way, u can avoid division by zero error. Do smt similar for the numerator, leave it up to u as an exercise

**Comment by Devvynneo** [comment]
@PokezardVGC Thank you so much!! Really appreciate it!

**Comment by Devvynneo** [comment]
Afterwards, I got this error number of occurence, does anyone knows what is wrong?
<img width="508" alt="Screenshot 2021-11-09 at 1 40 08 AM" src="https://user-images.githubusercontent.com/71486247/140791484-c1745f5d-1021-44e3-a5a9-7dfe8721373c.png">
r

**Comment by RussellDash332** [comment]
> Afterwards, I got this error number of occurence, does anyone knows what is wrong? <img alt="Screenshot 2021-11-09 at 1 40 08 AM" width="508" src="https://user-images.githubusercontent.com/71486247/140791484-c1745f5d-1021-44e3-a5a9-7dfe8721373c.png"> r

Probably because you are counting adjacent repeats as one. So 111111 is counted as 5 occurrences instead of the expected answer 1.

**Comment by snoidetx** [comment]
Hi @Devvynneo ,

This is because the purpose of this lab is to use `Stream` over conventional selection (`if` and ternary operators) and iteration (`for` and `while’) method.

**Comment by Devvynneo** [comment]
@RussellDash332 
Oh but I filtered out those who are
