### ISSUE TITLE
Evaluated type is different from original

### ISSUE THREAD

**Issue by PokezardVGC** [nus-cs2030/2122-s1#205]
Wanted to store the list of functions into a List and evaluate it only when called. However, as shown, num is type T, which cannot be assigned ltr to nnum, which is type R. Anyway to get around this? Or is my approach generally wrong? Thanks peeps.

Screenshots (if any)
![image](https://user-images.githubusercontent.com/71965541/140794729-5b10d381-1db2-44eb-aae2-b482d92d3da7.png)

**Comment by PokezardVGC** [comment]
Thanks mate. Just to clarify why it is necessary here. We need to specify input and output type of function to ensure that correct type is being produced?

**Comment by PokezardVGC** [comment]
And any suggestion to work around the assignment of type R to T?

**Comment by SolarPanda1** [comment]
Im guessing you could write
```java
for (Function<? super T, ? > s: this.ls) {
    String string = s.apply(num).toString();
```
Since you only want the String representation, and <code>toString()</code> is the method of all Objects

**Comment by PokezardVGC** [comment]
Ah, seems to get around the problem, thanks for your help mate

**Comment by chenghong99** [comment]
> Im guessing you could write
> 
> ```java
> for (Function<? super T, ? > s: this.ls) {
>     String string = s.apply(num).toString();
> ```
> 
> Since you only want the String representation, and `toString()` is the method of all Objects

Yeap Storing as a sting is a good way since you are intending to print all the toString eventually.
