### ISSUE TITLE
Lab 9 Level 4 order of output

### ISSUE THREAD

**Issue by jbkim1999** [nus-cs2030/2122-s1#206]
Hi everyone,

for my level 4, the approach I used is to keep an ArrayList of promise,
then using allOf().join() by converting the ArrayList into an Array (after the while loop) and thereby outputting the result.

However, it seems that the order of output is different from the one in codecrunch, (in fact it changes every time I submit it) so I can't pass level four.

I also noticed that when I just try using .join() for each individual promise then I can pass level four and get A, but I know that the lab requires to use allOf() as seen from the introduction.

Any tips on this? Any help would be appreciated!

**Comment by brandonrhan** [comment]
I think for level4, we need to use allOf.join() to get an ArrayList of CompletableFuture<BusRoutes>, then after everything is done, we use a for loop to change it to CopletableFuture<String> and then .join() each individual promise and print it out.

**Comment by snoidetx** [comment]
Hi @jbkim1999 !

`allOf` ensures that itself is done after all the promises inside the array is done. So after you call `allOf.join()`, that means all the promises inside the array are done and now you should still need to look through the array/list again to get the result from each promise.

**Comment by FYimu** [comment]
My way of doing is the same as @snoidetx 

Actually even after allOf().join(), the result obtained is null. So I'm kinda curious about how you obtained your randomly ordered result from here haha

**Comment by jbkim1999** [comment]
Thank you everyone! Now I got it :)

In response to @FYimu, what I did was to use **thenAccept()** and use **x -> System.out.println(x)** to print out the response. That was why after calling **allOf(...).join()**, the one that is finished first print out the output first, so the order of output was random.
after each promise is completed.
