### ISSUE TITLE
What does it mean by saved in cs2030/simulator directory?

### ISSUE THREAD

**Issue by Devvynneo** [nus-cs2030/2122-s1#207]
Hi hi, so sorry if this is a simple question but I don't understand what it means by 

Note that RandomGenerator class resides in the cs2030.simulator package. So, RandomGenerator.class should be saved in the cs2030/simulator directory. 

I saved all my project file in a file called project, so I thought I should save the RandomGenerator.class in this project file also but it won't work

Thank yous!

**Comment by RussellDash332** [comment]
Hi, you can refer to #169

**Comment by Devvynneo** [comment]
@RussellDash332 Hi russel thank you so much for getting back to me! 

I have checked that thread but I still dont really understand because 
I don't know where to find this directory cs2030/simulator. 
Because I didn't make this directory, Is it auto created when you package cs2030.simulator?

**Comment by Gibson0918** [comment]
I think it's more of which files should have the line `package cs2030.simulator` so that when you compile using `javac -d . *.java`, it will create the directory cs2030/simulator and deposit those files that belong there.

**Comment by BrendanCheong** [comment]
your project file should look something like this

📦Project
 ┣ 📂cs2030
 ┃ ┗ 📂simulator
 ┃ ┃ ┣ 📜Event.class
 ┃ ┃ ┣ 📜RandomGenerator.class
 ┃ ┃ ┗ 📜Simulator.class
 ┣ 📜Event.java
 ┣ 📜Main.class
 ┣ 📜Main.java
 ┗ 📜Simulator.java

first make sure all your java files are under ```/Project``` and all files (except Main.java) has ```package cs2030.simulator;``` as its first line.
Make sure your ```Main.java``` has ```import cs2030.simulator.SImulator```
Now run ```javac -d . *.java``` in your ```/Project``` folder
You should see ```cs2030/simulator``` folder appearing, here you can find all your ```.class``` files for java files that had that ```package cs2030.simulator;``` line
Now, place your ```RandomGenerator.class``` file in that ```cs2030/simulator``` folder
