### ISSUE TITLE
Size of Class

### ISSUE THREAD

**Issue by Devvynneo** [nus-cs2030/2122-s1#209]
Is there a limit to the size of a class? 

Cos I have classes that has 100 plus lines

**Comment by FYimu** [comment]
Never heard of such restrictions for projects and codecrunch confirm dun have. Not sure if it's possible to write Simulator.java without exceeding 100 lines 🤔 not to mention the javadoc needed

**Comment by RussellDash332** [comment]
> Never heard of such restrictions for projects and codecrunch confirm dun have. Not sure if it's possible to write Simulator.java without exceeding 100 lines 🤔 not to mention the javadoc needed

+1 this, whoever wrote in less than 100 lines is a true alpha.

**Comment by BrendanCheong** [comment]
There's a limit? my files have hundreds of lines lol

**Comment by RussellDash332** [comment]
> There's a limit? my files have hundreds of lines lol

Pride limit 😆
