### ISSUE TITLE
Can't use jshell on stu, anyone else facing this issue?

### ISSUE THREAD

**Issue by josiahoo** [nus-cs2030/2122-s1#211]
Can't seem to run jshell on the stu server. Tried to exit and login to stu again but it still didn't work. It was working perfectly fine earlier in the day but when I logged in tonight I came across this problem. (jshell it works fine on my local cmd though). Anyone have any advice?

![Screenshot 2021-11-09 at 21 06 20 (2)](https://user-images.githubusercontent.com/92449690/140930061-07747eb8-0b22-4a06-9367-d06aef99512d.png)

**Comment by RussellDash332** [comment]
![image](https://user-images.githubusercontent.com/63991775/140930910-cbfb768c-8f7d-49a9-85a4-907056e73050.png)
No, looks good to me

**Comment by huzaifa1712** [comment]
Yep working for me too. Judging from this StackOverflow link it's probably not your fault:
https://stackoverflow.com/questions/8384000/java-io-ioexception-error-11

**Comment by jehousoh** [comment]
Seems to be working for me as well, maybe you can try looking at this to see if anything fits your description: https://stackoverflow.com/questions/13216148/what-throws-an-ioexception-in-java

**Comment by josiahoo** [comment]
Got it working eventually, apparently the previous time i used jshell it didn't close properly, my ta helped me out with it in the end. Thanks for the help everyone!

**Comment by francisyzy** [comment]
> Got it working eventually, apparently the previous time i used jshell it didn't close properly, my ta helped me out with it in the end. Thanks for the help everyone!

Hi, just checking if you know what your TA did to resolve this issue. I am currently facing the same issue now

**Comment by josiahoo** [comment]
> > Got it working eventually, apparently the previous time i used jshell it didn't close properly, my ta helped me out with it in the end. Thanks for the help everyone!
> 
> Hi, just checking if you know what your TA did to resolve this issue. I am currently facing the same issue now
> 
> Edit: never mind i figured it out. there was another instance of jshell running in another tmux session

Oops sorry I just saw this, glad you were able to resolve the issue!!
