### ISSUE TITLE
CodeCrunch COMPILATION ERRORS: null value detected

### ISSUE THREAD

**Issue by yueyin22** [nus-cs2030/2122-s1#213]
Any suggestion on what I should replace null with?

**Comment by hgimleng** [comment]
You may want to try replacing it with Optional.empty().

**Comment by yueyin22** [comment]
> You may want to try replacing it with Optional.empty().

Will give it a try, thanks!

**Comment by dragane359** [comment]
> You may want to try replacing it with Optional.empty().

Which optional methods are restricted btw. thanks!
