### ISSUE TITLE
Javadocs grading 

### ISSUE THREAD

**Issue by Devvynneo** [nus-cs2030/2122-s1#218]
Hihi! Are we graded on Java docs? 

Eg. What we describe in the java docs, the format, whether we have javadocs on all methods etc?

**Comment by BrendanCheong** [comment]
Javadocs are not required for the project

**Comment by weiquany** [comment]
Hi, I think it is optional since java docs were not taught during lectures. It is still good to learn though

**Comment by Eclipse-Dominator** [comment]
I think checkstyle will flag it for the internal test 6 since it is a checkstyle test

**Comment by weiquany** [comment]
> I think checkstyle will flag it for the internal test 6 since it is a checkstyle test

Test case 32 is a check style test, is there is going to be a level 6?

**Comment by RussellDash332** [comment]
> > I think checkstyle will flag it for the internal test 6 since it is a checkstyle test
> 
> Test case 32 is a check style test, is there is going to be a level 6?

No. That's the last. Please let it be the last 😆
