### ISSUE TITLE
Level 5: Unable to use flatMap in test

### ISSUE THREAD

**Issue by xaviertanwc** [nus-cs2030/2122-s1#230]
# Summary

Unable to perform flatMap in test method.

## Description:

Every time I attempt to use a flatMap in my test method I get the following error:
"incompatible types: no instance(s) of type variable(s) U exist so that Logger<? extends U> conforms to Logger<java.lang.Integer>"
Does anybody else experience this? And if so, why does this happen?

## Code Snippets

Attach code snippets (if any)

## Screenshots

Screenshots (if any)

**Comment by lulucopter** [comment]
You may want to take a look at the return type of your flatMap method, and appropriately casting it into its correct type.

**Comment by xaviertanwc** [comment]
@lulucopter It works now! Thank you!
