### ISSUE TITLE
Using Streams in Task 1 and Task 3

### ISSUE THREAD

**Issue by Benjamin-Sim** [nus-cs2030/2122-s1#231]
## Task 1
For task 1, I am able to represent the series of prime numbers using an `IntStream` in ascending order. However, I'm not sure what method to use to count twin primes. `forEach()` allows me to perform some action on every element, but it doesn't allow me to "view" the next/previous element of the stream. So how do I "compare" two consecutive elements to see if their difference is 2?
<br/>

## Task 3
Similarly for task 3, I am able to represent the `int` array using an `IntStream`, but I'm not sure how to "compare" two consecutive elements to see if they are repeated.

**Comment by RussellDash332** [comment]
> ## Task 1
> For task 1, I am able to represent the series of prime numbers using an `IntStream` in ascending order. However, I'm not sure what method to use to count twin primes. `forEach()` allows me to perform some action on every element, but it doesn't allow me to "view" the next/previous element of the stream. So how do I "compare" two consecutive elements to see if their difference is 2?
> 
> ## Task 3
> Similarly for task 3, I am able to represent the `int` array using an `IntStream`, but I'm not sure how to "compare" two consecutive elements to see if they are repeated.

## Task 1
You can use another filter to see if x - 2 or x + 2 (depends on your range) is prime for every prime number x in your stream.

## Task 3
Since the array can be accessed multiple times, you can just use indexing directly and see if they are equal.

**Comment by Benjamin-Sim** [comment]
> > ## Task 1
> > For task 1, I am able to represent the series of prime numbers using an `IntStream` in ascending order. However, I'm not sure what method to use to count twin primes. `forEach()` allows me to perform some action on every element, but it doesn't allow me to "view" the next/previous element of the stream. So how do I "compare" two consecutive elements to see if their difference is 2?
> > ## Task 3
> > Similarly for task 3, I am able to represent the `int` array using an `IntStream`, but I'm not sure how to "compare" two consecutive elements to see if they are repeated.
> 
> ## Task 1
> You can use another filter to see if x - 2 or x + 2 (depends on your range) is prime for every prime number x in your stream.
> 
> ## Task 3
> Since the array can be accessed multiple times, you can just use indexing directly and see if they are equal.

I don't quite understand what you mean. Could you elaborate on your solutions? Thanks!

**Comment by RussellDash332** [comment]
For Task 1, instead of using `forEach`, why not using `filter`? With this, you obtained a stream of twin primes, then use the `.count()` method to return the length of the strean.

The idea of task 3 is finding spots of A, A, B since A is repeated more than twice and the moment this A-sequence ends, we add 1 to the count. E.g. 1, 1, 2, 3, 4, 5, 5, 6 -> 1, 1, 2 and 5, 5, 6 is what we're looking for, so there are 2 repeats.

**Comment by Darren12345677** [comment]
> ## Task 1
> For task 1, I am able to represent the series of prime numbers using an `IntStream` in ascending order. However, I'm not sure what method to use to count twin primes. `forEach()` allows me to perform some action on every element, but it doesn't allow me to "view" the next/previous element of the stream. So how do I "compare" two consecutive elements to see if their difference is 2?
> 
> ## Task 3
> Similarly for task 3, I am able to represent the `int` array using an `IntStream`, but I'm not sure how to "compare" two consecutive elements to see if they are repeated.

For task 3 use intstream to represent the indexes of the int array rather than the array itself. That way you can compare 2 consecutive elements

**Comment by Darren12345677** [comment]
> ## Task 1
> For task 1, I am able to represent the series of prime numbers using an `IntStream` in ascending order. However, I'm not sure what method to use to count twin primes. `forEach()` allows me to perform some action on every element, but it doesn't allow me to "view" the next/previous element of the stream. So how do I "compare" two consecutive elements to see if their difference is 2?
> 
> ## Task 3
> Similarly for task 3, I am able to represent the `int` array using an `IntStream`, but I'm not sure how to "compare" two consecutive elements to see if they are repeated.

For task 1 a twin prime is a prime number whose +2 or  -2 is also a prime number. So technically you don't need access to the  next element you just need to check for the element you are at, whether or not its +2 or -2 is a prime

**Comment by Benjamin-Sim** [comment]
Hi @RussellDash332 and @Darren12345677, thanks for your suggestions. I managed to solve both tasks :)
