### ISSUE TITLE
Can we refer to non-CS2030 (downloaded) notes for PA2?

### ISSUE THREAD

**Issue by yueyin22** [nus-cs2030/2122-s1#233]
E.g. explanations from geeksforgeeks / w3schools ?

**Comment by ovidharshini** [comment]
The previous announcement for PA1 mentions that "it is an open-book assessment, and you may refer to your hardcopy notes or e-materials stored on your own laptop." It only seems natural to regard e-materials as a set that contains the likes of explanations from w3schools and the same set of protocols should hold for PA2 as well. Do correct me on this if I am wrong though (before PA2, preferably)!

If nothing else, it would be useful to keep a summary of important Vim shortcuts on hand (for troublesome operations like 'replace all') and so I'm interested in knowing if this is alright as well.

**Comment by BrendanCheong** [comment]
No you cannot use internet resources, only your own notes
