### ISSUE TITLE
Zork!! Level 5&6

### ISSUE THREAD

**Issue by cindyangXQ** [nus-cs2030/2122-s1#236]
# Summary
Can anyone suggest how to do Zork level 5&6? 

## Description
I had thought about LinkedList, but it was not mentioned in lecture at all. What's your approach?

**Comment by RussellDash332** [comment]
Either LinkedList or ArrayList should work. Basically when you call `go`, return a new room with the previous room added to the list. Then, we call `back`, simply return the last element in the list as the new room and chop off the list accordingly.

**Comment by cindyangXQ** [comment]
Thanks for your reply, but how do you ensure the elements are in the proper sequence in `toString()` if implemented this way? Traverse through the whole list?

**Comment by chngchngchng** [comment]
I did the same thing as Brendan, in which the previous room is stored in an `Optional<Room>`. I think this should be easier than a linked list!

**Comment by RussellDash332** [comment]
> > Either LinkedList or ArrayList should work. Basically when you call `go`, return a new room with the previous room added to the list. Then, we call `back`, simply return the last element in the list as the new room and chop off the list accordingly. For `back`, don't forget to `tick` the room.
> 
> Lists are a good idea, but that might be going against the idea of immutability lol, I just have an attribute `private final Optional<Room> pastRoom` instead, and back will return a new room with the sword removed or a new room with a replaced sword (past room sword with this room sword)

Ah right, even though Lists are mutable, my intention is to make it like an ImList. If you store an `Optional<Room>` instead, I guess that's a similar concept to a LinkedList.

**Comment by cindyangXQ** [comment]
I thought about pastRoom also, but the same question, how to write toString()? Cannot simply pastRoom+... bcuz there is also a sword in the pastRoom.

**Comment by RussellDash332** [comment]
Shouldn't it be `pastRoom.toString()`?

**Comment by Darren12345677** [comment]
> > > Either LinkedList or ArrayList should work. Basically when you call `go`, return a new room with the previous room added to the list. Then, we call `back`, simply return the last element in the list as the new room and chop off the list accordingly. For `back`, don't forget to `tick` the room.
> > 
> > 
> > Lists are a good idea, but that might be going against the idea of immutability lol, I just have an attribute `private final Optional<Room> pastRoom` instead, and back will return a new room with the sword removed or a new room with a replaced sword (past room sword with this room sword)
> 
> I thought about pastRoom also, but the same question, how to write toString()? Cannot simply pastRoom+... bcuz there is also a sword in the pastRoom (suppose there is a sword in the pastRoom and a new sword in the current room).

I used the Optional<Room> method to store the previous room and have an ArrayList to store the items in that room and every time go is called I would create a newlist that would combine items from the old room and the newly created room to be the itemlist for the current room. It involves overriding the equals method for each item class but the toString method becomes simpler

**Comment by TsangZiXuan** [comment]
hello, i am also unsure of how to proceed with these 2 levels! how would the structure of the go method look like? especially the argument format since it takes in a lambda?

**Comment by cindyangXQ** [comment]
> 
> 
> > > > Either LinkedList or ArrayList should work. Basically when you call `go`, return a new room with the previous room added to the list. Then, we call `back`, simply return the last element in the list as the new room and chop off the list accordingly. For `back`, don't forget to `tick` the room.
> > > 
> > > 
> > > Lists are a good idea, but that might be going against the idea of immutability lol, I just have an attribute `private final Optional<Room> pastRoom` instead, and back will return a new room with the sword removed or a new room with a replaced sword (past room sword with this room sword)
> > 
> > 
> > I thought about pastRoom also, but the same question, how to write toString()? Cannot simply pastRoom+... bcuz there is also a sword in the pastRoom (suppose there is a sword in the pastRoom and a new sword in the current room).
> 
> I used the Optional method to store the previous room and have an ArrayList to store the items in that room and every time go is called I would create a newlist that would combine items from the old room and the newly created room to be the itemlist for the current room. It involves overriding the equals method for each item class but the toString method becomes simpler

Thanks Darren. I also got to this solution in the end. It turned out the items and the previous room should be considered separately. 

Thank you guys for the replies!
