### ISSUE TITLE
Submission of files on CodeCrunch returning 'No such file or directory' warning after duplicate files alert

### ISSUE THREAD

**Issue by ovidharshini** [nus-cs2030/2122-s1#237]
# Summary
Submission of files on CodeCrunch sometimes removes duplicate files but later results in a 'file not found' error. 

## Description 
When I submit files on CodeCrunch for my nth try (n>1), there are alerts for duplicate files being uploaded (compared to previous submissions, I presume), which when clicked through, result in a `ctags: Warning: cannot open source file "*.java" : No such file or directory \n error: file not found: *.java` error. 

Every time I have this issue, making small changes to the java files (changing variable names, (sometimes) changing comments etc.) works to sidestep the duplicate files alert altogether, but this is hardly an elegant solution.

I am unsure if I am submitting files on CodeCrunch incorrectly and if this is expected behaviour.  

## Screenshots (if any): 
![image](https://user-images.githubusercontent.com/13196686/141357459-f88ed0c8-cd48-4a5e-b921-5b593dd010a9.png)

**Comment by KeithPJX** [comment]
I did not experience this, I don't think it is expected behavior. I do not see any mentions of duplicate files in the error though. I just submitted each .java file individually, like selecting them all in the File Explorer pop-up and uploading them, maybe you can try doing that if you are not already.

**Comment by weiseng18** [comment]
![image](https://user-images.githubusercontent.com/20338724/141604505-9f434a29-e64d-41cb-871c-cfc1c562e4ea.png)

Did you submit while this notification is there? I've had some issues before (not the same as yours though). I suggest you can try refreshing the page before making another submission

**Comment by francisyzy** [comment]
+1 on the refresh before submitting because I have faced similar issues and a refresh helped fix the problem

**Comment by ovidharshini** [comment]
As a quick update, refreshing the page after every submission has resolved this issue for me. Thanks for the help!
