### ISSUE TITLE
CS2030/S PA2 CodeCrunch Compilation Warnings

### ISSUE THREAD

**Issue by cheeheng** [nus-cs2030/2122-s1#238]
# Summary
CodeCrunch gives a compilation warning on my in-lab submission for PA2, and I am unsure whether this is a grader bug.

## Description 
When I saw my in-lab submission for PA2, my code compiles but I found three compilation warnings as shown in the screenshot below. Do you also have the same compilation warnings? Is this a grader bug?

## Screenshots: 
![image](https://user-images.githubusercontent.com/13196670/141462606-9b285569-db35-4b52-87ac-40eac6e7768a.png)

**Comment by RussellDash332** [comment]
Same here, but I don't think it's an issue on our end.

**Comment by BrendanCheong** [comment]
I think it means that you are not suppose to submit ``Point.java``` and ```Circle.java``` to CodeCrunch for grading (see the last line of the PA2 html). I assume ```SuppressWarnings.java``` is to check for ```SuppressWarnings("unchecked")``` in the code.

**Comment by cheeheng** [comment]
That was the attempt during the assessment, hence I believe that the autograder script messed up and submitted ```Point.java``` and ```Circle.java``` anyway even though that was not necessary.

I think ```SuppressWarnings.java``` checks for any ```SuppressWarnings``` (especially, but not limited to, unchecked types in generics).

**Comment by cheeheng** [comment]
Update: Prof Henry has fixed the grader bug (indeed this was a grader bug), and has regraded the PA2 submissions.
