### ISSUE TITLE
Query on CS2030/S Final Examination Details

### ISSUE THREAD

**Issue by cheeheng** [nus-cs2030/2122-s1#241]
Unless I missed out something, it appears that the prof has yet to reveal the details regarding the ```final``` examination.

1. Is the examination open-book?
2. Does the examination use Examplify?
3. Does the examination use Zoom proctoring?
4. Does the examination involve coding on vim?
5. What is the format of the examination?
6. Are CS2030 and CS2030S students going to take the same paper?

**Comment by Twars2** [comment]
I think prof answered your first question yesterday, It is open book and u can use your hard/softcopy notes (I think your soft copy has to be shown in your screen recording). He said he will release the exam protocols sometime soon this week.

**Comment by cheeheng** [comment]
1) Yes
2) No
3) Yes
6) Most likely
