### ISSUE TITLE
Mini Project Level 5 test case debug

### ISSUE THREAD

**Issue by cadencjk** [nus-cs2030/2122-s1#244]
# Summary
I have completed level5 initially but got stuck at test case 73 for level 6. This was due to some Lazy class issue which I managed to resolve by wrapping my Lazy with a supplier for my head, eg: private final Supplier<Lazy<\T>> head. However, this caused me to get stuck at the level 5 random integer test case.

## Description 
I compared my old code (which is correct for this level) with my new code, and found out that my new code was calling the alternate random numbers (see attached). This means that something is calling the random Integer twice but I can't seem to find it. Did anyone face this issue?

## Screenshots (if any): 
![image](https://user-images.githubusercontent.com/63772723/141671247-a4d1608d-3cc5-472d-83f0-99d47e4062bf.png)

**Comment by weiquany** [comment]
I think Lazy shouldn't be wrapped around a Supplier as that defeats the purpose of having a Lazy class and there would also be a need to call get() twice to retrieve a value. Maybe try to work with your previous version of the code and try to solve the other test case that you were facing issues with.

**Comment by cadencjk** [comment]
@weiquany I thought it was awkward to wrap a supplier around a Lazy too haha but I couldn't think of another way to produce a Empty Lazy. Thanks for the advice, I will try with my old code again!

**Comment by cadencjk** [comment]
Finally solved it after realizing a bug in my improved old code, thanks for the help!
