### ISSUE TITLE
Lab 8 double Sub issue

### ISSUE THREAD

**Issue by Devvynneo** [nus-cs2030/2122-s1#246]
Hihi 

I have seen the previous thread talking about this double sub but I still don't get how to revolve around it? 

I have a list of suppliers<String> 
and each of this suppliers contain the transition eg 4 -> 5 
and I have a Supplier<T> value, that contains the current transition value 

so in the final toString() method 
I just concatenated all the suppliers by using suppliers.get() eg 4 -> 5 + "\n" + 5->6

Then in the final return, I need to return the current value of the class so I used supplier.get() to get the current value 
and then concatenate the above?

**Comment by malwaregarry** [comment]
Hi, you mention that you used a supplier in your toString, I presume for the logs. Did you also call the supplier to get the value for the logger? ie. Logger[5]

If so then that is why the sub printed twice
