### ISSUE TITLE
Collatz conjecture infinite loop 

### ISSUE THREAD

**Issue by Devvynneo** [nus-cs2030/2122-s1#247]
Hi all, this is my collatz conjecture code, why does it result in an endless loop? 

<img width="619" alt="Screenshot 2021-11-14 at 7 59 39 PM" src="https://user-images.githubusercontent.com/71486247/141679956-13c52d38-54d6-45e3-8b68-08147c9fcf16.png">

**Comment by JustinS00** [comment]
I think you will have to reassign the old logger to the new logger. Try this instead
logger = logger.test(x -> x % 2 == 0, logger.map(x -> x/2), logger.map(x -> x *3 + 1));
