### ISSUE TITLE
Lab 8 flatmap issue

### ISSUE THREAD

**Issue by Devvynneo** [nus-cs2030/2122-s1#248]
Hi friendos, 

Why does this equation return me two times of the same value? 

<img width="754" alt="Screenshot 2021-11-14 at 8 42 06 PM" src="https://user-images.githubusercontent.com/71486247/141681494-41e127a9-c25f-44c2-a0f0-42d652ed1428.png">

**Comment by Devvynneo** [comment]
<img width="663" alt="Screenshot 2021-11-14 at 8 47 20 PM" src="https://user-images.githubusercontent.com/71486247/141681684-94b86ac2-3d70-4652-8ca6-6f6c3ae7dcfa.png">

This is my flatmap and map code T.T

**Comment by jackhocheukhei** [comment]
Can show the rest of the code?

**Comment by Devvynneo** [comment]
@jackhocheukhei oh okay!

<img width="615" alt="Screenshot 2021-11-15 at 1 06 05 PM" src="https://user-images.githubusercontent.com/71486247/141725583-ccfcb013-5082-4a58-8075-a65f72555a4c.png"

<img width="658" alt="Screenshot 2021-11-15 at 1 06 21 PM" src="https://user-images.githubusercontent.com/71486247/141725598-eaaf4a69-47d5-4afe-a5b2-11de02931c38.png">
>

**Comment by brandonrhan** [comment]
I think the error might comes from that everytime u flatmap u copy over the first log value into your log, so It will cause a double print. One solution might be u create a ArrayList<Boolean> together with your log to check whether this is a flatmap or not. I am not very sure but hope it helps.
