### ISSUE TITLE
Supplier<Integer> cannot be converted to integer 

### ISSUE THREAD

**Issue by Devvynneo** [nus-cs2030/2122-s1#252]
<img width="754" alt="Screenshot 2021-11-15 at 3 27 23 PM" src="https://user-images.githubusercontent.com/71486247/141739591-8a2067bc-17da-4ba6-8e05-e95df672a736.png">

Hi I saved my int seed value in a Supplier<Integer> seed 

So in the Stream.iterate(this.seed.get(), .....) 
sets the seed taken from the supplier, so the seed value will be an integer
but why is it that I will get this error?

**Comment by kavxya** [comment]
I'm just curious but how did you resolve this?

**Comment by caeliajayne** [comment]
Same! I have the same issue...
