### ISSUE TITLE
Tips for the HTML viewers

### ISSUE THREAD

**Issue by RussellDash332** [nus-cs2030/2122-s1#264]
To everyone who manages to look at the HTML code of the CodeCrunch pages (because there's always that one easter egg), which method did you do to look at it?
- Go to the page, Ctrl+S, and there you have it.
![image](https://user-images.githubusercontent.com/63991775/141959065-5b335d9b-3d18-495d-8949-37ebb9c50c1a.png)

- Ctrl-U the page itself, which I just found out to be viable.
![image](https://user-images.githubusercontent.com/63991775/141959147-2b9a025d-0c2e-4639-aab5-4a53f42e44df.png)

**Comment by BrendanCheong** [comment]
lmao I just copy the outerHtml using google devtools and paste them in a html file

**Comment by lulucopter** [comment]
In google chrome, you can simply right click and click on view page source

**Comment by yuehernkang** [comment]
Thanks for the suggestion!

**Comment by RussellDash332** [comment]
> In google chrome, you can simply right click and click on view page source

Nice this works! Equivalent to Ctrl-U but a good TIL. Thanks!
