### ISSUE TITLE
Simulator Level 1: Sequence of Events at the same time

### ISSUE THREAD

**Issue by cindyangXQ** [nus-cs2030/2122-s1#265]
# Summary
How do you make the events behave like the sample run when they have the same time? 

## Screenshots: 
![屏幕截图 2021-11-16 214403](https://user-images.githubusercontent.com/77227570/141997636-af484462-4dae-4dd7-890f-8dea592d6df6.png)![屏幕截图 2021-11-16 214541](https://user-images.githubusercontent.com/77227570/141997649-cb11f29e-9b93-4a44-b911-98ea29429d7c.png)

**Comment by Devvynneo** [comment]
You need a to implement a comparator<Event> to your priority queue 
You first compare the event timing, 
then you compare the customer id

**Comment by cindyangXQ** [comment]
Thank you!

**Comment by satsuma42** [comment]
I used two separate Comparator<Events>,  one for the actual simulation and one for the presentation of events afterwards.
