### ISSUE TITLE
Error: bad operand types for binary operator '<'

### ISSUE THREAD

**Issue by yueyin22** [nus-cs2030/2122-s1#266]
Any idea how do i solve this? I tried changing the equation to make it > , but it doesn't work.

**Comment by RussellDash332** [comment]
It depends on what methods you are using around this operator. Mind if you elaborate more?

**Comment by EricBryann** [comment]
Maybe can give us further elaborations / screenshots of your methods?

**Comment by yueyin22** [comment]
![image](https://user-images.githubusercontent.com/79189775/142003395-058b908e-1531-4146-867b-db451c40db94.png)
![image](https://user-images.githubusercontent.com/79189775/142003488-159a148e-40d8-4c48-9c90-be89b0640dfd.png)

I tried googling and it was suggested to add additional brackets; tried but still failed

**Comment by EricBryann** [comment]
Does your `getCustomer()` returns you a `Customer` type? I believe in this case it should be `getCustomerId()` to return you an `int` type of a customer Id and compare the Ids instead

**Comment by RussellDash332** [comment]
> Does your `getCustomer()` returns you a `Customer` type? I believe in this case it should be `getCustomerId()` to return you an `int` type of a customer Id and compare the Ids instead

Yup what @EricBryann said is true, you can't directly compare two `Customer` objects with just using `<` or `>`. Maybe you can try to make a method to get an integer instead, should be the similar idea to your other getter methods.

**Comment by yueyin22** [comment]
I got it! thanks! @EricBryann @RussellDash332
