### ISSUE TITLE
Error: cannot assign a value to final variable

### ISSUE THREAD

**Issue by yueyin22** [nus-cs2030/2122-s1#267]
I understand that once a variable/method is declared 'final', we can't assign new values, but is there any way I can get around with it?

E.g., I'll assign new values into my variables, but I'm not sure how to do so after it's been declared final.

**Comment by yueyin22** [comment]
> You can simply create a new Event object!

Sorry, I'm quite confused, could you give me an example?

**Comment by RussellDash332** [comment]
Oh sorry, I mean a new `Server` object. Basically add another private constructor which takes in all the attributes as parameters to assign, so I can do something like `new Server(this.serverID, e.getTime(), ..., true)` as the return value. But this means your `serve` method returns a new `Server` object.

When you call the serve method, it becomes something like `server = server.serve(event)`.

**Comment by yueyin22** [comment]
> Oh sorry, I mean a new `Server` object. Basically add another private constructor which takes in all the attributes as parameters to assign, so I can do something like `new Server(this.serverID, e.getTime(), ..., true)` as the return value. But this means your `serve` method returns a new `Server` object.
> 
> When you call the serve method, it becomes something like `server = server.serve(event)`.

Okay, I'll give it a try.

**Comment by vardentoh** [comment]
You can get around by assigning that final variable to a list or any other object that can have its internal state mutated.

E.g You have a variable `private final int id = 1`, and somehow you would like to give it a new value. Then you can let id be an `ArrayList` or any other mutatable object.

```
private final ArrayList<Integer> id = new ArrayList<>();
id.put(0);       // Insert int 0 into the ArrayList
id.set(0, 1);    // Replace index 0 of ArrayList with int 1
```

Won't recommend it. Just additional information that might be useful for you to know.

**Comment by lhy-hoyin** [comment]
You can "change" the value by creating a new object with the newer value.

For example:
```java
class Counter {
    private final int value;
    
    Counter() { value = 0; }
    Counter(int val) { value = val; }
    
    Counter changeValue(int newValue) {
        return new Counter(newValue);
    }
}
```

Usage:
```java
Counter c1 = new Counter(); //c1value = 0
Counter c2 = c1.changeValue(2); //c1value = 0 (immutable), c2value = 2
// To "change" the value inside of c1
c1 = c1.changeValue(3) //c1value = 3
```

**Comment by yueyin22** [comment]
> You can "change" the value by creating a new object with the newer value.
> 
> For example:
> 
> ```java
> class Counter {
>     private final int value;
>     
>     Counter() { value = 0; }
>     private Counter(int val) { value = val; } // private to ensure only it can change the value of itself
>     
>     Counter changeValue(int newValue) {
>         return new Counter(newValue);
>     }
> }
> ```
> 
> Usage:
> 
> ```java
> Counter c1 = new Counter(); //c1value = 0
> Counter c2 = c1.changeValue(2); //c1value = 0 (immutable), c2value = 2
> // To "change" the value inside of c1
> c1 = c1.changeValue(3) //c1value = 3
> ```



Thanks for the example!! However, in my case, my return type is not the same. This is my server class, but i am returning an **Event** type. So it does not work in my case (I tried). 


```
public class Server {
    private final int serverID;
    private final double serviceStartTime;
    private final double serviceEndTime;
    private final int numServed;
    private final boolean isServing;
    private final boolean isResting;

    private final LinkedList<Event> queue = new LinkedList<Event>();

    public Server(int index) {
        this.serverID = serverID;
        this.serviceStartTime = 0.0;
        this.serviceEndTime = 0.0;
        this.numServed = 0;
        this.isServing = false;
        this.isResting = false;
    }

    public Event serve(Event e) {
        this.serviceStartTime = e.getTime();
        this.numServed++;
        this.isServing = true;
        this.serviceEndTime = e.getTime() + RandomGen.randomG.genServiceTime();
        
        // Event(customer, time, eventType, server)
        // eventType: 5 = CUSTOMER_DONE
        return new Event(e.getCustomer(), this.endTime, 5, this);
        
    }
```

**Comment by kxshxsh** [comment]
> > You can "change" the value by creating a new object with the newer value.
> > For example:
> > ```java
> > class Counter {
> >     private final int value;
> >     
> >     Counter() { value = 0; }
> >     private Counter(int val) { value = val; } // private to ensure only it can change the value of itself
> >     
> >     Counter changeValue(int newValue) {
> >         return new Counter(newValue);
> >     }
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Usage:
> > ```java
> > Counter c1 = new Counter(); //c1value = 0
> > Counter c2 = c1.changeValue(2); //c1value = 0 (immutable), c2value = 2
> > // To "change" the value inside of c1
> > c1 = c1.changeValue(3) //c1value = 3
> > ```
> 
> Thanks for the example!! However, in my case, my return type is not the same. This is my server class, but i am returning an **Event** type. So it does not work in my case (I tried).
> 
> ```
> public class Server {
>     private final int serverID;
>     private final double serviceStartTime;
>     private final double serviceEndTime;
>     private final int numServed;
>     private final boolean isServing;
>     private final boolean isResting;
> 
>     private final LinkedList<Event> queue = new LinkedList<Event>();
> 
>     public Server(int index) {
>         this.serverID = serverID;
>         this.serviceStartTime = 0.0;
>         this.serviceEndTime = 0.0;
>         this.numServed = 0;
>         this.isServing = false;
>         this.isResting = false;
>     }
> 
>     public Event serve(Event e) {
>         this.serviceStartTime = e.getTime();
>         this.numServed++;
>         this.isServing = true;
>         this.serviceEndTime = e.getTime() + RandomGen.randomG.genServiceTime();
>         
>         // Event(customer, time, eventType, server)
>         // eventType: 5 = CUSTOMER_DONE
>         return new Event(e.getCustomer(), this.endTime, 5, this);
>         
>     }
> ```

Hi! Let me help you out:))
In your serve method, you're trying to update your final class fields which isn't allowed. The only way to update them is to call a new instance of Server. But I don't think your method will do what you want it to do in the best way. Maybe you can create a method to 'update' your Server which will basically create a new Server with all these new values that you're deriving from your Event object and then return that object. And then you can keep your serve method the way it is after some minor changes (such as abstracting the first half of it out).

**Comment by yueyin22** [comment]
Thanks all!
