### ISSUE TITLE
How is the project graded?

### ISSUE THREAD

**Issue by yuyanjulia** [nus-cs2030/2122-s1#268]
I am curious about the grading of project. Is it graded by submission (we get all 10% as long as codecruch shows A)? Or are there other marking criteria? I remember my TA mentioned Style is graded, but codecrunch already gave me A when I am halfway writing my Javadocs. 

For Javadocs, is it correct to say that we need to write Javadocs for `Simulator.java` only, as it is the only public facing class? How can I view the API generated?

**Comment by RussellDash332** [comment]
> I am curious about the grading of project. Is it graded by submission (we get all 10% as long as codecruch shows A)? Or are there other marking criteria? I remember my TA mentioned Style is graded, but codecrunch already gave me A when I am halfway writing my Javadocs.
> 
> For Javadocs, is it correct to say that we need to write Javadocs for `Simulator.java` only, as it is the only public facing class? How can I view the API generated?

You can type in the command `javadoc Simulator.java`. It will generate all the HTML files!

**Comment by yuyanjulia** [comment]
> > I am curious about the grading of project. Is it graded by submission (we get all 10% as long as codecruch shows A)? Or are there other marking criteria? I remember my TA mentioned Style is graded, but codecrunch already gave me A when I am halfway writing my Javadocs.
> > For Javadocs, is it correct to say that we need to write Javadocs for `Simulator.java` only, as it is the only public facing class? How can I view the API generated?
> 
> You can type in the command `javadoc Simulator.java`. It will generate all the HTML files!

wow magic! thank you

**Comment by throwawayAcc123** [comment]
iirc Prof mentioned that Javadocs is not needed for us this time round, and the style grading will be done by an autograder (kind of like codecrunch?)

**Comment by dragane359** [comment]
> iirc Prof mentioned that Javadocs is not needed for us this time round, and the style grading will be done by an autograder (kind of like codecrunch?)

I think style grading is the 32nd test case, so yeah on codecrunch

**Comment by aaronthamsc98** [comment]
I asked my TA about this and he said as long as codecrunch gives an A grade, it should be fine.

**Comment by kxshxsh** [comment]
wait so are we required to write javadocs?

**Comment by dragane359** [comment]
> wait so are we required to write javadocs?

nope

**Comment by cliftonfelix** [comment]
> > wait so are we required to write javadocs?
> 
> nope

Wah thanks for the clarification. I thought we need to write javadocs :)

**Comment by upabove122** [comment]
I actually asked this question a while back #68
