### ISSUE TITLE
Difference between runnable and supplier

### ISSUE THREAD

**Issue by ryan195** [nus-cs2030/2122-s1#270]
Would the difference between runnable and supplier be that runnable is just some function that gets executed when called, with no output, whereas supplier outputs the executed function's output?

**Comment by Albunist** [comment]
I guess so, since runnable accepts nothing and returns nothing(void) since its only abstract method run accepts nothing and returns void.

**Comment by BrendanCheong** [comment]
Supplier => () -> returns T (must return a thing)
Runnable => () -> void (like System.ou.println) doesn't return anything

**Comment by chenghong99** [comment]
Runnable does not return anything. Supplier has a return value

**Comment by ryan195** [comment]
Thanks everyone for the responses! I have a better idea of what runnable and supplier does now!
