### ISSUE TITLE
Is 'instanceof' allowed for both projects?

### ISSUE THREAD

**Issue by Benjamin-Sim** [nus-cs2030/2122-s1#271]
## Description 
For both projects (Discrete Event Simulator and Infinite List), is the `instanceof` keyword allowed?

i.e. Will CodeCrunch accept `instanceof`?

**Comment by JadeHZY** [comment]
From my experience, instanceof is not allowed for Project(shop one).

**Comment by cadencjk** [comment]
Nope i don't think so, but you can have a method such as:
```
String getType() {
    return "Serve Event";
}
```
in your "child" classes. Then to check the type of class in the main class, do something like this:
```
if (class.getType().equals("Serve Event") {
   // Do this
}
```
Not recommended but it is a way to get around.

**Comment by BrendanCheong** [comment]
> Nope i don't think so, but you can have a method such as:
> 
> ```
> String getType() {
>     return "Serve Event";
> }
> ```
> 
> in your "child" classes. Then to check the type of class in the main class, do something like this:
> 
> ```
> if (class.getType().equals("Serve Event") {
>    // Do this
> }
> ```
> 
> Not recommended but it is a way to get around.

Why not let the event have a boolean method to check if 2 strings are same (input string and attribute string)

**Comment by yuyanjulia** [comment]
I think you can use `instanceof` to check if the class type is the same as the current class type. For example, in the `Logger` lab, `if (value instanceof Logger) { throw new IllegalArgumentException("already a Logger"); `
But you cannot check other class types, like checking `if (event instanceof Arrive)` in `Simulator.java`

**Comment by brandonrhan** [comment]
Nope instanceof can not be used. What u can do is to create methods like isSelfCheckServer(), isWait(), isServe() etc in your code to get pass of it

**Comment by chenghong99** [comment]
nope instanceof, null and Optional .get()/isPresent()/isEmpty() are all nt allowed

**Comment by Hongyi6328** [comment]
I think instanceof is allowed in the mini-project. (update me if I am wrong because I tried this some time ago)
all java reflections, including getName(), getClass(), instanceof,  are not allowed in the project.

**Comment by Tan-Jin-Waye** [comment]
I assume there's a better way, but here's my take with regards to event type checking:

Assign each concrete event type a `static` 'priority' or 'identifier' integer i.e. `Arrival` events could be 1, `Wait` events could be 2, etc.

I have found two uses for doing so:
The first is that you can use a `switch` block to determine which event type is currently being evaluated, and accordingly deal with each event type in the cases.

The second is that if, for any reason, you need to order two events that occur at the same time, this integer score could provide an additional tiebreaker to determine which should go first.

Again, probably better ways to implement this, but just my two cents.
