### ISSUE TITLE
Level 5 -> Codecrunch 5-4

### ISSUE THREAD

**Issue by mewrion** [nus-cs2030/2122-s1#274]
# Summary
**1 2 0 3 20 1.0 1.0 0.1 0.5 0.9**

Anyone experience an issue where the greedy customer is not joining the correct queue?
Specifically, seems like my customer 15 keeps joining server 2, instead of server 1! I passed all other test cases after checking, just this 1 that is bugging me
## Description 
Describe the problem and code snippets if necessary 

## Screenshots (if any): 
Insert Images here if necessary

**Comment by marcusczh** [comment]
It seems like that should be the correct output, customer 15 should wait at server 2 at 13.109

**Comment by mewrion** [comment]
Ah wait typo, but customer 15 is joining server 1 instead of 2

**Comment by ZChenxin** [comment]
Have you implemented a check whereby the customer would wait at the smaller server ID when the queue lengths are the same? Could be the cause of this problem

**Comment by mewrion** [comment]
Yup I did! Seems like its not the problem too, considering the cust is waiting at server 1 instead of 2

**Comment by yuyanjulia** [comment]
When Customer 15 arrives, Server 1 is resting with two Customers queuing (10 and 13), and Server 2 is serving Customer 12 with Customer 14 waiting. So Server 2 has a shorter queue length of 1, Customer 15 should wait at Server 2.

**Comment by yuyanjulia** [comment]
For the GreedyCustomer, are you checking the number of Customers in the Server instead of queue length? Both servers have two customers inside, maybe your simulator thinks the two queues are the same so it chose the smaller Server no.
But actually Greedy sees Server 2 as the faster one so...

**Comment by mewrion** [comment]
Oh I see! Thank you, managed to fixed it with this!
