### ISSUE TITLE
Simulator: Track Statistics Immutably

### ISSUE THREAD

**Issue by cindyangXQ** [nus-cs2030/2122-s1#276]
# Summary
Can anyone give a hint on how to immutably keep track of the statistics? 

## Description 
My current approach is to write a `Recorder` class and pass it to every relevant `Event`, which involves fields that are not declared final. I know I could wrap those fields to an ArrayList though, to get pass CodeCrunch, but are there any really immutable ways of doing it?

**Comment by wjingen** [comment]
Hi, 

I think you're on the right track. Just return immutable Recorder class after any event is passed in.

For instance, I have a Statistics.java with the constructor `Stats(double waitingTime. int numCustomersServed, numCustomersLeft`.
In the spirit of immutability, let's say if I pass inside a Leave event, then I have a method called `left()` which returns a new Statistics instance, `return new Statistics(this.waitingTime, this.numCustomersServed, this.numCustomersLeft + 1)`

This will enable your declared variables to be both private and final. Hope this answered your question.

**Comment by Hongyi6328** [comment]
I don't collect data until the event queue is empty. Instead, I add every `ServeEvent` to a list and every `WaitEvent`  to another list when they are polled from the event queue. After everything is settled, I calculate the difference of time stamp between each pair of `WaitEvent` and `ServeEvent` associated to the same customer to get the average waiting time. The number of customers served is just the size the the list consisting of `ServeEvent`, and the number of customers who left is the number of customers - this size.

**Comment by satsuma42** [comment]
I also have a dedicated stats class, itself containing a `PriorityQueue` which logs all events. It has a different Comparable<Event> method compared to the 'true' PriorityQueue involved in the simulation. Everything that happens in the 'true' PriorityQueue gets flushed into this when resolved, which gives me control over how whether to include certain things (like a `RestEvent`). Like @Hongyi6328, my duration spent waiting is also 'retroactively' calculated, though the logic itself is done method-side, before a modified WaitEvent is added to to the event logs.

**Comment by cindyangXQ** [comment]
Thank you!
