### ISSUE TITLE
How detailed must the javadocs be?

### ISSUE THREAD

**Issue by ZChenxin** [nus-cs2030/2122-s1#279]
From my understanding of javadocs we will have to specify the parameters and return type (if any) of the constructors and methods. 

If the simulate method is quite long and complicated, do we have to document the logic within the method? Thanks!

**Comment by Hongyi6328** [comment]
I don't think codecrunch checks javadoc. I just submitted a very brief javadoc. I think Prof Henry also mentioned that javadoc is no longer needed.

**Comment by ZChenxin** [comment]
Codecrunch does check for javadocs style if you choose to write javadocs, but good to know it’s not needed

**Comment by joderson** [comment]
> I don't think codecrunch checks javadoc. I just submitted a very brief javadoc. I think Prof Henry also mentioned that javadoc is no longer needed.

So does this mean I don't need to write any javadocs for the whole project? Even for the Simulator class?
