### ISSUE TITLE
Error: cannot find symbol

### ISSUE THREAD

**Issue by Hongyi6328** [nus-cs2030/2122-s1#28]
Hi all,

I was recreating the objects introduced in the first lecture. 
![image](https://user-images.githubusercontent.com/58073006/130205716-35653650-15e1-4e89-a0cd-f33379e0285c.png)

However I encountered this error:
![image](https://user-images.githubusercontent.com/58073006/130205771-9118ff99-7801-4e32-874c-046534c90e42.png)

What is wrong with my codes? Thank you guys!

**Comment by RussellDash332** [comment]
When starting JShell, run `/open Point.java`

**Comment by tlylt** [comment]
Also, you may want to check if your class is written correctly in the first place, i.e. able to compile.
So try running `javac Point.java` to see if there is any issue.

**Comment by Hongyi6328** [comment]
Thank you Russel and tlylt!
