### ISSUE TITLE
Not sure why values are not added into the server instance's list

### ISSUE THREAD

**Issue by PokezardVGC** [nus-cs2030/2122-s1#282]
DGeneral Summary: 
 - Stored the servers as an array
 - passed server instance into a EventGenerator method which will
 - update the server's list of customers to be served by calling add/ remove methods from server
 
problem:
As shown, server is being added when it is passed into event generator however, when the 2nd iteration takes place, the server is currently having no one in the queue?

![image](https://user-images.githubusercontent.com/71965541/142227966-b151180f-72a2-4c92-9f44-df781cf009f8.png)
![image](https://user-images.githubusercontent.com/71965541/142228191-cea42e1b-ae19-4324-bd39-45e509cbe66f.png)
![image](https://user-images.githubusercontent.com/71965541/142228326-1d6cd598-7fa5-4b64-bc74-f89637b73a92.png)

**Comment by yuyanjulia** [comment]
did you update the List of Server with the waiting customers? maybe can try using List.set(int n, Server s)

**Comment by Lokki-ki-ki** [comment]
I met similar issue but is that element added into List disappeared. I solved it by finding an extra break in my code where there is no loop. Maybe you could go through the whole process to see if there are something going wrong cause this.

**Comment by CalebLee** [comment]
I noticed you used sS.checker() to print "Server 1: False", does that mean Server 1 is currently unoccupied? If your Servers have a "current Customer" property or something, you might want to assign Customers there first before filling up the queue, or simply have a queue (List or ArrayList) of Customers where the first Customer in the queue is by default the current Customer.
