### ISSUE TITLE
Which classes are allowed to be mutable?

### ISSUE THREAD

**Issue by Benjamin-Sim** [nus-cs2030/2122-s1#283]
## Description 
For the **Discrete Event Simulator** project, which classes or objects are allowed to be mutable and which are not?

The project specifications doesn't say anything about immutability, so does it mean we can have mutable classes?

**Comment by cliftonfelix** [comment]
I'm not sure about this, but for some of the attributes.. I kinda "cheat".. I put the attributes inside an ArrayList and declare them as private final. So, if I need to change the value, I can just change the value inside the ArrayList

**Comment by yuyanjulia** [comment]
yea but all attributes should still be declared as `private final`, even though they may be "mutable" like List. I mean you can try to upload to codecrunch to see if your mutable classes are allowed.

**Comment by pikawrex** [comment]
As long as the classes are immutable from the client's point of view, i think it should be fine

**Comment by joellow88** [comment]
> yea but all attributes should still be declared as `private final`, even though they may be "mutable" like List. I mean you can try to upload to codecrunch to see if your mutable classes are allowed.

All attributes have to be declared private final if not CodeCrunch won't grade it 
I tried my luck for level 3 and it didn't work

**Comment by CalebLee** [comment]
Like the others have mentioned, there's a private final check on all class properties :')
Personally I used a private final ArrayList<> to circumvent this using .add(), .remove() and .set() on the ArrayList.

**Comment by teominghuang** [comment]
Hi, all properties must be private final! However, there exists a grey area - Arraylist. I use this for properties that change over time, like summing all the waiting time, etc.
