### ISSUE TITLE
How does project code run all 5 levels together?

### ISSUE THREAD

**Issue by Benjamin-Sim** [nus-cs2030/2122-s1#284]
## Description 
For the **Discrete Event Simulator** project, does our final code base need to be able to run all 5 levels together?

I understand that each level has its own `MainN` class and its own `simulate()` method. I know the `simulate()` method is overloaded based on the inputs for each level.

However, the rest of the code remains constant for all 5 levels, so how is it supposed to handle all the different specifications for each level without any changes?

E.g. My code runs level 3 which allows Servers to rest. But how does that same piece of code also run level 1 where there is no concept of rest for Servers?

**Comment by cliftonfelix** [comment]
My Simulator only has 1 constructor and 1 simulate. So, I have some attributes that are not used for lv 1, 2 etc. I just put a dummy value for these attributes.

Same as Russell, I also put the restTimeList to all 0.. this way level 1 can still be using the same simulate as level 3 (and other levels)

**Comment by mewrion** [comment]
For levels 1 - 4, I used dummy values too! Do avoid using null, and if you can't help it, Optionals or really useful in this context
For level 5, it was very similar to original, but I made another Simulator class instead of putting all in 1 class

**Comment by Benjamin-Sim** [comment]
> My Simulator only has 1 constructor and 1 simulate. So, I have some attributes that are not used for lv 1, 2 etc. I just put a dummy value for these attributes.
> 
> Same as Russell, I also put the restTimeList to all 0.. this way level 1 can still be using the same simulate as level 3 (and other levels)

Yeah I also thought of doing that. So what you're saying is that all 5 levels must be able to run together, and the only thing that you can change to make your code work for each level is the `simulate()` method and `MainN`?

**Comment by mewrion** [comment]
You don't have to use one simulate if you don't want to

**Comment by ZChenxin** [comment]
I had different Simulator constructors for the different levels, and also overloaded the simulate methods

**Comment by cliftonfelix** [comment]
> > My Simulator only has 1 constructor and 1 simulate. So, I have some attributes that are not used for lv 1, 2 etc. I just put a dummy value for these attributes.
> > Same as Russell, I also put the restTimeList to all 0.. this way level 1 can still be using the same simulate as level 3 (and other levels)
> 
> Yeah I also thought of doing that. So what you're saying is that all 5 levels must be able to run together, and the only thing that you can change to make your code work for each level is the `simulate()` method and `MainN`?

I agree with @mewrion I won't say it's a must, but that's one of the possible ways because I think all 5 levels behave quite similarly and there is no need to have an overloaded method (just my opinion). My simulate doesnt take any input, so it will just use the attributes in Simulator class + other extra variables.

So, all my Main1-5 are quite similar to Main0 (the example). It will create a Simulator (which takes in around 10 inputs in my case).. then just need to call s.simulate()

**Comment by Benjamin-Sim** [comment]
> > > My Simulator only has 1 constructor and 1 simulate. So, I have some attributes that are not used for lv 1, 2 etc. I just put a dummy value for these attributes.
> > > Same as Russell, I also put the restTimeList to all 0.. this way level 1 can still be using the same simulate as level 3 (and other levels)
> > 
> > 
> > Yeah I also thought of doing that. So what you're saying is that all 5 levels must be able to run together, and the only thing that you can change to make your code work for each level is the `simulate()` method and `MainN`?
> 
> I agree with @mewrion I won't say it's a must, but that's one of the possible ways because I think all 5 levels behave quite similarly and there is no need to have an overloaded method (just my opinion). My simulate doesnt take any input, so it will just use the attributes in Simulator class + other extra variables.
> 
> So, all my Main1-5 are quite similar to Main0 (the example). It will create a Simulator (which takes in around 10 inputs in my case).. then just need to call s.simulate()

So that means you have multiple constructors in `Simulator` to handle the different levels?

**Comment by RussellDash332** [comment]
> > > > My Simulator only has 1 constructor and 1 simulate. So, I have some attributes that are not used for lv 1, 2 etc. I just put a dummy value for these attributes.
> > > > Same as Russell, I also put the restTimeList to all 0.. this way level 1 can still be using the same simulate as level 3 (and other levels)
> > > 
> > > 
> > > Yeah I also thought of doing that. So what you're saying is that all 5 levels must be able to run together, and the only thing that you can change to make your code work for each level is the `simulate()` method and `MainN`?
> > 
> > 
> > I agree with @mewrion I won't say it's a must, but that's one of the possible ways because I think all 5 levels behave quite similarly and there is no need to have an overloaded method (just my opinion). My simulate doesnt take any input, so it will just use the attributes in Simulator class + other extra variables.
> > So, all my Main1-5 are quite similar to Main0 (the example). It will create a Simulator (which takes in around 10 inputs in my case).. then just need to call s.simulate()
> 
> So that means you have multiple constructors in `Simulator` to handle the different levels?

Yes, I did the same as well.

**Comment by joellow88** [comment]
For levels 1 to 4, the higher levels actually build on the earlier ones. My constructor only included a list of customers, and instead of overloading the constructor, I overloaded simulate() instead. So my level 1 calls level 2 with maxQueueLength = 1, level 2 calls level 3 with serveTimes = list of 1s, and so on. Only for level 5 I had to use a different constructor.

**Comment by cliftonfelix** [comment]
> > > > My Simulator only has 1 constructor and 1 simulate. So, I have some attributes that are not used for lv 1, 2 etc. I just put a dummy value for these attributes.
> > > > Same as Russell, I also put the restTimeList to all 0.. this way level 1 can still be using the same simulate as level 3 (and other levels)
> > > 
> > > 
> > > Yeah I also thought of doing that. So what you're saying is that all 5 levels must be able to run together, and the only thing that you can change to make your code work for each level is the `simulate()` method and `MainN`?
> > 
> > 
> > I agree with @mewrion I won't say it's a must, but that's one of the possible ways because I think all 5 levels behave quite similarly and there is no need to have an overloaded method (just my opinion). My simulate doesnt take any input, so it will just use the attributes in Simulator class + other extra variables.
> > So, all my Main1-5 are quite similar to Main0 (the example). It will create a Simulator (which takes in around 10 inputs in my case).. then just need to call s.simulate()
> 
> So that means you have multiple constructors in `Simulator` to handle the different levels?

Um no.. I only have 1 constructor. So lets say for level 5 we have pr, but level 1-4 we dont.. then in Main1 until Main4, I put pr as -1. So I will call the same Simulator constructor in Main1 until Main5.

**Comment by BrendanCheong** [comment]
for `Simulator` I have a boolean attribute that checks if the simulator is at level 5 (Main5 passes an attribute that says level == 5). I pass that boolean check to all the classes that needs the `rng`. If its level 5 is true, then the rest of classes will use `rng` methods. If its false, it will not use the `rng` methods and instead uses the data from Main1 to Main4 (like an array of rest times or an array of customer serve times).

**Comment by brandonrhan** [comment]
actually u can write simulator12345 for Main12345, it is much easier

**Comment by SW-bza** [comment]
Can declare the variables as ArrayList and leave them blank if not needed for certain levels I guess? I overloaded the simulator with extra inputs for each level, instead of updating the constructor of Simulator also.
