### ISSUE TITLE
RandomGenerator constructor is not public in RandomGenerator

### ISSUE THREAD

**Issue by albertsutz** [nus-cs2030/2122-s1#286]
Hi, I am trying to start Level5 but my code breaks when i want to make RandomGenerator object.

![image](https://user-images.githubusercontent.com/64079065/142250100-cf93533c-a382-46ef-90d3-108a27c95630.png)

```
import cs2030.simulator.Simulator;
import cs2030.simulator.RandomGenerator;

class Main5 {
    public static void main(String[] args) {
        Scanner sc = new Scanner(System.in);
        int seed = sc.nextInt();
        int numOfServer = sc.nextInt();
        int numOfSelfCheckOut = sc.nextInt();
        int numOfQueue = sc.nextInt();
        int numOfCustomer = sc.nextInt();
        double lambda = sc.nextDouble();
        double mu = sc.nextDouble();
        double rho = sc.nextDouble();
        double pr = sc.nextDouble();
        double pg = sc.nextDouble();
        RandomGenerator rng = new RandomGenerator​(seed, lambda, mu, rho);
    }
}
```

Is there anything wrong with it?

**Comment by RussellDash332** [comment]
RandomGenerator should only be used inside Simulator.java. So, you can think of a way to use the rng only inside the simulator since the RNG.class file should also be stored in the same directory as Simulator.java

**Comment by ZChenxin** [comment]
Import and use the random generator class within Simulator.java instead. You are trying to access the random generator outside of the folder it exists in when you package it as the Main classes are not packaged, which is why you have this error.

**Comment by albertsutz** [comment]
OH, thank you very much for the answer!

I was trying to generate all the arrival times in the main5.java :D
