### ISSUE TITLE
How does :: (method reference) replace lambda expressions

### ISSUE THREAD

**Issue by Twars2** [nus-cs2030/2122-s1#287]
I know method references are not allowed on codecrunch but how do they work?

The thing I am most confused about is how does method reference knows which parameters are being input into the method if there is no mention of them at all. One example from the java docs tutorial found [here ](https://docs.oracle.com/javase/tutorial/java/javaOO/methodreferences.html)is  : 
`Arrays.sort(rosterAsArray,
    (a, b) -> Person.compareByAge(a, b)
);`
vs
`Arrays.sort(rosterAsArray, Person::compareByAge);`

In the second example, both a and b are not specified but the array can still sort 2 different people. 

Another question is if all lambda expressions can be replaced by method references?

**Comment by huzaifa1712** [comment]
This StackOverflow post gives a lot of detail about what's going on: https://stackoverflow.com/questions/29244357/lambda-expression-vs-method-reference-implementation-details

I don't really get it too well either, but I think the essence is that when you have a lambda expression it gets converted internally into another instance method with matching arguments and return type and this is checked against what the argument should actually be. In this case, Array.sort is supposed to take in a Comparator<? super T>, and Comparator is a Functional Interface so the compiler knows what form the Function passed in should take i.e should look like Comparator<T>.compare with (T o1, T o2) -> int. 

With method references this conversion doesn't have to be converted internally.

**Comment by jackhocheukhei** [comment]
https://stackoverflow.com/questions/25606906/sonar-replace-this-lambda-with-a-method-reference

Can check this out too, a method reference replace a single method invocation, so it can’t simply replace a lambda expression consisting of more than one method invocation.
