### ISSUE TITLE
(Nvm, misinterpreted the Qn ._.) Project 3-2, wrong test case for 10th customer??

### ISSUE THREAD

**Issue by DerenC** [nus-cs2030/2122-s1#289]
# Summary
For Project Level 3-2, is it just me, or the given output serving time for the 10th customer is wrong?

## Description 
The max queue length is 2 customers. 

Given respective rest time for 7th - 10th service:
(7) 0
(8) 3.863139
(9) 0
(10) 0

Given outputs:
 - 9.006 7 serves by server 1
 - 9.105 9 waits at server 1
 - 9.160 10 arrives
 - 9.160 10 waits at server 1
 - 10.484 7 done serving by server 1
 - 10.484 9 serves by server 1
 - 10.781 9 done serving by server 1
 - 14.644 10 serves by server 1

Given that the 9th service has a '0' rest time, shouldn't Server 1 serve the 10th customer immediately at 10.781, after done serving the 9th customer????

## Screenshots: 
Given inputs:
![Given inputs](https://user-images.githubusercontent.com/65486901/142379710-3f5fe429-6cbe-42d8-bf7f-de1417ee07e5.JPG)
Given outputs:
![Given outputs](https://user-images.githubusercontent.com/65486901/142379725-4087cdce-a2b0-4d21-9598-85577ad11c95.JPG)
My outputs:
![My output](https://user-images.githubusercontent.com/65486901/142379741-42ccfe36-6e53-49c0-9131-296198f2819c.JPG)

**Comment by clarence-chew** [comment]
There is no respective rest time.

**Comment by DerenC** [comment]
New inputs:
![New inputs](https://user-images.githubusercontent.com/65486901/142382636-fe55a045-00c8-442f-855e-baa542462174.JPG)
New outputs which tally with the given outputs:
![Tallied outputs of the new inputs](https://user-images.githubusercontent.com/65486901/142382641-b6e46a7d-3cab-4b7c-b7eb-195db8fbbe89.JPG)

**Comment by DerenC** [comment]
> > Given respective rest time for 7th - 10th service:
> 
> There is no respective rest time, a rest time is read at the time the server rests.

Alrite i get it. Thanks :)
