### ISSUE TITLE
Trouble installing Vim

### ISSUE THREAD

**Issue by ketamethane** [nus-cs2030/2122-s1#29]
# Summary

## Description 
1. I followed the steps to install Vim locally (Windows) but Vim does not appear to be installed in the command prompt.
2. Additionally, I tried creating a "hello.txt" file via Vim on Ubuntu but I faced a "PERMISSION DENIED".
3. When I tried to go into insert mode on vim, I faced a warning as shown.
Edit: for context I added what exe.file I installed

## Screenshots (if any): 
1.
![Capture vim command prompt](https://user-images.githubusercontent.com/88729540/130363423-0d744002-48bc-4df2-ae2f-6becc8fdcfdd.PNG)

2.
![Capture hello](https://user-images.githubusercontent.com/88729540/130363485-5666682a-2968-4ae7-b013-54a8b7f5d0e9.PNG)

3.
![Capture vim](https://user-images.githubusercontent.com/88729540/130363436-4146c23f-f2a5-4365-9ef9-cfd902e19dcd.PNG)

4.
![Capture ss](https://user-images.githubusercontent.com/88729540/130364246-03930d9a-91c4-40d5-805c-9b7d24adc8cf.PNG)

**Comment by kiwizop** [comment]
Hi ketamethane, could type `vim -version` on ubuntu instead.  In ubuntu, can try `sudo chmod 777 /methane/root` to give access to read and write files in the directory. Do check if the path is correct using the command `pwd`.  
Reference: [https://unix.stackexchange.com/questions/119358/create-file-in-folder-permission-denied](url)

**Comment by ketamethane** [comment]
Hi kiwizop! I did what you suggested, and the following showed the results.
I also want to add I didn't face any permission denied when I opened vim using sudo.
Also, that reference leads to an empty issue (which I think was deleted?)

![Capture](https://user-images.githubusercontent.com/88729540/130476247-54b8b3ea-4f33-442d-8a3c-698918cd371c.PNG)

**Comment by RussellDash332** [comment]
Is this because you're working on the root directory and not the home directory?

**Comment by RicharCd** [comment]
Hi, if you want to have vim on cmd, it has to be a parameter in PATH on Windows.

Inside `Edit the System Environment variables` typed in the search bar, press the best match.
When the window appears, click Environment Variables. Now there is a top and bottom selection, scroll down into the bottom selection and double click the system variable called `Path`. Now there is a list, press new and copy where `vim.exe` was installed on your Windows computer. By default it should be
```
C:\Program Files (x86)\Vim\vim82
```
Then press OK on all windows to close everything and restart the cmd (close and reopen).
You should be able to type vim and open the vim editor through cmd now.

**Comment by ketamethane** [comment]
Thanks, kiwizop, RussellDash332 and RicharCD! I managed to set vim as a parameter in PATH on Windows, and managed to open vim on the home directory! (totally forgot that was necessary!)
My apologies for the numerous posts. I tend to get lost installing applications >_<

![Capture](https://user-images.githubusercontent.com/88729540/130499425-6a5ec30f-af37-4315-a7ae-f94c39c5ed46.PNG)

**Comment by RussellDash332** [comment]
Glad it's resolved! 😄
