### ISSUE TITLE
How to Replace 'Null' with 'Optional.empty()' ?

### ISSUE THREAD

**Issue by yueyin22** [nus-cs2030/2122-s1#294]
I am not using Optional in any of my codes but since i can't use null, how should i use Optional.empty()?

My codes are as attached - which is flagged out on codecrunch:
```
error: incompatible types: no instance(s) of type variable(s) T exist so that Optional<T> conforms to Event
        return Optional.empty();
```

```
@Override
    public Event nextEvent(Server[] servers, ArrayList<Double> restTimes) {
        return Optional.empty(); //null
    }
```

**Comment by guowei42** [comment]
Since your method returns Optional.empty() which is type Optional, your method return type should be Optional<Event> instead.

**Comment by yueyin22** [comment]
> Since your method returns Optional.empty() which is type Optional, your method return type should be Optional instead.

As in the original code is supposed to be `return null;`, I just tested using Optional.empty() which failed. So if I were to return Optional< Event > , do I have to do it for all my classes that has the Event method? So I got to change everything to work according with Optional ?

**Comment by Elyxpenguin** [comment]
> As in the original code is supposed to be `return null;`, I just tested using Optional.empty() which failed. So if I were to return Optional< Event > , do I have to do it for all my classes that has the Event method? So I got to change everything to work according with Optional ?

Optional.empty() returns an empty optional but your return type is Event hence the error. If you want to use optional then you have to change your return type to Optional<Event> and yes you have to change the return type for all classes that have this nextEvent method since you are overriding the method.

**Comment by yueyin22** [comment]
> > As in the original code is supposed to be `return null;`, I just tested using Optional.empty() which failed. So if I were to return Optional< Event > , do I have to do it for all my classes that has the Event method? So I got to change everything to work according with Optional ?
> 
> Optional.empty() returns an empty optional but your return type is Event hence the error. If you want to use optional then you have to change your return type to Optional< Event > and yes you have to change the return type for all classes that have this nextEvent method since you are overriding the method.

Got it, thanks!
