### ISSUE TITLE
Cannot find RandomGenerator.class in Simulator.java

### ISSUE THREAD

**Issue by optionalemon** [nus-cs2030/2122-s1#297]
## Description 
<img width="239" alt="Screenshot 2021-11-18 at 22 23 17" src="https://user-images.githubusercontent.com/86706511/142433280-c5454759-8b05-4bc8-8751-566350896a49.png">
This is how my directory looks like currently (don't mind my messy Simulators, anyway Simulator5 is used for level 5).

I can't seem to find the RandomGenerator class in my Simulator5 when i initiate a new RandomGenerator, the error below appears
<img width="513" alt="Screenshot 2021-11-18 at 22 22 50" src="https://user-images.githubusercontent.com/86706511/142433201-c96150cf-3a70-48ad-8023-476e380e657b.png">

Any advice will be helpful :(

**Comment by CalebLee** [comment]
Hmm I'm not too sure but I created a RandomGenerator.java file and compiled it to create the RandomGenerator.class, rather than just downloading RandomGenerator.class to the directory. You might also want to try placing your Simulator5 code into Simulator1/3.java and seeing if it is able to find RandomGenerator?

**Comment by optionalemon** [comment]
> Hmm I'm not too sure but I created a RandomGenerator.java file and compiled it to create the RandomGenerator.class, rather than just downloading RandomGenerator.class to the directory. You might also want to try placing your Simulator5 code into Simulator1/3.java and seeing if it is able to find RandomGenerator?

Ah ok, found the RandomGenerator.java file shared @BrendanCheong just now, that works! Thank you!
