### ISSUE TITLE
Issue setting up Checkstyle

### ISSUE THREAD

**Issue by prizojuice** [nus-cs2030/2122-s1#3]
When trying to run the checkstyle command: java -jar ./checkstyle-8.2-all.jar -c ./cs2030_checks.xml *.java 
I get this message on Ubuntu: 
**Files to process must be specified, found 0.**

How can I fix this? Thank you for your help!

**Comment by hwkchia** [comment]
If you manage to resolve your own issue, it's best to leave it intact and also respond to it as to how it was solved.  It will be to the benefit of other students.   Don't need to be shy... 😄
