### ISSUE TITLE
Help with Level 5, method Logger<Integer> f(int n)

### ISSUE THREAD

**Issue by aanghs22** [nus-cs2030/2122-s1#300]
# Summary

The output after running Logger<Integer> f(int n) is opposite to what's needed.

## Description:

I'm unsure of how to implement the method Logger<Integer> f(int n) although I know what it's just recursion and supposed to be very similar to the code snippet they provided in the level 5 brief.

## Code Snippets
` Logger<Integer> f(int n) {
     if (n == 1) {
         return new Logger<Integer>(() -> 1);
     } else if (n % 2 == 0) {
         return f(n / 2).map(x -> 2 * x);
     } else {
         return f(3 * n + 1).map(x -> (x - 1) / 3);
     }
 }`

## Screenshots
<img width="138" alt="Screenshot 2021-11-19 at 1 23 55 PM" src="https://user-images.githubusercontent.com/63781664/142569798-f3f662f8-1f12-4624-8b4e-ced0acf82d82.png">

**Comment by yuyanjulia** [comment]
#150 can refer to this post for some ideas

**Comment by aanghs22** [comment]
thanks so much! didn't scroll back far enough :")
