### ISSUE TITLE
2 Final Exam zoom links

### ISSUE THREAD

**Issue by kxshxsh** [nus-cs2030/2122-s1#301]
![image](https://user-images.githubusercontent.com/92561253/142574449-5ece14cf-2e51-4798-897e-a6b5e2c8f672.png)

Went to conferencing to see that I have 2 separate zoom meetings created for the same date and time. Does anyone else have this issue too?

**Comment by jeromepui** [comment]
Hi, I have the exact same two as you too.

**Comment by Mehvin** [comment]
I think we are able to view all the exam groups but to find which exam group you are under go to
class & groups > class groups.
The group which you are in should be clickable to view the people in the group.

**Comment by upabove122** [comment]
Oh no... i see no links help D:

**Comment by bingsen0806** [comment]
I also see no link? Is that an issue?

**Comment by kxshxsh** [comment]
No, my TA says that prof is looking into why we're seeing multiple links. Maybe thats why they were all removed:)

**Comment by yuyanjulia** [comment]
I think the problem has been solved? I have only one link now!

**Comment by SW-bza** [comment]
I also only see 1 zoom link now!

**Comment by kxshxsh** [comment]
I see none now:/

**Comment by RussellDash332** [comment]
This should be resolved closer to date. Just let the Prof or TAs know if there's some discrepancy!
