### ISSUE TITLE
Lv4 Self checkout

### ISSUE THREAD

**Issue by PokezardVGC** [nus-cs2030/2122-s1#302]
Having problems thinking of a solution to Lv4. How do we keep track of which customers go to which self-checkout counter when he/she has to wait? Was thinking of having an array to store the mostAvailableTiming for each self-checkout counter then, create a wait event, attaching the customer to the self-CheckOut counter with the earliest mostAvailableTImings

**Comment by Twars2** [comment]
Personally, I created a new class called SelfCheckoutList that only creates one instance in the Simulator code. The new class is basically just the waitlist for servers but shared among all the self-checkout and each time a customer waits for a self-checkout this new Class changes and adds a new person to the waitlist. However, I think how u create your SelfCheck out depends on your initial implementation. Also, I think you can create a static waitList that is shared among all SelfCheckouts.

**Comment by CalebLee** [comment]
I stored the Customers queuing for self-checkout in a common queue (ArrayList) managed by a “Shop”, which also manages all the Servers.

If customers have to wait, then the Done Event needs to trigger the next Serves event somehow (although if Done directly creates Serves this leads to a cyclic dependency). So I used Simulator to identify Done Events and manually create the next ServesByEvent, using the same self-checkout counter which is now available and popping the next Customer in the common self-checkout queue (ArrayList).

**Comment by nmtuan2001** [comment]
I created an interface (abstract class should also work) called Server, then 2 classes, HumanServer and SelfCounter. SelfCounter is almost the same but the waiting queue is static.

`private static final Queue<Customer> waiting = new LinkedList<>();`

Then, the constructor will not make a new waiting queue and every SelfCounter will update this same static queue.

**Comment by kxshxsh** [comment]
My approach was slightly different- I basically have the same event flow for all customers regardless of whether they are being served by a human server or a self-checkout machine. For me, every self-checkout (SCO) machine had its own queue(just for ease of implementation and uniformity) but if a server had to wait, I would always queue them in the queue of the first SCO machine and thus always have the same log output for anyone waiting for a SCO. Then when it finally came to serving the customer, I allocated the best SCO to them at that moment. Essentially you delay allocating a SCO until as long as possible.

**Comment by PokezardVGC** [comment]
Currently having some problems, using the static waiting list approach. 
Simulation:
Human example: (curr implementation)
A in queue, B joins queue. B will have to wait A's service time, gen Wait event. adding A's service time

SCO: 
A in queue, B join queue. However, A may proceed to SCO 3 while B go SCO4. Any suggestions for this?

**Comment by CalebLee** [comment]
A and B can be in the same queue, but the allocation to SCO need not occur upon arrival. It should simply create a Wait Event and allocate to the first SCO. Then, when a Done Event is polled from the PriorityQueue, check the common SCO queue, pop the next Customer from the queue, and add a Serves Event.

However, there may be some cases where you want the Customers to proceed to the SCO directly, in which case they should be allocated to the SCO upon arrival. What I did here was run an .allocateServer() function in the Arrival Event and then run a .allocateSelfCheckout (only searches through self-checkouts) again later on if the Customers are queuing for a self-checkout counter.

**Comment by Eclipse-Dominator** [comment]
My server has an internal queue to handle customer queues. So for self-checkout, I made a new constructor in my server to take in a queue instead of creating one in the constructor. Then for self-checkout, I just extended server and pass in a queue that is defined outside. So every instance of self-checkout will only reference 1 queue.

**Comment by kxshxsh** [comment]
> Currently having some problems, using the static waiting list approach. Simulation: Human example: (curr implementation) A in queue, B joins queue. B will have to wait A's service time, gen Wait event. adding A's service time
> 
> SCO: A in queue, B join queue. However, A may proceed to SCO 3 while B go SCO4. Any suggestions for this?

Yes, the way to calculate wait time is still the same but when A is done serving and its B's chance to now be served, create an implementation to allocate to it the best SCO in that situation:) and then proceed normally

**Comment by PokezardVGC** [comment]
Thanks for all your help people hope this thread also helps others with this level!!
