### ISSUE TITLE
Are non-final attributes allowed in the project? 

### ISSUE THREAD

**Issue by haoyusimon** [nus-cs2030/2122-s1#303]
For our project, will the CodeCrunch check if all the attributes of a class are declared as private final? I am planning to do so but not sure if the code can pass the CodeCrunch...

**Comment by RussellDash332** [comment]
Try your best to make all attributes private final. If you need a non-final attribute, you can make it look like final by wrapping it in an array list.

E.g. you have an int attribute initiated with 0 and then you want to increment by 1 when something happens. Obviously you can't just do this.attribute += 1, but if you wrap it into a list or an array, it is allowed (somehow, but take note this may be a bad practice), so from [0] to [1] and so on.

**Comment by haoyusimon** [comment]
Ohhh I see! I'll try to think about ways that don't need non-final attributes first. If really cannot I guess I'll use the trick you suggested. Thanks!
