### ISSUE TITLE
Run time Error for Simulator Project hidden testcases

### ISSUE THREAD

**Issue by xzzz3** [nus-cs2030/2122-s1#304]
# Summary
Facing run time error without error messages in Code Crunch for discrete event simulator project.

## Description 
Hello! I have been debugging my code pretty smoothly with the codecrunch test cases despite them being hidden, but today I got to a new hidden test case (test case 5_16) and it gave me a run time error (without telling me what it is, like the screenshot below)... Usually if it is an exception, it will be in the form of "Incorrect Output" and the error message will be shown (in the other sc below). Does anyone know how I should go about solving this? Thank you!!

## Screenshots (if any): 
current problem:
![image](https://user-images.githubusercontent.com/88388128/142618692-4aea0a79-ad47-45cf-bc3f-b7bc7c5e2bdb.png)

usual exceptions: 
![image](https://user-images.githubusercontent.com/88388128/142618732-bb5fbb26-0617-49d5-9490-7d0d2363a1f6.png)

**Comment by xzzz3** [comment]
i think i found the problem! 

used the 5_16 answer file in another issue and it says I have 5000 lines of incorrect output (i dont even know how that's possible) but that may have been the cause (maybe an overflow or smth)...

**Comment by ikaajj** [comment]
I'm not sure what's the issue, but this is the input for testcase 5_16: 2 3 2 10 1000 7.0 1.0 1.0 1.0 0.5 . Hope it helps!

**Comment by xzzz3** [comment]
> I'm not sure what's the issue, but this is the input for testcase 5_16: 2 3 2 10 1000 7.0 1.0 1.0 1.0 0.5 . Hope it helps!

thank you so much! that helps my debugging a lot :o)
