### ISSUE TITLE
Scanning inputs for level 3

### ISSUE THREAD

**Issue by tammehh** [nus-cs2030/2122-s1#307]
# Summary
Clown doing project last minute

## Description 
Getting a NoSuchElementException while trying to scan the Doubles for the server breaktimings?

## Screenshots (if any): 
<img width="273" alt="image" src="https://user-images.githubusercontent.com/85746894/142664237-59f02ab0-c9f7-4cf8-82ee-75b59bc4af39.png">
<img width="427" alt="image" src="https://user-images.githubusercontent.com/85746894/142664265-d4aafece-0ab4-4e9b-9dbd-abd21000cb59.png">
Tried filtering out the '0's with the if statement, but it didn't seem to work. Error seems to be coming from the sc.nextDouble()?

**Comment by Eclipse-Dominator** [comment]
I dont think you need to check for whether there is a next "0"?

**Comment by tammehh** [comment]
oh my, the `j` solved it, THANKS!

**Comment by CalebLee** [comment]
You shouldn't check if there is a next "0", scan it into the list of rest times first. When the Server finishes serving, then pop the rest duration from the list of rest times. This is how you will need to implement it for later levels - the Server only knows how long they will rest when they they rest.
