### ISSUE TITLE
cyclic dependency between simulator and arrive event

### ISSUE THREAD

**Issue by TsangZiXuan** [nus-cs2030/2122-s1#308]
![Screenshot (73)](https://user-images.githubusercontent.com/89310073/142714259-4965ed64-2a70-4af4-a1cf-0becaf2ddac0.png)

Hello! Has anyone else encountered a cyclic dependency issue like this? Mine appears to be Arrive -> Event -> Simulator -> Event or Arrive -> Simulator -> Arrive if i am interpreting this correctly. But i don't really know how to work around this since my simulator creates arrive events and i have an abstract class Event that has a runEvent method that takes in a simulator. 
Any help is appreciated! Thank you :)

**Comment by cadencjk** [comment]
May I ask what your Event.java does? My Event.java is just a abstract class for Serve/Arrival/etc events to inherit from. My simulator does not create any Event, only Arrival events. In my opinion, there is no need for events to take in Simulator as the events only need to take in specific arguments such as Customer and (double) time in, the events do not need to know anything else from the Simulator class.

**Comment by TsangZiXuan** [comment]
> May I ask what your Event.java does? My Event.java is just a abstract class for Serve/Arrival/etc events to inherit from. My simulator does not create any Event, only Arrival events. In my opinion, there is no need for events to take in Simulator as the events only need to take in specific arguments such as Customer and (double) time in, the events do not need to know anything else from the Simulator class.

I took in the simulator for my runEvent method to update the different statistics! like for arrive i have to reference the list of servers that's in my simulator to decide if arrive will lead to wait leave or serve.

**Comment by cadencjk** [comment]
> > May I ask what your Event.java does? My Event.java is just a abstract class for Serve/Arrival/etc events to inherit from. My simulator does not create any Event, only Arrival events. In my opinion, there is no need for events to take in Simulator as the events only need to take in specific arguments such as Customer and (double) time in, the events do not need to know anything else from the Simulator class.
> 
> I took in the simulator for my runEvent method to update the different statistics! like for arrive i have to reference the list of servers that's in my simulator to decide if arrive will lead to wait leave or serve.

Oh, how about passing the list of servers directly to your events to call the next event, instead of passing in the whole simulator? For keeping track of statistics, I created another Statistics.java for the purpose. I think these will eliminate the cyclic problem.

**Comment by Xinyi-Steph** [comment]
You probably wouldn't want to have the method `runEvent` inside your `Event` class. Think of it this way – when you want to update the statistics, whose job is that? Is that part of the event's jobs, or is that the _responsibility_ of the simulator? If you assign some of the simulator's jobs to the event class, then the classes are sharing responsibilities. That would be a violation of the single responsibility principle.

Usually, circular dependency signals tight coupling, which is often bad in software design. That is because a change in one implies changes in many other classes that are coupled to the class. Decoupling will help.

**Comment by TsangZiXuan** [comment]
> You probably wouldn't want to have the method `runEvent` inside your `Event` class. Think of it this way – whose job is it to run some event and update the statistics? Is that part of the event's jobs, or is that the _responsibility_ of the simulator? If you assign some of the simulator's jobs to the event class, then the classes are sharing responsibilities. That would be a violation of the single responsibility principle.
> 
> Usually, circular dependency signals tight coupling, which is often bad in software design. One of the reasons is that a change in one implies changes in many other classes that are coupled to the class. In my opinion, events, as building bricks of the simulator, do not really need to depend on the simulator class. Rather, the simulator should be dependent on the events. So, _decoupling_ them will help.



> > > May I ask what your Event.java does? My Event.java is just a abstract class for Serve/Arrival/etc events to inherit from. My simulator does not create any Event, only Arrival events. In my opinion, there is no need for events to take in Simulator as the events only need to take in specific arguments such as Customer and (double) time in, the events do not need to know anything else from the Simulator class.
> > 
> > 
> > I took in the simulator for my runEvent method to update the different statistics! like for arrive i have to reference the list of servers that's in my simulator to decide if arrive will lead to wait leave or serve.
> 
> Oh, how about passing the list of servers directly to your events to call the next event, instead of passing in the whole simulator? For keeping track of statistics, I created another Statistics.java for the purpose. I think these will eliminate the cyclic problem.


Thanks so much for the insights guys! I manage to resolve it! :D
