### ISSUE TITLE
Query on how to keep track of history in the arraylist for Lab8

### ISSUE THREAD

**Issue by ruyian** [nus-cs2030/2122-s1#309]
# Summary

I am having an issue with the flatMap() method of Logger. I am not sure of the way for us to keep track of the history in the ArrayList of Logger Object.

## Description:

Clarifications or details with respect to the issue you are facing
I am not sure of how to keep track of history in the array list of Logger Object using flatMap(). I have already removed the first output(if there is any) but i still does not work.

## Code Snippets

Attach code snippets (if any)
![image](https://user-images.githubusercontent.com/78540645/142720528-0efa2fc1-34e8-4733-aa18-786aada44dae.png)

And this is my current implementation:
![image](https://user-images.githubusercontent.com/78540645/142720560-763d4209-12f5-428f-ab27-56f5767f08bd.png)
With or without the commented line of adding the history, its not going to generate the correct result.
(Less content without the commented line, but much more content in the history with the commented line)

## Screenshots

Screenshots (if any)

Thank you!
Your help will be greatly appreciated!

**Comment by nmtuan2001** [comment]
I think the problem is that your current implementation of Logger (and map/flatMap) isn't lazy. I'm not sure if others are able to implement flatMap to evaluate eagerly, but personally I used Supplier for x and only call .get() in Logger's toString method. 
``` java
class Logger<T> {
    private final Supplier<T> supplier;
    private final List<...> history;  // you can decide how you want to implement history

     /* constructor */

    public T get() {
        return supplier.get();
    }

    @Override
    public String toString() {
        // only call .get() here (you can call it in map/flatMap but inside a supplier)
    }
}
```
For more details, you can check the discussions in other Lab 08 posts or Lecture 9 (there is a section for map method).

**Comment by UnwilledTangent** [comment]
Thanks @nmtuan2001 . You gave me an idea on how to code out my last level. I was stuck at it for quite some time!

**Comment by nmtuan2001** [comment]
No problem @UnwilledTangent . Happy to help!
