### ISSUE TITLE
Has ForkJoinPool Java Framework (in Java 7) been removed from the syllabus?

### ISSUE THREAD

**Issue by cheeheng** [nus-cs2030/2122-s1#312]
I tried the AY17/18 Semester 1 and AY18/19 Semester 1 Past Year paper. Both tested on ForkJoinPool, which wasn't covered in this semesters' lectures. 

I would like to confirm whether CompletableFuture will be tested this semester in place of ForkJoinPool?

**Comment by RussellDash332** [comment]
ForkJoinPool is not covered? Isn't that the lecture drama?

**Comment by cheeheng** [comment]
Lecture 11?

**Comment by cheeheng** [comment]
Lecture drama? Which one? I couldn't find any mention of the Java ForkJoinPool framework in the asynchronous programming lecture.

**Comment by upabove122** [comment]
@RussellDash332 The one where we can't seem to get the right worker to do the job? XD

**Comment by cheeheng** [comment]
Oh. That was towards the end of the lecture, but I don't think we covered RecursiveAction and RecursiveTask<T> that was tested in past year papers because it was superseded by CompletableFuture? Please confirm.

**Comment by wjingen** [comment]
Anyone has any updates regarding this question? Encountered the same question doing PYPs.
