### ISSUE TITLE
Peek() without Optional:: ifPresent

### ISSUE THREAD

**Issue by kxshxsh** [nus-cs2030/2122-s1#313]
How does one implement peek() without using Optional.ifPresent? 
Initially, I just printed my get() Optional value but when I read the description for level 3, I realised that if the Optional is empty, we shouldn't print anything. 

Alternatively, if I had to do orElse() what action would I carry out?

Maybe this is a stupid question but help me out coz the stress is making me lose my mind:") Thanks<3

**Comment by cadencjk** [comment]
Optional.isPresent() is not allowed but Optional.ifPresent() is. I used a code that looks like this `optional.ifPresent(x -> {System.out.println(x)}); ` Hope I answered your question.

**Comment by kxshxsh** [comment]
Omg small details, that helps so much!! Thank you!!
