### ISSUE TITLE
Variable Capture Question

### ISSUE THREAD

**Issue by e0559198** [nus-cs2030/2122-s1#318]
Based on our understanding of variable capture, local variables have to be effectively final in order to be used in lambda expressions. Can someone explain the rationale behind this? Thanks

**Comment by mewrion** [comment]
Local variables are stored in the stack. In lambda expressions, Java has to make a deep copy of x so it can live outside of its scoped method. When you modify the local variable in the same scoped method after creating the lambda, you're not actually changing the local variable referenced in the lambda, although you expect that to be the case

To keep it simple, Java compiler requires local variables to be effectively final to avoid any misunderstandings, and it is impertinent to note that Java needs the lambda to have access to the latest value of y
