### ISSUE TITLE
What kind of output is expected in codecrunch?

### ISSUE THREAD

**Issue by ChrisHo1341** [nus-cs2030/2122-s1#324]
Hi guys, I've been doing the project so far with just typing out the test cases within ubuntu and did not upload into codecrunch at all.
Now that I am almost done, I decided to upload to codecrunch, but according to codecrunch i do not have any output at all.
I am outputting everything using System.out.println

The following are my output in ubuntu followed by whats happening in codecrunch

![outputs2](https://user-images.githubusercontent.com/79920944/142760579-8a360a71-9e6c-4ef3-8b47-7ba3fe346874.PNG)
![outputs](https://user-images.githubusercontent.com/79920944/142760584-a3865532-a96d-4f4b-a201-7fed3b8f7428.PNG)

Any help is greatly appreciated!

**Comment by hewliyang** [comment]
Have you packaged your java files as instructed?

**Comment by cadencjk** [comment]
Hmm that is weird, I believe System.out.println() is correct. Does your code require any input from the user to end stdin (eg press Ctrl + D to start the simulation) ?

**Comment by ChrisHo1341** [comment]
> Have you packaged your java files correctly?

I started every file with package cs2030.simulator;

Am i supposed to include all 5 main1-5.java?




> Hmm that is weird, I believe System.out.println() is correct. Does your code require any input from the user to end stdin (eg press Ctrl + D to start the simulation) ?

nope not at all! just your usual scanner class!

**Comment by hewliyang** [comment]
> > Have you packaged your java files correctly?
> 
> I started every file with package cs2030.simulator;
> 
> Am i supposed to include all 5 main1-5.java?
> 
> > Hmm that is weird, I believe System.out.println() is correct. Does your code require any input from the user to end stdin (eg press Ctrl + D to start the simulation) ?
> 
> nope not at all! just your usual scanner class!

Yes you need to include all your Main files

**Comment by ChrisHo1341** [comment]
> 

So i need to make all my main files compatible with the my final version of simulator?

**Comment by Irminrics** [comment]
Yes. You are required to submit all your files including the Main1-5 files which will be compatible with your final version of simulator so that it will work for all levels. All your files should start with package cs2030.simulator except your main files which would be in the default package.

You can compile using javac -d . *java and check the folders where your files are saved to make sure that the Java files are compiled in their correct packages.

**Comment by ChrisHo1341** [comment]
Got it! thank you so much everyone!
