### ISSUE TITLE
EmptyList constructor without using null

### ISSUE THREAD

**Issue by kxshxsh** [nus-cs2030/2122-s1#329]
# Summary
How did y'all construct an EmptyList without null values being allowed?

## Description 
My EmptyList extends InfiniteListImpl so I created an InfiniteListImpl constructor as shown below. But every time I submit, I'm hit with 'null values detected'. How did y'all work around this? 

Also, does using `Lazy.ofNullable(...)`  trigger the null value error in the grader too?

## Screenshots (if any): 
![image](https://user-images.githubusercontent.com/92561253/142793462-a5b95dd8-b4b0-4cba-b3fd-cdbde107e753.png)

Thanks!!

**Comment by SolarPanda1** [comment]
My EmptyList does not have any fields. It just returns itself for intermediate operations

**Comment by Irminrics** [comment]
You do not need any attributes for the EmptyList class so there is no need for a constructor for it as well

**Comment by kxshxsh** [comment]
hmm so my InfiniteListImpl has 1 constructor with the head and tail as arguments. If I choose to not have a constructor for EmptyList I get an error:
![image](https://user-images.githubusercontent.com/92561253/142797749-d9bbab7b-9435-46df-855f-bb61f86a3adb.png)

did y'all extend your EmptyList from InfiniteListImpl<T> too? or did y'all just make EmptyList implement InfiniteList<T>?

**Comment by Irminrics** [comment]
EmptyList should implement from InfiniteList instead of InfiniteListImpl because you only need the abstract classes that define the EmptyList methods and not the attributes from the InfiniteListImpl if that make sense.

**Comment by kxshxsh** [comment]
oh that does make sense! Thanks:))
