### ISSUE TITLE
Checkstyle for *.jsh files

### ISSUE THREAD

**Issue by lhy-hoyin** [nus-cs2030/2122-s1#33]
Do we have to ensure that our *.jsh files conform to the styling requirements when submitting to CodeCrunch?

**Comment by Polygonalr** [comment]
I personally didn't do so (seems like there's no need to), but you can always throw the code of your 2 functions into a Java class to use `checkstyle` on. I still think it is good practice to conform to the coding style just to get used to it.

**Comment by RussellDash332** [comment]
Better be 😄 no loss on doing that.
If you try to edit the .jsh files directly, e.g. `vim blabla.jsh`, you can see that it's just a bunch of Java codes crunched into a single file, so running checkstyle on it will also do the work.

**Comment by Polygonalr** [comment]
> so running checkstyle on it will also do the work.

@RussellDash332 Didn't really work out for me, running `checkstyle` directly on on the jsh (i.e. `./checkstyle-8.2-all.jar -c cs2030_checks.xml maxDiscCoverage.jsh` always shows "Audit done" without any errors even if there's styling errors within the file. Changing the extension to `.java` makes `checkstyle` not work at all. Personally I had to throw the code to a Java class for `checkstyle` to work. Maybe you have a different configuration?

**Comment by RussellDash332** [comment]
> > so running checkstyle on it will also do the work.
> 
> @RussellDash332 Didn't really work out for me, running `checkstyle` directly on on the jsh (i.e. `java -jar ./checkstyle-8.2-all.jar -c cs2030_checks.xml maxDiscCoverage.jsh` always shows "Audit done" without any errors even if there's styling errors within the file. Changing the extension to `.java` makes `checkstyle` not work at all. Personally I had to throw the code to a Java class for `checkstyle` to work. Maybe you have a different configuration?

Oh it will pass even with styling errors? I guess your method is the way for now 😆 
New food for thought

**Comment by lhy-hoyin** [comment]
> > so running checkstyle on it will also do the work.
> 
> @RussellDash332 Didn't really work out for me, running `checkstyle` directly on on the jsh (i.e. `java -jar ./checkstyle-8.2-all.jar -c cs2030_checks.xml maxDiscCoverage.jsh` always shows "Audit done" without any errors even if there's styling errors within the file. Changing the extension to `.java` makes `checkstyle` not work at all. Personally I had to throw the code to a Java class for `checkstyle` to work. Maybe you have a different configuration?

If you typed `checkstyle maxDiscCoverage.java` (without renaming it as suggested below), it wouldn't work as `maxDiscCoverage.java` doesn't exist, which was probably the reason why it didn't work at all.

I think what you can do instead is to change the file (extension) from `maxDiscCoverage.jsh` to `maxDiscCoverage.java` temporarily, so you can run the checkstyle on it. Then afterwards, change it back.  Running the java checkstyle on .jsh file went through with "Audit done" with no errors (despite intentional styling errors) was because no audit was done in the first place. According to `cs2030_checks.xml`, it only check for file with `java`, `properties` and `xml` extensions.

P.S. you can rename files easily by typing `mv file.jsh file.java` to convert `.jsh` to `.java`.

**Comment by connlim** [comment]
Here's a simple shell script I whipped up to run checkstyle on .jsh files automatically. It creates temp .java files from .jsh files, runs checkstyle on everything, and then deletes the temp .java files. You can probably alias it to a command if you want to run it from any directory.
```bash
#!/usr/bin/bash
for file in *.jsh; do
    java_file="${file%.*}.java"
    echo "class ${file%.*} {" > "$java_file"
    cat "$file" | sed 's/^/    /' >> "$java_file"
    echo "}" >> "$java_file"
done

java -jar <path to checkstyle>/checkstyle-8.2-all.jar -c <path to checkstyle>/cs2030_checks.xml *.java

for file in *.jsh; do
    rm "${file%.*}.java"
done
```

Disclaimer: I'm not responsible if it somehow deletes your files :)

**Comment by Polygonalr** [comment]
> P.S. you can rename files easily by typing `mv file.jsh file.java` to convert `.jsh` to `.java`.

@lhy-hoyin Yep, that's what I meant when I mentioned that I changed the file to use the `.java` extension. I do get an error when running the checkstyle after doing so though.

![image](https://user-images.githubusercontent.com/16399656/131234860-693d3fa9-0196-415c-8fd4-981d77e38719.png)

(checkstylef is my alias for checking individual files)

For now I guess we can use Connor's workaround.

**Comment by lhy-hoyin** [comment]
> For now I guess we can use Connor's workaround.

Hmm...I don't think Connor's workaround will work. I appreciate that he actually came up with a script to help automate the process of creating the temp `.java` files.

> ![image](https://user-images.githubusercontent.com/16399656/131234907-7726ed7f-3a2f-411c-955b-2dd7e49154de.png)

Based on the screenshot of the error provided, it appears that the error causing that checkstyle was casued by `Circle` in the first line (and first word) of `maxDiscCoverage.*`. Looking at Connor's script, I don't think it will help resolve the error (since the error is caused by the content of the file).

**Comment by Polygonalr** [comment]
> Based on the screenshot of the error provided, it appears that the error causing that checkstyle was casued by `Circle` in the first line (and first word) of `maxDiscCoverage.*`. Looking at Connor's script, I don't think it will help resolve the error (since the error is caused by the content of the file).

His script is working well on my end. Here's my console output while doing my testing.

```
~/cs2030stuff/testscript
❯ ls
checkjsh.sh  mdctest.jsh

~/cs2030stuff/testscript
❯ ./checkjsh.sh
Starting audit...
[WARN] /home/mylinux/cs2030stuff/testscript/mdctest.java:1:7: Type name 'mdctest' must match pattern '^[A-Z][a-zA-Z0-9]*$'. [TypeName]
[WARN] /home/mylinux/cs2030stuff/testscript/mdctest.java:4:55: ')' is preceded with whitespace. [ParenPad]
[WARN] /home/mylinux/cs2030stuff/testscript/mdctest.java:13:12: WhitespaceAround: 'for' is not followed by whitespace. Empty blocks may only be represented as {} when not part of a multi-block statement (4.1.3) [WhitespaceAround]
[WARN] /home/mylinux/cs2030stuff/testscript/mdctest.java:14:16: WhitespaceAround: 'for' is not followed by whitespace. Empty blocks may only be represented as {} when not part of a multi-block statement (4.1.3) [WhitespaceAround]
[WARN] /home/mylinux/cs2030stuff/testscript/mdctest.java:15:19: WhitespaceAround: 'if' is not followed by whitespace. Empty blocks may only be represented as {} when not part of a multi-block statement (4.1.3) [WhitespaceAround]
[WARN] /home/mylinux/cs2030stuff/testscript/mdctest.java:18:24: WhitespaceAround: 'for' is not followed by whitespace. Empty blocks may only be represented as {} when not part of a multi-block statement (4.1.3) [WhitespaceAround]
[WARN] /home/mylinux/cs2030stuff/testscript/mdctest.java:19:27: WhitespaceAround: 'if' is not followed by whitespace. Empty blocks may only be represented as {} when not part of a multi-block statement (4.1.3) [WhitespaceAround]
[WARN] /home/mylinux/cs2030stuff/testscript/mdctest.java:20:36: '++' is preceded with whitespace. [NoWhitespaceBefore]
[WARN] /home/mylinux/cs2030stuff/testscript/mdctest.java:23:23: WhitespaceAround: 'if' is not followed by whitespace. Empty blocks may only be represented as {} when not part of a multi-block statement (4.1.3) [WhitespaceAround]
Audit done.

~/cs2030stuff/testscript
❯ checkstylef mdctest.jsh
Starting audit...
Audit done.

~/cs2030stuff/testscript
❯ mv mdctest.jsh mdctest.java

~/cs2030stuff/testscript
❯ checkstylef mdctest.java
Starting audit...
com.puppycrawl.tools.checkstyle.api.CheckstyleException: Exception was thrown while processing mdctest.java
        at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:295)
        at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:213)
        at com.puppycrawl.tools.checkstyle.Main.runCheckstyle(Main.java:523)
        at com.puppycrawl.tools.checkstyle.Main.runCli(Main.java:437)
        at com.puppycrawl.tools.checkstyle.Main.main(Main.java:210)
Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: NoViableAltException occurred during the analysis of file mdctest.java.
        at com.puppycrawl.tools.checkstyle.TreeWalker.processFiltered(TreeWalker.java:231)
        at com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck.process(AbstractFileSetCheck.java:79)
        at com.puppycrawl.tools.checkstyle.Checker.processFile(Checker.java:316)
        at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:286)
        ... 4 more
Caused by: /home/mylinux/cs2030stuff/testscript/mdctest.java:1:1: unexpected token: Circle
        at com.puppycrawl.tools.checkstyle.grammars.GeneratedJavaRecognizer.compilationUnit(GeneratedJavaRecognizer.java:181)
        at com.puppycrawl.tools.checkstyle.TreeWalker.parse(TreeWalker.java:500)
        at com.puppycrawl.tools.checkstyle.TreeWalker.processFiltered(TreeWalker.java:202)
        ... 7 more
Checkstyle ends with 1 errors.

~/cs2030stuff/testscript
❯
```

As I mentioned before, the only solution to test `.jsh` code seems to be appending it to a Java class before running `checkstyle` (which is what Connor's script does!).

**Comment by RussellDash332** [comment]
> > Based on the screenshot of the error provided, it appears that the error causing that checkstyle was casued by `Circle` in the first line (and first word) of `maxDiscCoverage.*`. Looking at Connor's script, I don't think it will help resolve the error (since the error is caused by the content of the file).
> 
> His script is working well on my end. Here's my console output while doing my testing.
> 
> ```
> ~/cs2030stuff/testscript
> ❯ ls
> checkjsh.sh  mdctest.jsh
> 
> ~/cs2030stuff/testscript
> ❯ ./checkjsh.sh
> Starting audit...
> [WARN] /home/mylinux/cs2030stuff/testscript/mdctest.java:1:7: Type name 'mdctest' must match pattern '^[A-Z][a-zA-Z0-9]*$'. [TypeName]
> [WARN] /home/mylinux/cs2030stuff/testscript/mdctest.java:4:55: ')' is preceded with whitespace. [ParenPad]
> [WARN] /home/mylinux/cs2030stuff/testscript/mdctest.java:13:12: WhitespaceAround: 'for' is not followed by whitespace. Empty blocks may only be represented as {} when not part of a multi-block statement (4.1.3) [WhitespaceAround]
> [WARN] /home/mylinux/cs2030stuff/testscript/mdctest.java:14:16: WhitespaceAround: 'for' is not followed by whitespace. Empty blocks may only be represented as {} when not part of a multi-block statement (4.1.3) [WhitespaceAround]
> [WARN] /home/mylinux/cs2030stuff/testscript/mdctest.java:15:19: WhitespaceAround: 'if' is not followed by whitespace. Empty blocks may only be represented as {} when not part of a multi-block statement (4.1.3) [WhitespaceAround]
> [WARN] /home/mylinux/cs2030stuff/testscript/mdctest.java:18:24: WhitespaceAround: 'for' is not followed by whitespace. Empty blocks may only be represented as {} when not part of a multi-block statement (4.1.3) [WhitespaceAround]
> [WARN] /home/mylinux/cs2030stuff/testscript/mdctest.java:19:27: WhitespaceAround: 'if' is not followed by whitespace. Empty blocks may only be represented as {} when not part of a multi-block statement (4.1.3) [WhitespaceAround]
> [WARN] /home/mylinux/cs2030stuff/testscript/mdctest.java:20:36: '++' is preceded with whitespace. [NoWhitespaceBefore]
> [WARN] /home/mylinux/cs2030stuff/testscript/mdctest.java:23:23: WhitespaceAround: 'if' is not followed by whitespace. Empty blocks may only be represented as {} when not part of a multi-block statement (4.1.3) [WhitespaceAround]
> Audit done.
> 
> ~/cs2030stuff/testscript
> ❯ checkstylef mdctest.jsh
> Starting audit...
> Audit done.
> 
> ~/cs2030stuff/testscript
> ❯ mv mdctest.jsh mdctest.java
> 
> ~/cs2030stuff/testscript
> ❯ checkstylef mdctest.java
> Starting audit...
> com.puppycrawl.tools.checkstyle.api.CheckstyleException: Exception was thrown while processing mdctest.java
>         at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:295)
>         at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:213)
>         at com.puppycrawl.tools.checkstyle.Main.runCheckstyle(Main.java:523)
>         at com.puppycrawl.tools.checkstyle.Main.runCli(Main.java:437)
>         at com.puppycrawl.tools.checkstyle.Main.main(Main.java:210)
> Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: NoViableAltException occurred during the analysis of file mdctest.java.
>         at com.puppycrawl.tools.checkstyle.TreeWalker.processFiltered(TreeWalker.java:231)
>         at com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck.process(AbstractFileSetCheck.java:79)
>         at com.puppycrawl.tools.checkstyle.Checker.processFile(Checker.java:316)
>         at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:286)
>         ... 4 more
> Caused by: /home/mylinux/cs2030stuff/testscript/mdctest.java:1:1: unexpected token: Circle
>         at com.puppycrawl.tools.checkstyle.grammars.GeneratedJavaRecognizer.compilationUnit(GeneratedJavaRecognizer.java:181)
>         at com.puppycrawl.tools.checkstyle.TreeWalker.parse(TreeWalker.java:500)
>         at com.puppycrawl.tools.checkstyle.TreeWalker.processFiltered(TreeWalker.java:202)
>         ... 7 more
> Checkstyle ends with 1 errors.
> 
> ~/cs2030stuff/testscript
> ❯
> ```
> 
> As I mentioned before, the only solution to test `.jsh` code seems to be appending it to a Java class before running `checkstyle` (which is what Connor's script does!).

It works for me as well! Thanks 😄  @connlim 
Might need to take note that not all checkstyle errors are to be considered in this case, e.g. the file name must follow the regex.

**Comment by lhy-hoyin** [comment]
> Here's a simple shell script I whipped up to run checkstyle on .jsh files automatically. It creates temp .java files from .jsh files, runs checkstyle on everything, and then deletes the temp .java files. You can probably alias it to a command if you want to run it from any directory.
> 
> ```shell
> #!/usr/bin/bash
> for file in *.jsh; do
>     java_file="${file%.*}.java"
>     echo "class ${file%.*} {" > "$java_file"
>     cat "$file" | sed 's/^/    /' >> "$java_file"
>     echo "}" >> "$java_file"
> done
> 
> java -jar <path to checkstyle>/checkstyle-8.2-all.jar -c <path to checkstyle>/cs2030_checks.xml *.java
> 
> for file in *.jsh; do
>     rm "${file%.*}.java"
> done
> ```
> 
> Disclaimer: I'm not responsible if it somehow deletes your files :)

My apologies, it appears that I didn't read through the script thoroughly. I would like to put this as the **recommended answer**. 
Also, I would like to add that while it maybe be possible to run the checkstyle on `*.jsh` files, do read the warning messages from the checkstyle carefully, especially if you put commands like `/open filename.java` within your `*.jsh` file (I believe this will fail the checkstyle, but I have yet to test this).

Thank you all for your inputs. With that, I would like to close this issue.
