### ISSUE TITLE
Don't lose your confidence in the project

### ISSUE THREAD

**Issue by yuyanjulia** [nus-cs2030/2122-s1#330]
I actually started doing the project last week (I know it's a bit late but I was kinda busy during the semester and didn't know where to start). I panicked a lot thinking what if I couldn't finish. But I surprisingly finished in three days. Guess I was lucky and didn't have to change much of my code from level to level. My approach was to minimise the change while making it pass all the test cases. Although I think my design isn't perfect, but I have completed it haha!

So don't be too anxious if you are still not done with the labs or projects. Take a deep breath and do whatever you can achieve in these three days. Never give up! You may be able to finish everything before Thursday. Good Luck!

And to everyone, all the best to your finals!

![1cbb542b423fafe951469bcf8651f28c](https://user-images.githubusercontent.com/77619767/142794314-5bd477d1-68f5-402d-b68e-24f955b34e10.jpg)

**Comment by aanghs22** [comment]
thanks for this :")

**Comment by swiftguy1** [comment]
thanks for this LOL , gives me some hope

**Comment by upabove122** [comment]
Adding to that, I gave up with my initial implementation and reworked from scratch. It also took around 3 days for a working project HAHA

**Comment by DarrenCsAcc** [comment]
i am only at level 2 gg i just see what i can complete hopefully wont have to remod or get Dapao

**Comment by RussellDash332** [comment]
The picture is so cute! But shortly after I got reminded of the Pokemon exception 😭

**Comment by va5hi** [comment]
Thanks needed this i am barely done with the project HAHAHA At this rate, i would be happy with a C+ :')

**Comment by Devvynneo** [comment]
I think it is a good thing that you finish in three days! 
But please be reminded that while you can finish in three days, others might not be able to finish in three days! 
By saying this, you could actually be giving stress to other people who are already taking longer than 3 days to code, questioning their own ability!

**Comment by UnwilledTangent** [comment]
Needed this post. Thanks!

**Comment by yuehernkang** [comment]
power sia bro, finish in 3 days, i took 3 months 😂😂😂😂
