### ISSUE TITLE
Mini Project: private testcase 56

### ISSUE THREAD

**Issue by kxshxsh** [nus-cs2030/2122-s1#331]
## Description 
Hi guys, just failed private test case 56- did someone have this problem too? It's so hard to debug without seeing the full test case haha
I used @taymila's test case to check if my Implementation is lazy enough to pass test case 73- and it worked fine:) So I don't know what the conditions are, to consider, for this test case.. any help? Looks like my filter is one step late but I don't know how one would change something in filter and not compromise on laziness?

## Screenshots (if any): 
![image](https://user-images.githubusercontent.com/92561253/142811957-8a747e98-82ca-4978-956f-08f35b8a03e4.png)

**update:**

![image](https://user-images.githubusercontent.com/92561253/142818462-378765f7-910d-4f31-a541-38ba4c3c5dd4.png)

so this -> ` System.out.println(InfiniteList.iterate(0, op).limit(4).filter(lessThanTwo).count());` case prints out what my code printed out for the failed testcase. But then it makes sense for the iterate to come first and then the filter check.

In what situation would a filter happen before the iteration and how would the test case look for that :/?

**Comment by Eclipse-Dominator** [comment]
You should filter first before iterating. 
Why should you iterate first if you haven't checked the head of the current list first.

**Comment by kxshxsh** [comment]
Figured it out, thanks!! my count() was slightly eager oops
