### ISSUE TITLE
Need help on pyp question

### ISSUE THREAD

**Issue by haoyusimon** [nus-cs2030/2122-s1#333]
![image](https://user-images.githubusercontent.com/77672961/142822976-6579d089-04aa-4a1c-ad92-a3617ca04c75.png)
I am not sure about the last line of code, i.baz(q). Since Interface I only has two overloading methods, baz(P p) and baz(I i), and q here has type Q, which method in class I will be executed? Baz(P p) or baz(I i)?

**Comment by lelerer** [comment]
I think the code should execute baz(Q q) in class Q, since i is actually q(type Q), correct me if I'm wrong.

**Comment by haoyusimon** [comment]
But isnt it static binding when determining overloaded methods?

**Comment by RussellDash332** [comment]
It actually prints 3 😮

**Comment by Le-PenDu** [comment]
![image](https://user-images.githubusercontent.com/30016771/142829679-097e0bca-a52f-4e92-b465-c65e8d61211c.png)
This is the answer to the question.

**Comment by haoyusimon** [comment]
Thanks a lot for the explanation! But why the method invoked in Class Q is baz(P p) instead of baz(I i)? Is it because I is an interface?

**Comment by JavierTham** [comment]
> why the method invoked in Class Q is baz(P p) instead of baz(I i)

yea, I'm so confused XD why is it Baz(P p). Not even Baz(Q q), where did the P even come from :astonished:

**Comment by haoyusimon** [comment]
Ya I wonder if it is because of static binding so can only choose methods in class I, so only Baz(P p) or Baz(I i).

**Comment by baabaablacksheepz** [comment]
Im quite confused with this question also... is it because since Q <: P  and P has a method baz(P p) which is inherited by Q?

**Comment by JavierTham** [comment]
tried coming up with an explanation but realized I'm not very confident with my static/dynamic binding stuff. Here's a java file with all the classes inside including the Parent/Child classes from the ungraded Quiz 7 to play around with. Hope it works, have fun! :D


[polymorphism.zip](https://github.com/nus-cs2030/2122-s1/files/7581075/polymorphism.zip)

**Comment by throwawayAcc123** [comment]
my TA explained this question before, for the last case of i.baz(q), since the CTT of i is interface I, it will look through the lens of interface I for something with CTT of Q. However, there's no baz() method that takes in a Q in the interface I, as such, it will call the closest of Q within the interface itself, which is P in this case. And the story of RTT continues, where i's RTT is Q, and baz(P p) within Q actually prints out 3. 

Hope this helps!

**Comment by haoyusimon** [comment]
Oh, now I understand! Thank you so much for the explanation!!
