### ISSUE TITLE
Type Erasure

### ISSUE THREAD

**Issue by aexolate** [nus-cs2030/2122-s1#334]
From https://docs.oracle.com/javase/tutorial/java/generics/erasure.html, type erasure does

> Replace all type parameters in generic types with their bounds or Object if the type parameters are unbounded

```
abstract class A {
    abstract void test(List<String> list);
    abstract void test(List<? extends Integer> list);
}

|  Error:
|  name clash: test(java.util.List<? extends java.lang.Integer>) and test(java.util.List<java.lang.String>) have the same erasure
|          abstract void test(List<? extends Integer> list);
|          ^-----------------------------------------------^
```

Does `List<? extends Integer>` get erased to `List<Object>` as well? because the statement gave me the impression it will be erased to `List<Integer>` since that is the bound.

**Comment by ZChenxin** [comment]
Yes, to my understanding it will

**Comment by Hongyi6328** [comment]
Yes, generic in java is a mean to ensure type safety at compile-time, but at run time it gets rid of any type variable.

**Comment by haoyusimon** [comment]
Ya I remember prof mentioned in his lecture that generics will be erased to <Object>

**Comment by aexolate** [comment]
Thank you all for the help
