### ISSUE TITLE
CS2030 Java Style Guide Point 9

### ISSUE THREAD

**Issue by cliftonfelix** [nus-cs2030/2122-s1#34]
"9. Each line is limited to 80 characters in length. You can break a long line into multiple lines to enhance readability, this is called line wrapping. When you do so, each continuation line is indented at 8 spaces (twice the normal indentation) from the original line."

Is there a way to automatically break a long line in VIM?
Thank you.

**Comment by zunedz** [comment]
You can set the maximum width of each line by using this command on vim NORMAL MODE

`:set tw=80`

**Comment by hingen** [comment]
Alternatively, if you want to handle line wrapping yourself to ensure that it conforms to the style guide, u can use the command  `:set colorcolumn=80`or add `set colorcolumn=80` into your `.vimrc`. It'll mark the 80th column in red so you'll know if your line exceeds 80 characters

**Comment by lhy-hoyin** [comment]
> You can set the maximum width of each line by using this command on vim NORMAL MODE
> 
> `:set tw=80`


Just note that although it can be automated, I would recommend breaking the long line manually, as it gives you more control over where you want to break up the line.

For example, 
```java
// 151 characters
System.out.println("<some very long text in front> The values are a = %d, b = %d, c = $d, d = $d", myVariableA, myVariableB, myVariableC, myVariableD);

//automatically broken up at character 80
System.out.println("<some very long text in front> The values are a = %d, b = %d
        , c = $d, d = $d", myVariableA, myVariableB, myVariableC, myVariableD);

// Broken up manually to improve readability
System.out.println("<some very long text in front> The values are a = %d, b = %d, c = $d, d = $d", 
        myVariableA, myVariableB, myVariableC, myVariableD);
```
