### ISSUE TITLE
[PYP] Immutable cyclic reference

### ISSUE THREAD

**Issue by RussellDash332** [nus-cs2030/2122-s1#340]
I wonder if there is an easier way to implement such in an easier way than StackOverflow because the solutions I found seem to be hackish in a way that violates the ground rules of CS2030.

Source is AY20/21 S1.
```java
// Code for part (a)
class A {
    private A other;

    void set(A other) {
        this.other = other;
    }

    A get() {
        return this.other;
    }
}
```
![image](https://user-images.githubusercontent.com/63991775/142910280-0d971c43-d93c-4c51-8acc-8a381cf40a15.png)
![image](https://user-images.githubusercontent.com/63991775/142910357-159f82fc-b524-4e0a-adaa-6b8e0a5cf21d.png)

Tag @BrendanCheong

**Comment by BrendanCheong** [comment]
Tag @hwkchia

**Comment by hingen** [comment]
Considering that the question is 1 mark I feel like it shouldn't be dat difficult. Perhaps, the phrasing of the question is just bad and dat we're suppose to use the unmodified mutable version of the A and B class.

**Comment by RussellDash332** [comment]
> Considering that the question is 1 mark I feel like it shouldn't be dat difficult. Perhaps, the phrasing of the question is just bad and dat we're suppose to use the unmodified mutable version of the A and B class.

*+3 marks, since we had to do part (C) too?

**Comment by hingen** [comment]
> > Considering that the question is 1 mark I feel like it shouldn't be dat difficult. Perhaps, the phrasing of the question is just bad and dat we're suppose to use the unmodified mutable version of the A and B class.
> 
> *+3 marks, since we had to do part (C) too?

hmmm, I feel like since it is not mentioned anywhere in part c, they shouldn't be able to penalise u for designing an immutable version without caring for whether cyclic referecing is possible. Especially when its explicitly stated how much points are allocated for each part.

That aside, perhaps the method that is most in line with what is taught in CS2030 is lazy evaluation? Something along the lines of
```java
List<A> other = new ArrayList<A>();
Supplier<A> sup = () -> other.get(0);
```
`sup` can be evaluated to get `other` when needed and it also gives us the ability the value in `other` allowing for cyclic referencing

**Comment by hingen** [comment]
Was thinking maybe something like that?

```java
import java.util.ArrayList;
import java.util.List;
import java.util.function.Supplier;

abstract class Base {
    private final Supplier<Base> other;

    protected Base(Supplier<Base> other) {
        this.other = other;
    }

    abstract Base set(Base other);
    abstract Base set(Supplier<Base> other);

    Base get() {
        return other.get();
    }
}

class A extends Base {
    public A() {
        super(() -> null);
    }

    private A(Supplier<Base> other) {
        super(other);
    }

    @Override
    A set(Base other) {
        return new A(() -> other);
    }

    @Override
    A set(Supplier<Base> other) {
        return new A(other);
    }
}

class B extends Base {
    public B() {
        super(() -> null);
    }

    private B(Supplier<Base> other) {
        super(other);
    }

    @Override
    B set(Base other) {
        return new B(() -> other);
    }

    @Override
    B set(Supplier<Base> other) {
        return new B(other);
    }
}

class Main {
    public static void main(String[] args) {
        List<Base> aOther = new ArrayList<Base>();
        Supplier<Base> aOtherSup = () -> aOther.get(0);
        List<Base> a2Other = new ArrayList<Base>();
        Supplier<Base> a2OtherSup = () -> a2Other.get(0);
        List<Base> b1Other = new ArrayList<Base>();
        Supplier<Base> b1OtherSup = () -> b1Other.get(0);
        List<Base> b2Other = new ArrayList<Base>();
        Supplier<Base> b2OtherSup = () -> b2Other.get(0);

        A a = new A().set(aOtherSup);
        A a2 = new A().set(a2OtherSup);
        B b1 = new B().set(b1OtherSup);
        B b2 = new B().set(b2OtherSup);

        aOther.add(a2);
        a2Other.add(b1);
        b1Other.add(b2);
        b2Other.add(a);

        System.out.println(a);
        System.out.println(a.get());
        System.out.println(a.get().get());
        System.out.println(a.get().get().get());
        System.out.println(a.get().get().get().get());
        System.out.println(a.get().get().get().get().get());
    }
}
```

**Comment by RussellDash332** [comment]
> ```java
> import java.util.ArrayList;
> import java.util.List;
> import java.util.function.Supplier;
> 
> abstract class Base {
>     private final Supplier<Base> other;
> 
>     protected Base(Supplier<Base> other) {
>         this.other = other;
>     }
> 
>     abstract Base set(Base other);
>     abstract Base set(Supplier<Base> other);
> 
>     Base get() {
>         return other.get();
>     }
> }
> 
> class A extends Base {
>     public A() {
>         super(() -> null);
>     }
> 
>     private A(Supplier<Base> other) {
>         super(other);
>     }
> 
>     @Override
>     A set(Base other) {
>         return new A(() -> other);
>     }
> 
>     @Override
>     A set(Supplier<Base> other) {
>         return new A(other);
>     }
> }
> 
> class B extends Base {
>     public B() {
>         super(() -> null);
>     }
> 
>     private B(Supplier<Base> other) {
>         super(other);
>     }
> 
>     @Override
>     B set(Base other) {
>         return new B(() -> other);
>     }
> 
>     @Override
>     B set(Supplier<Base> other) {
>         return new B(other);
>     }
> }
> 
> class Main {
>     public static void main(String[] args) {
>         List<Base> aOther = new ArrayList<Base>();
>         Supplier<Base> aOtherSup = () -> aOther.get(0);
>         List<Base> a2Other = new ArrayList<Base>();
>         Supplier<Base> a2OtherSup = () -> a2Other.get(0);
>         List<Base> b1Other = new ArrayList<Base>();
>         Supplier<Base> b1OtherSup = () -> b1Other.get(0);
>         List<Base> b2Other = new ArrayList<Base>();
>         Supplier<Base> b2OtherSup = () -> b2Other.get(0);
> 
>         A a = new A().set(aOtherSup);
>         A a2 = new A().set(a2OtherSup);
>         B b1 = new B().set(b1OtherSup);
>         B b2 = new B().set(b2OtherSup);
> 
>         aOther.add(a2);
>         a2Other.add(b1);
>         b1Other.add(b2);
>         b2Other.add(a);
> 
>         System.out.println(a);
>         System.out.println(a.get());
>         System.out.println(a.get().get());
>         System.out.println(a.get().get().get());
>         System.out.println(a.get().get().get().get());
>         System.out.println(a.get().get().get().get().get());
>     }
> }
> ```

Wow this actually, although for one marks somehow.
Also, you can combine the lists into one list.
