### ISSUE TITLE
How does combiner work??

### ISSUE THREAD

**Issue by wjingen** [nus-cs2030/2122-s1#341]
# Description

Hi all,

Kind of a silly question but I thought I'll ask it anyway.

What exactly is the purpose of the combiner argument inside the reduce function of Streams?

From my test cases below it doesn't seem to matter. I don't understand the Java API explanation too...

Thanks!
![image](https://user-images.githubusercontent.com/74229021/142924311-495c1213-c183-4aa0-b043-139b7a9aedb2.png)
![image](https://user-images.githubusercontent.com/74229021/142924715-0b2283d5-035f-4de2-9e51-2de87ee97c16.png)

## Topic:

Specific Topics this question is related to (If Any)

## Screenshots

Screenshots (if any)
![image](https://user-images.githubusercontent.com/74229021/142924592-ebe587b7-9186-4470-ae16-34b2ab9ddfb9.png)
![image](https://user-images.githubusercontent.com/74229021/142924638-15870a0b-381a-41a5-a161-de367e6f2928.png)

**Comment by RussellDash332** [comment]
The combiner is never invoked in all your stream methods because it is not parallelized. The idea of combiner is basically how would you combine the accumulated values from each thread after parallelization.

A visualization is provided [here](https://stackoverflow.com/questions/24308146/why-is-a-combiner-needed-for-reduce-method-that-converts-type-in-java-8).

**Comment by wjingen** [comment]
> The combiner is never invoked in all your stream methods because it is not parallelized. The idea of combiner is basically how would you combine the accumulated values from each thread after parallelization.
> 
> A visualization is provided [here](https://stackoverflow.com/questions/24308146/why-is-a-combiner-needed-for-reduce-method-that-converts-type-in-java-8).

OH sick, didn't know that. Thanks!

**Comment by RussellDash332** [comment]
Also another case is when the accumulator is not a binary operator, and thus a combiner is needed. Source is still from that link, in case I didn't point it out.
