### ISSUE TITLE
sub 1 is printed twice, level 5

### ISSUE THREAD

**Issue by ruyian** [nus-cs2030/2122-s1#348]
# Summary

Description of the question / problem here.
For the level 5, everything works well except that the "sub 1" is printed twice.
It should execute for only once but how come it is executed for 2 times?
How should I change it such that it is only printed once.

## Description:

Below is my code for my test()

## Code Snippets

Attach code snippets (if any)
![image](https://user-images.githubusercontent.com/78540645/143008081-07b7a9e1-898f-4c47-875e-76d489b50578.png)

## Screenshots

Screenshots (if any)

Thank you very much. Look forward to hearing from you!

**Comment by ruyian** [comment]
![image](https://user-images.githubusercontent.com/78540645/143012482-a94586a4-7409-4064-b22e-4131e486eacc.png)
here is how I did the map.
It must be that applied is executed twice. How can I make it execute only once?

**Comment by TanPingZhi** [comment]
You need to cache the output of the function so it doesnt evaluate again. maybe try to use Lazy from the infinitelist project.
this issue was discussed before too maybe you can try to dig up the previous issue

**Comment by TanPingZhi** [comment]
[#147 ](url)

**Comment by sheshenk** [comment]
As commented above, your `Logger` needs to store the current value lazily. If you haven't completed the InfiniteList project and don't have the `Lazy` class, then you can consider using a supplier to store your value. I managed to make it work using this method.

**Comment by brextonho** [comment]
if you were to use Supplier, both your `x` and logs should be wrapped in a Supplier. so my history is `ArrayList<Supplier<String>>`, and every time you update your history you do `newHistory.add(() -> x.get.toString())`.

in the toString() method in Logger, you can store `x.get().toString()` in a variable and use it twice, so that you dont call get() multiple times for the final value. (see #147 and #172)

**Comment by aanghs22** [comment]
What's your toString() method implementation like? if you find yourself calling something along the lines of `this.get()` twice, you should call `this.get()` once, store it in a variable like what brexton said and use the variable in place of the situations where you called `this.get()`

**Comment by ruyian** [comment]
> What's your toString() method implementation like? if you find yourself calling something along the lines of `this.get()` twice, you should call `this.get()` once, store it in a variable like what brexton said and use the variable in place of the situations where you called `this.get()`

Hi there, thank you very much. I realize the mistake in my `toString()` method a while after posting this issue. I should have saved the result of `get()` to avoid the supplier function to be executed repeatedly.
