### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by beeaatrrice** [nus-cs2030/2122-s1#349]
i submitted my code on codecrunch and there were some compilation errors :( What does this mean?

field pq in class Simulator
field servers in class Simulator
field pq in class Simulator
field servers in class Simulator
not declared private/protected final

**Comment by xzzz3** [comment]
all the fields need to be private final :( one way to get past it is to use private final arrays assuming it works with your code

**Comment by yuehernkang** [comment]
bo bian must make everything private final
