### ISSUE TITLE
Level 3 findBusServicesBetween

### ISSUE THREAD

**Issue by ChrisHo1341** [nus-cs2030/2122-s1#356]
How do you guys create a Map<BusService, CompletableFutre<Set<BusStop>>> using thenapply? I keep getting the following error.
![busstop](https://user-images.githubusercontent.com/79920944/143052528-8c3e38ee-7ade-4f0e-b543-08b7355556fb.PNG)

Any help is much appreciated!

**Comment by hgimleng** [comment]
You need to change BusRoutes so that it stores Map<BusService,CompletableFuture<Set<BusStop>>> as well as the description method.

**Comment by ChrisHo1341** [comment]
Yup i changed it to Map<BusService, CompletableFuture<Set>> and description to CompletableFuturte<String> but still getting this issue.

Side note: was i supposed to change describeservice to CompletableFuture<String>?

**Comment by ChrisHo1341** [comment]
I think after using thenApply > i will get a completablefuture of a map, how do I get the Map out of the completable future? I'm not supposed to use .join() until the final level right?

**Comment by yuyanjulia** [comment]
> Yup i changed it to Map<BusService, CompletableFuture> and description to CompletableFuturte but still getting this issue.
> 
> Side note: was i supposed to change describeservice to CompletableFuture as well?

Yes, `describeService` should return `CompletableFuture<String>`

**Comment by hgimleng** [comment]
I changed describeService as well. I performed a second thenApply to convert the CompletableFuture of map to CompletableFuture<BusRoutes> by passing the map into the BusRoutes constructor.

Yup, join shouldn't be used until the last level.

**Comment by ChrisHo1341** [comment]
Oh wait so the map is also a completable future now?

**Comment by brextonho** [comment]
> Oh wait so the map is also a completable future now?

yea, so i did `CompletableFuture<Map<BusService, CompletableFuture<Set<BusStop>>>>`, and at the end you will use `thenApply` to put the `Map<BusService, CompletableFuture<Set<BusStop>>>` into the BusRoutes constructor!

**Comment by ChrisHo1341** [comment]
oooh i finally got it! thank you guys!
