### ISSUE TITLE
Physical Notes for Finals

### ISSUE THREAD

**Issue by josiahoo** [nus-cs2030/2122-s1#360]
Just want to clarify, just like the PAs, are we allowed to bring in our own physical notes for tomorrow's finals? As well as writing paper in case we need to pen down our thoughts or plan out our answers.

**Comment by huzaifa1712** [comment]
Hmm seems like it, at least according to this announcement
<img width="1674" alt="Screenshot 2021-11-24 at 12 20 01 PM" src="https://user-images.githubusercontent.com/20151382/143174449-132d82ec-a07d-4f51-ba63-3506086201ed.png">

**Comment by jehousoh** [comment]
Yep it's allowed but just use them within the zoom frame i guess so it won't be sus

**Comment by josiahoo** [comment]
Ahhh ok thanks guys!!
