### ISSUE TITLE
CompletableFuture if statement without using join()

### ISSUE THREAD

**Issue by pengjiakun** [nus-cs2030/2122-s1#362]
# Summary
I have a CompletableFuture<Set>, and I want to execute some code if the set is empty. How do I go about doing this without using join() to obtain the set itself?

**Comment by brextonho** [comment]
which method is this for ah? i think we can use `thenApply` to operate on the thing inside of CompletableFuture, so that it will still return a CompletableFuture in the end! maybe you can put the "set is empty" condition inside a lambda function inside `thenApply`?

**Comment by pengjiakun** [comment]
This was specifically for level 1 and 3 for the lab. I managed to solve this by creating a helper function, then using `thenApply` to pass the object in CompletableFuture through it to get the behavior that I wanted.
