### ISSUE TITLE
Printing out outputs for level 4

### ISSUE THREAD

**Issue by ChrisHo1341** [nus-cs2030/2122-s1#363]
Hey guys, im not very sure how to print out my outputs for level 4

I'm currently saving all the findBusServicesBetween completable futures into a list, then turning the list into an array and then use the allOf(arr) method and join() it. After that how do I print out the results?

I'm trying to loop through the same array again and print out each result with .get() but i keep running into the following error
error: unreported exception InterruptedException; must be caught or declared to be thrown

Any help is much appreciated!

**Comment by BrendanCheong** [comment]
loop through the array again and do this `arr[i].thenAccept((x) -> System.out.println(x))`

**Comment by ChrisHo1341** [comment]
Hi thanks for the reply!
I tried that and i get java.util.concurrent.CompletableFuture@50a7bc6e[Not completed]
However i did do CompletableFuture.allOf(arr).join();
before looping through the array

Am I doing something wrong?
