### ISSUE TITLE
Level 4 project

### ISSUE THREAD

**Issue by TsangZiXuan** [nus-cs2030/2122-s1#364]
hey guys, how did you implement your check out counters? i'm thinking of changing my server class to abstract so i can inherit a self check out counter class from it? but I'm wondering if there are other ways too! Thanks!!

**Comment by ChrisHo1341** [comment]
I made a abstract staff class then both server and SCO counter inherits from it

**Comment by aaronthamsc98** [comment]
I created a self-checkout class that extends Server and tweak some of the methods accordingly. But as what ChrisHo has mentioned, I think it would be more ideal to create an abstract staff class and have both server and SCO inherit it from there!

**Comment by brandonrhan** [comment]
extend from server will be easier i think. coz u don't need to remove everything from level3 and just need to change a few method according to your project structure

**Comment by jehousoh** [comment]
I too made my self-checkout class extend from server and overrided the methods from the Server class and changed it accordingly
