### ISSUE TITLE
Project Testcase 5_03

### ISSUE THREAD

**Issue by tubting** [nus-cs2030/2122-s1#365]
Anyone experience this issue where the service time generated does not seem to match the expected output?:( 

<img width="578" alt="Screenshot 2021-11-24 at 1 38 03 PM" src="https://user-images.githubusercontent.com/85825676/143181232-873a9b61-e3f4-4282-b300-2323634ff079.png">

**Comment by ChrisHo1341** [comment]
I had a similar issue because I did not generate the servicetimes/restingtimes at the appropriate stages
You want to only generate service time during a serve event and resting time during a done event

**Comment by Gibson0918** [comment]
> It is also worth noting that the service time cannot be generated together with the arrival time as each customer is created before the simulation starts, since the nth customer to arrive might not be the nth customer to be served! Although this might entail passing the RandomGenerator along with the Customer. This need not be so! Hint: Think `Lazy..

Check if you are generating the service time eagerly. You can create a supplier and pass the supplier around and call get() on that supplier to get the svcTime of that particular customer when you actually need it.

**Comment by tubting** [comment]
thanks for all the suggestions!!
