### ISSUE TITLE
Level 4 CompletableFutures not completed

### ISSUE THREAD

**Issue by ChrisHo1341** [nus-cs2030/2122-s1#367]
Hi, I'm currently tackling level 4 by creating a list of completablefutures then adding each findBusServicesBetween output to the list.

Then i turn it into an array and call allOf(arr).join()

After which i loop through this list and call arr[i].thenAccept(x -> System.out.println(x));

However the output im getting is java.util.concurrent.CompletableFuture@4034c28c[Not completed]

Any help will be much appreciated!

**Comment by EricBryann** [comment]
Yo I think if you can give us a screenshot of your code that will be great!

**Comment by EricBryann** [comment]
For me I did this

`CompletableFuture.allOf(cfs.toArray(new CompletableFuture<?>[cfs.size()]));`

with `cfs` declared as
`List<CompletableFuture<String>> cfs = new ArrayList<>();`
