### ISSUE TITLE
Does anyone have idea on how to do this kind of exception question?

### ISSUE THREAD

**Issue by adam07018** [nus-cs2030/2122-s1#369]
![Screenshot 2021-11-24 152414](https://user-images.githubusercontent.com/62133038/143193398-37a1cab0-ee48-4385-b7d3-9fc2a2561824.png)

**Comment by optionalemon** [comment]
use try-catch in main, the order of catch is from the most specific exception to the least specific, ie catch(NoPerssionException) first and catch(DatabaseException) last, do not catch(Exception), which is Pokemon exception handling

**Comment by kxshxsh** [comment]
> Use try-catch block in main
> 
> The order of catch is from the most specific exception to the least specific, ie `catch(NoPerssionException)` first and `catch(DatabaseException) `last
> 
> do not catch(Exception), which is Pokemon exception handling

yeap this is the way to go:))

**Comment by BrendanCheong** [comment]
```java
try {
    Main.accessDatabase();
} catch (NoPermissionException ex) {
    System.err.println(ex);
} catch (ElementNotFoundException ex) {
    System.err.println(ex);
} catch (ReadException ex) {
    System.err.println(ex);
} catch (WriteException ex) {
    System.err.println(ex);
} catch (TableException ex) {
    System.err.println(ex);
} catch (DatabaseException ex) {
    System.err.println(ex);
}

```
Exception :> DatabaseException
DatabaseException :> TableException
TableException :> ReadException :> ElementNotFoundException
TableException :> WriteException :> NoPermissionException

**Comment by wjingen** [comment]
Just to be clear, the order of ReadException and Write exception doesn't matter?

Also, the order of NoPermissionException and ElementNotFound Exception?

**Comment by BrendanCheong** [comment]
> Just to be clear, the order of ReadException and Write exception doesn't matter?
> 
> Also, the order of NoPermissionException and ElementNotFound Exception?

yeah
