### ISSUE TITLE
Java version

### ISSUE THREAD

**Issue by yuqitanyq** [nus-cs2030/2122-s1#4]
# Summary
Had installed java previously, where the version was 11.0.11, is that okay?

## Description 
Good afternoon prof and everyone, I had installed java previously and I ran `java -version` on my terminal to see which version it was. It turns out that the version is 11.0.11 but I understand that the version on the Setting Up Java wiki page is intending to install 11.0.8. I was wondering if 11.0.11 is okay too? or do I need to uninstall my current one and reinstall it again according to the wiki page? Thank you!

## Screenshots (if any): 
![image](https://user-images.githubusercontent.com/83687861/128629017-57b55503-21d9-4bd1-8202-304e1ce812ea.png)

**Comment by hwkchia** [comment]
Yes, as long as its jdk11.

**Comment by yuqitanyq** [comment]
okay got it! Thanks for clarifying prof!
