### ISSUE TITLE
Overriding Serve ?

### ISSUE THREAD

**Issue by zunedz** [nus-cs2030/2122-s1#41]
## Description:

For lab 2 - level 6, I initially approach this problem by overriding the serve method in order to return a RecycledLoader instead of a Loader object. However, I did not manage to find a way as the "overriding serve method" requires the RecycleLoader (subclass of Loader) to access the identifier and cruise of the Loader class (superclass of Loader), which is private. I believe that we cannot change it to protected or create a protected getter of this variable (please confirm). Here's the code snippet:

```java
@Override
RecycledLoader serve(Cruise cruise) {
    if (canServe(cruise)) {
        return new RecycledLoader(this.identifier, cruise);
    }
    else {                                                                                                         
        return this;                                                                                            
    }   
}
```
So is there a way around this problem?

## REMARKS
Perhaps the not-so-elegant solution that I found was to create a new instance of RecycledLoader directly inside the "serveCruises function" instead of using the "serve method", does this violates any OOP paradigms?

I think it is somewhat related to the issue below this but I think a new post dedicated to this wouldn't do any harm.

**Comment by RussellDash332** [comment]
You have a method to get the identifier without accessing it directly.

**Comment by hauchongtang** [comment]
How I approached it was to create a cruise getter in the Loader class.

**Comment by zunedz** [comment]
I thought creating a getter function violates the "tell don't ask principle" unless it's private, in this case, it does not? Thanks for the replies!

**Comment by RussellDash332** [comment]
> I thought creating a getter function violates the "tell don't ask principle" unless it's private, in this case, it does not? Thanks for the replies!

You are to create the getter function from the previous tasks so I guess u can use it?

**Comment by zunedz** [comment]
oh right my bad didn't notice :( Thanks! as for the remarks part in my post, are there any OOP principles violated?

**Comment by weiseng18** [comment]
Can confirm that `protected` will not work as the grader enforces that both `identifier` and `cruise` must be `private final`.

As for your approach in Remarks, you are delegating some logic handling to the client, which could have been handled by your code, so I think maybe that's where it's not so ideal? Not sure if there is a specific OOP paradigm related to this

**Comment by francisyzy** [comment]
> 
> 
> Can confirm that `protected` will not work as the grader enforces that both `identifier` and `cruise` must be `private final`, and will not grade your solution if either is not `private final`.
> 
> As for your approach in Remarks, you are delegating some logic handling to the client, which could have been handled by your code, so I think maybe that's where it's not so ideal? Not sure if there is a specific OOP paradigm related to this

Hi just to check if we are not using the auto grader, should we use protected instead of making getters if the children requires to access the parent property?

**Comment by weiseng18** [comment]
sorry I missed this, if you're referring to within this module, I think that you should use getters because eventually you will submit to codecrunch anyway
