### ISSUE TITLE
Time Complexity

### ISSUE THREAD

**Issue by cliftonfelix** [nus-cs2030/2122-s1#44]
How important is the time complexity in Lab assignments and PE? Will there be any hidden test cases where n can be a large number to test whether our code works for large n or not? Because in CS2040, maintaining the time complexity is quite important for the assignments (there was no PE last sem).
Thank you

**Comment by zunedz** [comment]
I believe this module mainly focuses on OOP and the correctness of your implementation, so as long as your code adheres to the OOP principles and does not have infinite execution time (such as infinite loop/recursion) it's ok? For test cases, I think only the prof can confirm whether there is such hidden edge cases.

**Comment by hwkchia** [comment]
Hidden edge cases are meant to ascertain if the logic or design breaks, and not about time/space complexities.
