### ISSUE TITLE
Indentation / FileTabCharacter Errors on CodeCrunch

### ISSUE THREAD

**Issue by yueyin22** [nus-cs2030/2122-s1#46]
## Description 
Does anyone know how to solve this without any manual changes? 
It happened in lab1 which i changed it line by line, and now its happening for lab2.

## Screenshots (if any): 
![image](https://user-images.githubusercontent.com/79189775/132623652-cb40996e-435d-4a23-9901-93bf5b04b514.png)

**Comment by RussellDash332** [comment]
Maybe at some particular spot you have 3 spaces for a one-level indentation instead of 4. To resolve this, try use `gg=G` on vim when opening your file in normal mode.

**Comment by yueyin22** [comment]
> Maybe at some particular spot you have 3 spaces for a one-level indentation instead of 4. To resolve this, try use `gg=G` on vim when opening your file in normal mode.
> 
> Other remaining checkstyle issues than this shouldn't be indentation's fault, I guess.

I tried with gg=G but it didn't work. Lab1 was like this as well, and i had to manually change every line for all my classes. Is there a better way to fix this? Did i not install something correctly?

**Comment by RussellDash332** [comment]
> I tried with gg=G but it didn't work.

Interesting. Have you checked if the `.vimrc` has specified `set tabstop=4`?

**Comment by yueyin22** [comment]
> > I tried with gg=G but it didn't work.
> 
> Interesting. Have you checked if the `.vimrc` has specified `set tabstop=4`?

It is set to 4. But I will try to re-download my checkstyle again. Thank you

**Comment by RussellDash332** [comment]
Okay. I hope it works afterwards 😃
