### ISSUE TITLE
Repeated Question: E510: Can't make backup file (add ! to override)

### ISSUE THREAD

**Issue by yueyin22** [nus-cs2030/2122-s1#47]
# Description 
I know that someone raised this issue sometime back, and i followed the solution provided which was to key in `chmod 644 .backup`. However, it did not work for me. Any ideas?

Attached is my `ls -lah ~` alongside the output of `chmod 644 .backup`

## Screenshots (if any): 
![image](https://user-images.githubusercontent.com/79189775/132634192-254aeb39-ffbe-442d-b32f-952cd5a6bde1.png)

**Comment by RussellDash332** [comment]
To anyone reading this, the reference is #20 

The reason why it doesn't work is because you don't have the `.backup` file yet. Try running `touch .backup` and do the whole procedure again.

**Comment by yueyin22** [comment]
> To anyone reading this, the reference is #20
> 
> The reason why it doesn't work is because you don't have the `.backup` file yet. Try running `touch .backup` and do the whole procedure again.

I tried doing it inside my home directory as well as inside the directory 'Lab2', still didn't work for me

**Comment by RussellDash332** [comment]
Mind giving me the screenshots? Since you already have the `.backup` file, the output may be different from your original screenshot.

**Comment by Enigmatrix** [comment]
``~/.backup should be a directory, not a file. To create such a directory, you can do mkdir ~/.backup. To make sure it is accessible for writing (it should be, unless something strange has occurred), you can change the permissions via chmod 644 ~/.backup

**Comment by RussellDash332** [comment]
> `~/.backup` should be a directory, not a file. To create such a directory, you can do `mkdir ~/.backup`. To make sure it is accessible for writing (it should be, unless something strange has occurred), you can change the permissions via `chmod 644 ~/.backup`

Oh yes, thanks for correcting! It's a directory, and I have corrected my comments above 😅

**Comment by yueyin22** [comment]
@Enigmatrix @RussellDash332 
![image](https://user-images.githubusercontent.com/79189775/132646037-e84b0d32-bed1-4e95-939c-8e334c6963f9.png)
hmmm this is what i got after `mkdir ~/.backup`

**Comment by RussellDash332** [comment]
Oh the file exists, then just `chmod 644 ~/.backup`?

**Comment by RussellDash332** [comment]
Oh because you created the file earlier. Do this
```sh
rm ~/.backup
mkdir ~/.backup
```

**Comment by Enigmatrix** [comment]
If this issue is solved, please close it :) P.S. Don't worry - the issue doesn't get deleted.
