### ISSUE TITLE
tmux jshell output

### ISSUE THREAD

**Issue by cliftonfelix** [nus-cs2030/2122-s1#49]
I don't know whether this qn has been asked previously or not.

If we are using the normal ubuntu (not the tmux) and run the given test.jsh, we can scroll up and down to see the full output. However, when we are using tmux to split our screen, we cannot see the full output. It's hard to check the output especially for our Lab 3. Is there any way to solve this?

**Comment by RussellDash332** [comment]
No, this question has not been asked previously.
I also noticed this during yesterday's lab due to the long jshell execution.

Try `Ctrl+B` and then `:set -g mouse on`.
Note  that you don't need to do this when logging in to PE Node as they already provide you these settings.

**Comment by c0j0s** [comment]
you can also pipe the output to other programs such as `less` to view it as well.
like this `jshell .... | less`

**Comment by Polygonalr** [comment]
`Ctrl+B` (or `Ctrl+A` if you're using penode's tmux) + `[`, then use either arrow keys or page up/down to scroll. `Q` to exit scrolling mode.

**Comment by Polygonalr** [comment]
> 
> 
> > `Ctrl+B` (or `Ctrl+A` if you're using penode's tmux) + `[`, then use either arrow keys or page up/down to scroll. `Q` to exit scrolling mode.
> 
> This was my original solution but somehow we cannot use the mouse scroller to hover. Works with arrow keys anyways so I guess it's also viable.

My bad, after further testing I realised page up/down doesn't work in penode's tmux. Mouse scrolling is the fastest (and more precise) way to scroll, and your solution enables that.
