### ISSUE TITLE
Checkstyle giving error when indent 8 for line wrapping

### ISSUE THREAD

**Issue by hingen** [nus-cs2030/2122-s1#50]
In the Java style guide, it is mentioned that we should indent by 8 spaces for line wrapping.

However, when I indent by 8 spaces when initialising an array, `checkstyle`  gives me an error.
`'array initialization' child has incorrect indentation level 16, expected level should be 12.`

The following is an example that produces an error.
```
          int[] a = new int[] {01234567, 01234567, 01234567, 01234567, 01234567,  
                  01234567, 01234567};
```

Said error disappears when I switch to a 4 space indentation.
```
          int[] a = new int[] {01234567, 01234567, 01234567, 01234567, 01234567,  
              01234567, 01234567};
```

Anyone knows if this is an intended behaviour? If so, when should we use 4 space indentation instead of 8 when line wrapping?

**Comment by BrendanCheong** [comment]
4

**Comment by hingen** [comment]
> 4

why 4 though, why not indent by 8 spaces just like how line wrapping is specified in the Java Style Guide. Does array initialisation fall into a special case where 4 space indents should be used?

**Comment by Polygonalr** [comment]
CS2030S checkstyle is based off Google Java Style Guide. Check out here for Google's [guidelines on array initializers](https://google.github.io/styleguide/javaguide.html#s4.8.3.1-array-initializers). I believe what checkstyle expects is that your array should be declared like so:

```java
int[] a = new int[] {
    01234567, 01234567, 01234567, 01234567,
    01234567, 01234567, 01234567
};
```

**Comment by hingen** [comment]
> CS2030S checkstyle is based off Google Java Style Guide. Check out here for Google's [guidelines on array initializers](https://google.github.io/styleguide/javaguide.html#s4.8.3.1-array-initializers). I believe what checkstyle expects is that your array should be declared like so:
> 
> ```java
> int[] a = new int[] {
>     01234567, 01234567, 01234567, 01234567,
>     01234567, 01234567, 01234567
> };
> ```

ah that makes perfect sense. Thx for the link
