### ISSUE TITLE
LSP - Breaking the client's expectation 

### ISSUE THREAD

**Issue by zunedz** [nus-cs2030/2122-s1#51]
I am a bit not sure about what does breaking the client's expectation mean. For the example in recitations 2 and 3 (Rectangle and FormattedText), I think it is quite clear that the implementation violated LSP. However, I am not sure ***whether the class RecycledLoader (from lab 2) violates LSP*** since it can be interpreted as breaking the client's expectation, such that when the Loader class is replaced by RecycledLoader, the client would not expect to wait an hour after each usage of the loader? 

### Remark
I suspect that it violates LSP also because I think there is a better implementation of RecycledLoader and Loader, that is to create an Interface which both of the class implements, rather than extending the class. Thoughts?

**Comment by albertsutz** [comment]
This is just my opinion.

However, I somehow believe that implementing class that uses @Overload will always break LSP? Because when you change the functionality of a particular function from the parent class, the client's expectation (in this case the parent) will be broken.

For you remark, I think it kinda depends. Loader and RecycledLoader have so much in common that using interface would mean that you'll be copy and pasting a lot of codes?

**Comment by zunedz** [comment]
> This is just my opinion.
> 
> However, I somehow believe that implementing class that uses @overload will always break LSP? Because when you change the functionality of a particular function from the parent class, the client's expectation (in this case the parent) will be broken.


I agree with you, but maybe what you meant was overriding a method? I also thought that the whole point of method overriding is to modify the behavior of the overridden method, hence break the LSP. Is there any case of method overriding which does not break LSP? Please correct me if my understanding of LSP is wrong :(

**Comment by zunedz** [comment]
> For you remark, I think it kinda depends. Loader and RecycledLoader have so much in common that using interface would mean that you'll be copy and pasting a lot of codes?

I think yes, but does it break the abstraction or any other OOP principles I'm not sure.

**Comment by RussellDash332** [comment]
> if S is a subclass of T, then an object of type T can be replaced by that of type S without changing the desirable property of the program

According to LSP, what matters is ***the property***, so the methods can do different things but the desired properties, like the cruise (which means the cruise's properties) shall not be changed.
