### ISSUE TITLE
Lab 3: Incompatible types: RubikUp cannot be converted to Rubik

### ISSUE THREAD

**Issue by Hongyi6328** [nus-cs2030/2122-s1#52]
# Summary

Hi all,
I think Prof Chia has changed the test case, and I need to re-work my code now. I am up to test case 4.1.

## Description:

![image](https://user-images.githubusercontent.com/58073006/133553427-53b3b3ed-736f-449c-a68c-8f2d522520c8.png)
![image](https://user-images.githubusercontent.com/58073006/133553602-c73873ae-2c49-49f6-95ec-c75f1c2b5405.png)

I think the original test case does not contain the typecasting circled in red, but even now typecasting is added, I cannot figure out why this typecasting fails. 

## Code Snippets

![image](https://user-images.githubusercontent.com/58073006/133553874-45d4ed26-7ef3-4bdf-b825-a39bf27f7b5a.png)
This is my code for RubikUp. Since new RubikUp(rubik).left() shall return an instance of Rubik, I have no idea why the compiler thinks this method returns an instance of RubikUp and hence the failure of typecasting.

Thank you all!

**Comment by zunedz** [comment]
I think it's because your implementation of RubikUp is not a subclass of Rubik, hence it cannot be typecasted. I think the class RubikUp should extend the Rubik abstract class in order for it to compile.

**Comment by hauchongtang** [comment]
Correct me if i am wrong, but i think this is due to your `RubikUp` not being a subclass(child) of `Rubik`.
the typecast performs the same thing as:
`Rubik r = new RubikUp(rubik);`
So at compile time, it will fail since `RubikUp` is not a child of `Rubik` at all.

**Comment by Hongyi6328** [comment]
Thank you to zunedz and Hau Chongtang,

I didn't let RubikUp extend Rubik because I thought doing so would cause cyclic dependency between Rubik and RubikUp. Rubik is a parent of RubikUp, but instantiating RubikUp needs a Rubik as parameter. How to solve this?

**Comment by hauchongtang** [comment]
> 
> 
> Thank you to zunedz and Hau Chongtang,
> 
> I didn't let RubikUp extend Rubik because I thought doing so would cause cyclic dependency between Rubik and RubikUp. Rubik is a parent of RubikUp, but instantiating RubikUp needs a Rubik as parameter. How to solve this?

You could make you `RubikUp` dependent on `RubikFront` isnt it, since technically you can view RubikFront from another POV and this is `RubikUp`.

**Comment by Hongyi6328** [comment]
By making `Rubik `dependent on `RubikFront `do you suggest I let `RubikUp `extend `RubikFront`? Since `RubikFront `is a subclass of `Rubik`, cyclic dependency still occurs.

**Comment by cliftonfelix** [comment]
> Thank you to zunedz and Hau Chongtang,
> 
> I didn't let RubikUp extend Rubik because I thought doing so would cause cyclic dependency between Rubik and RubikUp. Rubik is a parent of RubikUp, but instantiating RubikUp needs a Rubik as parameter. How to solve this?

Hi Hongyi,
Cmiiw, I think there is no cyclic dependency here because when you let RubikUp extends Rubik, it means RubikUp depends on Rubik and when you initialize RubikUp using Rubik as a parameter, the RubikUp also depends on Rubik. So, there shouldnt be any cyclic dependency?

There is a cyclic dependency if let's say, in your Rubik class, it will call RubikUp. So, now, Rubik depends on RubikUp too and RubikUp depends on Rubik. Cmiiw :)

**Comment by Hongyi6328** [comment]
Thank you guys. The problems are solved by making `RubikUp` a direct subclass of `Rubik`, but I still think my code works only because all input instances of `Rubik` happen to be of `RubikFront`. What if the input was of, for example, `RubikUp`. Would it be an infinite loop? For example, if I call `toString()`, then will `RubikUp::toString()` be called for intinitely many times?

`class RubikUp extends Rubik {
    private final Rubik rubik;

    RubikUp(Rubik rubik) {
        this.rubik = rubik;
    }

    @Override
    Rubik left() {
        return this.rubik.upView().left().downView();
    }

    @Override
    Rubik right() {
        return this.rubik.upView().right().downView();
    }

    @Override
    Rubik half() {
        return this.rubik.upView().half().downView();
    }

    @Override
    public String toString() {
        return this.rubik.toString();
    }

    @Override
    Rubik leftView() {
        return this.rubik.leftView();
    }

    @Override
    Rubik rightView() {
        return this.rubik.rightView();
    }

    @Override
    Rubik upView() {
        return this.rubik.upView();
    }

    @Override
    Rubik downView() {
        return this.rubik.downView();
    }

    @Override
    Rubik frontView() {
        return this.rubik.frontView();
    }

    @Override
    Rubik backView() {
        return this.rubik.backView();
    }

    @Override
    public Rubik clone() {
        return new RubikUp(this.rubik);
    }
}`

**Comment by cliftonfelix** [comment]
I let RubikUp extends RubikFront. So, I just need to override 1 method (Right()), but idk whether it's a correct implementation or not.

**Comment by zunedz** [comment]
> Thank you guys. The problems are solved by making `RubikUp` a direct subclass of `Rubik`, but I still think my code works only because all input instances of `Rubik` happen to be of `RubikFront`. What if the input was of, for example, `RubikUp`. Would it be an infinite loop? For example, if I call `toString()`, then will `RubikUp::toString()` be called for intinitely many times? 

I think this won't cause infinite recursion, because, at one point RubikUp must have RubikFront as the input (if you think about it, the only Rubik Object that you can instantiate independently is RubikFront). Hence, indeed it will call the function recursively, but only until it reaches the RubikUp with RubikFront input.

**Comment by Hongyi6328** [comment]
> I let RubikUp extends RubikFront. So, I just need to override 1 method (Right()), but idk whether it's a correct implementation or not.

I see. I am not sure, too, whether it is okay to instantiate a child class with an instance of the parent class as a parameter, i.e., 
```
//RubikFront is a child class of Rubik
class RubikUp extends RubikFront {
    RubikUp(Rubik rubik) {
    //...
    }
}
```

**Comment by Hongyi6328** [comment]
> > Thank you guys. The problems are solved by making `RubikUp` a direct subclass of `Rubik`, but I still think my code works only because all input instances of `Rubik` happen to be of `RubikFront`. What if the input was of, for example, `RubikUp`. Would it be an infinite loop? For example, if I call `toString()`, then will `RubikUp::toString()` be called for intinitely many times?
> 
> I think this won't cause infinite recursion, because, at one point RubikUp must have RubikFront as the input (if you think about it, the only Rubik class that you can instantiate independently is RubikFront). Hence, indeed it will call the function recursively, but only until it reaches the RubikUp with RubikFront input.

Yes. So I think this strategy is only suitable in this particular case, but it kind of violates the principles we covered.
