### ISSUE TITLE
Comparator and Comparable

### ISSUE THREAD

**Issue by yuyanjulia** [nus-cs2030/2122-s1#54]
# Description

I thought comparator and comparable were the same thing during lecture .o. then I got the lecture quiz question on sorting SOC student wrong. Is it because if we have the Student class implementing the Comparable interface, only one compareTo method will be written, so it is very hard to sort by different criteria? But we can use a few classes to implement Comparator interface separately, i.e. one class for each criterion? Hope I am understanding this correctly now ;-;

## Topic:

Comparator, Comparable

## Screenshots

Screenshots (if any)

**Comment by Hongyi6328** [comment]
I think you are on the right track. `compareTo()` is built in the class you want to compare. `compare()` is a method in the individual 
 `Comparator` class, so it has more flexibility.

**Comment by yuyanjulia** [comment]
Thank you! Ohhh I just know I can write code like here `compareTo()` by clicking the button! Thanks
