### ISSUE TITLE
Why can't my subclass find my super class during compiling?

### ISSUE THREAD

**Issue by NicsunXnus** [nus-cs2030/2122-s1#55]
I have already compiled the Event class so i am not sure where the problem lies.
![project problem 1](https://user-images.githubusercontent.com/77189033/133871637-c719ed44-7c5b-4efd-b552-0f783a84959e.PNG)

**Comment by Irminrics** [comment]
Hello! 

Did you compile your event file using javac -q . Event.java? You can check the folders where your files are saved and check if the Java files are compiled in their correct packages. 

Another problem might be the fact that if they are in different folders, you may need to import them in the file you want to use them at.

**Comment by NicsunXnus** [comment]
Hello,thanks for the reply. I tried using  "javac -q . Event.java" but it says that there is no -q flag? How do I check whether my files are compiled in their correct packages as you say?

**Comment by hauchongtang** [comment]
I think it's supposed to be javac -d . Xxx.java

**Comment by NicsunXnus** [comment]
> 
> 
> I think it's supposed to be javac -d . Xxx.java
Yes this is the solution.
Thank you both for your help!
