### ISSUE TITLE
Launching WSL via Win+R

### ISSUE THREAD

**Issue by Mehvin** [nus-cs2030/2122-s1#6]
# Summary
Windows cannot find 'ubuntu' when win + r ubuntu

## Description 
From the wiki: To launch WSL, you can hit ⊞ Win + R and type in Ubuntu followed by enter.
However, this does not work.
Anyone else with the same issue?

## Screenshots (if any): 
![Capture](https://user-images.githubusercontent.com/19343031/128635474-1c95ebb8-e1de-4769-b837-f0aec3595f71.PNG)

**Comment by shazxrin** [comment]
I had the same issue but I solved it by typing in `wsl` instead of `Ubuntu`

**Comment by Mehvin** [comment]
thanks!
