### ISSUE TITLE
Failed to do Lambda

### ISSUE THREAD

**Issue by Hongyi6328** [nus-cs2030/2122-s1#61]
![image](https://user-images.githubusercontent.com/58073006/136022382-ad76fe41-a648-4247-b4a2-5bbaffd281b1.png)
This is exactly the same as the slide. I am wondering why this fails on my pc.

**Comment by RussellDash332** [comment]
Your first line is wrong. Do
`ImList<Integer> listInt = new ImList.<Integer>of(...)`

**Comment by Hongyi6328** [comment]
thank you Russel. I think the scope of `of()` is inferred when you don't explicitly specify it, so it doesn't make much difference. I tried what you suggest, but still the same.
![image](https://user-images.githubusercontent.com/58073006/136154749-4d059085-bdab-487d-852a-a9686d4f6fd0.png)
