### ISSUE TITLE
Unused Class for PA

### ISSUE THREAD

**Issue by cliftonfelix** [nus-cs2030/2122-s1#62]
If I already created a class during PA session, but I don't need it anymore. Should I:
1. Edit the file (modify it a bit so that it doesn't produce an error)
2. Remove the file (is it considered changing a lot?)

Thanks before

**Comment by zunedz** [comment]
I think it is better to leave it as it is (as long as it is compilable). This is to keep a high similarity between your final submission and your submitted code during PA.

**Comment by cliftonfelix** [comment]
umm make sense. Thanks.
