### ISSUE TITLE
Downcasting with a new instance vs the current object instance (this)

### ISSUE THREAD

**Issue by Gibson0918** [nus-cs2030/2122-s1#65]
# Description
Just wondering when should be I be returning this vs returning a new instance of the object? 
If I am returning this (the current object instance), will I be violating immutability? 

Also in Lab 5, if I attempt to return a new KeyableMap object then there will be an ClassCastException error when casting it to either a module/student. But returning this (same object instance) seems to be fine.

**Comment by RussellDash332** [comment]
It's actually a good thing that the class is mutable. Otherwise we might even need to use recursion for the HashMaps 😳😳
