### ISSUE TITLE
Not sure how to find the account slip for SSH purposes

### ISSUE THREAD

**Issue by yuqitanyq** [nus-cs2030/2122-s1#7]
# Summary
Not sure what is the userid and hostname to put when trying to ssh, and not sure how to find the account slip.

## Description 
Good morning prof, I was trying to set up the SSH through sunfire to access the PE nodes, but am unsure what is the userid and hostname to put, and not sure what is the account slip that the instructions are referring to. Is this a step that is only to be done when the labs start and when the PE nodes are up? I was hoping that you could clarify! Thank you!

## Screenshots (if any): 
Insert Images here if necessary
![image](https://user-images.githubusercontent.com/83687861/128651402-5f17943e-2bdb-4157-a199-8bfe757711bd.png)

**Comment by hwkchia** [comment]
Don't worry about the SSH part yet as we need to prepare the accounts.  As long as you get java and vim set up on your own machine, you are in pretty good shape.

**Comment by yuqitanyq** [comment]
Okay got it, prof! Thanks! Can I also check if it's okay to modify the .vimrc file to add in some other settings? or must we use the default .vimrc file as it is?
