### ISSUE TITLE
How to input test cases into jshell without exiting jshell after it runs

### ISSUE THREAD

**Issue by AHerdOfHLMilk** [nus-cs2030/2122-s1#73]
Found it a little annoying that jshell always exits after the test cases run, been wanting to test on the go without having to vim into the test.in files. Tried removing the /exit at the end of the input files, but jshell still exits. Is there any ways to stop exiting jshell?

**Comment by Enigmatrix** [comment]
@RussellDash332 strange, works fine on my side. Is there a lingering `/exit` in testN.jsh?

**Comment by RussellDash332** [comment]
> @RussellDash332 strange, works fine on my side. Is there a lingering `/exit` in testN.jsh?

Nope, I removed it

**Comment by Eclipse-Dominator** [comment]
@RussellDash332 try type `cat file.jsh -` alone, does the stdIn break?

**Comment by Eclipse-Dominator** [comment]
right redirect was the right term, I forgot about it when I was typing the reply haha

**Comment by RussellDash332** [comment]
> @RussellDash332 try type `cat file.jsh -` alone, does the stdIn break?

Still willing to echo whatever I type next when I enter.
![image](https://user-images.githubusercontent.com/63991775/136663378-f0056799-f2f8-4747-8761-3155cecfb4a2.png)
