### ISSUE TITLE
Level 3 - How do we put modules in Student instance without modifying the HashMap variable

### ISSUE THREAD

**Issue by optionalemon** [nus-cs2030/2122-s1#75]
## Description:

I realise that in test3:

jshell> Student natasha = new Student("Natasha");
jshell> natasha.put(new Module("CS2040").put(new Assessment("Lab1", "B")))
$.. ==> Natasha: {CS2040: {{Lab1: B}}}
jshell> natasha.put(new Module("CS2030").put(new Assessment("PE", "A+")).put(new Assessment("Lab2", "C")))
$.. ==> Natasha: {CS2030: {{Lab2: C}, {PE: A+}}, CS2040: {{Lab1: B}}}

Natasha actually has both modules through put() function. As my code returns a new Student, it does not seem to fall under natasha (since the test case does not have a 'Student Natasha ='), what method can we use to put module inside instance Natasha without modifying the HashMap list in the original class?

My code is below in case needed

## Code Snippets

    Student put(Module mod) {
        Map<String,Module> newList = new HashMap<String,Module>(this.modList);
        newList.put(mod.getKey(),mod);
        return new Student(this.name,newList);
    }

**Comment by cliftonfelix** [comment]
You do not need to create newList. You shd directly put the (mod.getKey(), mod) to this.modList, then return this.

**Comment by cliftonfelix** [comment]
> > Hi optionalemon,
> > I don't think there is a need to return a new Student object for the put method since a HashMap is meant to be mutable if I am not wrong. So you can simply return this. In level 4, you will implement a KeyableMap class(which is meant to be mutable) for module and student to extend.
> 
> Hi, does that mean HashMap doesn't have to be a final variable since it is mutable? I thought in this mod all attributes of a class should be immutable and final.

If I'm not wrong, a final hashmap means that the reference for that hashmap cannot be changed, but the elements inside can be edited

**Comment by RussellDash332** [comment]
> If I'm not wrong, a final hashmap means that the reference for that hashmap cannot be changed, but the elements inside can be edited

Correct, you cannot reassign the hashmap into a new one but you can reassign or modify the contents inside a hashmap.
