### ISSUE TITLE
Lecture 8: Is there a case where combiner and accumulator are unequal and yet can be parallelised?

### ISSUE THREAD

**Issue by cheeheng** [nus-cs2030/2122-s1#78]
# Description

For the stream parallel reduce method, give an application where the combiner and accumulator are not identical and yet satisfy the compatible property.

**Comment by hingen** [comment]
> Can this be parallelised? It violates the condition of accumulator(identity, t) = t (as shown in lecture slides), but looks like it will work just fine.

no it doesn't break the rule. Let's say I'm adding 1 to 5 to 1 (`1 + 1 + 2 + 3 + 4 + 5`). The identity is 1.

When I run the code, let's say it ran on 2 threads, one that computed `1 + 1 + 2 + 3 + 4 + 5` and the other that didn't compute anything and just had the identity, 1.

When I combine them using 'combiner.apply(identity, i)', 'i' will be returned.
x is 1 + 1 + 2 + 3 + 4 + 5 = 16
y is 1
16 + 1 - 1 = 16
