### ISSUE TITLE
Lecture 8: Single-use property of streams

### ISSUE THREAD

**Issue by cheeheng** [nus-cs2030/2122-s1#79]
# Description

I would like to understand why Java Streams are single-use by design (once the elements are iterated, they cannot be used again).

Is there a way to 'clone' an unused stream to avoid duplication of code?

**Comment by RussellDash332** [comment]
Of course, just like slide 9 of this week's lecture, you can put them inside a function!
![image](https://user-images.githubusercontent.com/63991775/136748574-c7aa9b56-6a24-4566-a610-1c35c9ab1fce.png)

**Comment by SimJM** [comment]
To "copy" or "clone" a stream, you can try storing it as a List and then convert it back to stream when you want to use it. Not sure if this is a good design but if you really want to copy or clone, this is a way to do it.
For example, using .toList() to convert an int stream to list.
List<Integer> list = stream.collect(Collectors.toList());
then use flatMapToInt() to convert list of integers back to IntStream.
list.stream().flatMapToInt(IntStream::of);

**Comment by cheeheng** [comment]
Ok thanks, I got it now.
