### ISSUE TITLE
Unable to set up Unix and install Ubuntu

### ISSUE THREAD

**Issue by Twars2** [nus-cs2030/2122-s1#8]
# Summary
I followed the steps on the wiki however when I try to run "Ubuntu" it says no program has been found. 

## Description 
I ran Windows PowerShell as administrator. I followed the steps on the wiki however I was unable to set the default wsl version to 1 as I encountered an error. The steps after that ran fine. I proceed to run "Ubuntu" using windows + r but the error message below appeared. I use the search menu to find Ubuntu 1804 and I received this error. I have removed the Linux feature on the control panel and reinstalled however it does not work.

## Screenshots (if any): 
1) Error from setting the wsl version to 1
![Capture1](https://user-images.githubusercontent.com/79690596/128666809-62e8886f-8615-47b5-a89d-f5ef7511b553.PNG)

2) Steps from the Powershell
![Capture](https://user-images.githubusercontent.com/79690596/128667659-d739761d-5d45-4a74-bbb9-e75808ee06bd.PNG)

3) Error from running Ubuntu
![Capture2](https://user-images.githubusercontent.com/79690596/128667674-9aa39426-a9bc-4a0e-8612-0ad90360592c.PNG)

4) Opening Ubuntu from search bar
![Capture6](https://user-images.githubusercontent.com/79690596/128667683-0d4fe122-a09d-4c89-aa13-60af2cd56c83.PNG)

**Comment by Hongyi6328** [comment]
I encountered the same problem but it works now.
1. Kindly search for "Windows features" on your device and you would find a page under the control panel.
2. Try to untick "Windows subsystem for Linux" (if it is ticked) and click on OK, and then the computer would prompt you to restart. Make sure everything is saved and restart.
3. Repeat Step 1, but at this time, tick "Windows subsystem for Linux" again and restart just like Step 2.
4. Done. Return to PowerShell now.

**Comment by Lippy21** [comment]
Thanks Hongyi! Everything works smoothly in PowerShell administrator up until running Ubuntu. After keying in 'Ubuntu' and pressing enter, the error message "Windows cannot find 'Ubuntu'" still pops up. This goes the same for one of my friends. Seeking any solutions for this problem

**Comment by Lippy21** [comment]
Ok, resolved. after the steps listed by Hongyi, can just open up Ubuntu and let it install itself. Once the installation is done:

1. Key in your Unix username
2. Key in your Unix password
3. You are in Unix alr and can start inputting the various commands from the instructions manual eg. sudo apt update etc.

**Comment by Hongyi6328** [comment]
The same. It is not a big problem though, as long as you can open Ubuntu from your start menu or via the search function. You don't have to open it by pressing win+R.

**Comment by Hongyi6328** [comment]
> Thanks Hongyi! Everything works smoothly in PowerShell administrator up until running Ubuntu. After keying in 'Ubuntu' and pressing enter, the error message "Windows cannot find 'Ubuntu'" still pops up. This goes the same for one of my friends. Seeking any solutions for this problem

It is not a big problem though, as long as you can open Ubuntu from the start menu or via the search function. You don't have to open it by pressing win+R every time.
Cheers!

**Comment by Twars2** [comment]
Thanks Hongyi I can open the shell to but only through the search bar function.

**Comment by kiwizop** [comment]
Hello Twars2, Ubuntu can be opened by typing wsl into window+R or cmd

**Comment by RicharCd** [comment]
I just found out the right term to open Ubuntu 18.04 is `ubuntu1804`

So essentially, you could open ubuntu through all the above mentioned means by everyone else (search bar, cmd or wsl), but if you want to use the run command on Windows, you can

1. Press `Win` Key + `R` to open the run command
2. Type in `Ubuntu1804` (or `ubuntu1804`)

[Source at the third line of description](https://www.microsoft.com/en-sg/p/ubuntu-1804/9n9tngvndl3q?activetab=pivot%3aoverviewtab#)
