### ISSUE TITLE
How to safely typecast in lab5?

### ISSUE THREAD

**Issue by xzzz3** [nus-cs2030/2122-s1#82]
# Summary
My current implementation requires me to typecast a parent (keyablemap) to a child (student), which gives the error ClassCastException. how should I overcome this?

## Description:
In the qn prompt it was hinted (or stated?) that we should typecast the keyablemap to a student object. however, my student object currently extends keyablemap, and that will make it a narrowing typecast in the compiler's perspective, even if I know that my code is completely safe and not narrowing anything. is there a way to solve this? or is my implementation already wrong? 

thank you in advance!

**Comment by RussellDash332** [comment]
> My implementation is the same as Bryan. I override put method in both Module and Student classes.

Might as well do the same for Roster. 😆

**Comment by xzzz3** [comment]
thanks for the replies, I have solved it!
