### ISSUE TITLE
How would you implement a customer queue for each server?

### ISSUE THREAD

**Issue by hauchongtang** [nus-cs2030/2122-s1#98]
I understand that adapting from level 1 to 2 would require a queue for each server. I have no problems scheduling a Wait event when my server queue has capacity to take in more customers. However, since we trigger a Serve event from the Wait class itself, I am currently getting for eg `timeX 9 serves by server 1 and timeX 10 serves by server 1` concurrently.
how can we do it from the customer queue of a server for level 2 requirements?

**Comment by upabove122** [comment]
I'm not too sure what you are going for, but wouldn't different events be prioritized ahead of the other such that it is not concurrent?

**Comment by c0j0s** [comment]
Have you tried implementing states for your server? you can avoid the concurrent issue if the loop knows the current state of your server. eg if ur server is busy, then schedule a wait event.

**Comment by jerylseow** [comment]
I think there are a few ways to do it, depending on how you've implemented the rest of your code. You can try having a attribute/method within Server that keeps track of its nextAvailableTime. Every time you trigger a Serve event using a particular Server, you will trigger it using that Server's nextAvailableTime. Remember to update the Server's nextAvailableTime afterwards (something like `server.nextAvailableTime += customer.serviceTime`).

**Comment by ryanwalterlee** [comment]
I use a nextAvailTime() method that checks the serving time of curr customer and everyone in the queue

**Comment by hauchongtang** [comment]
thanks for the suggestions guys !
